SparkPost/2web2ui

package-lock.json, package.json, src/components/Layout/Layout.module.scss, src/components/Navigation/Navigation.js, src/components/Navigation/Navigation.module.scss, src/components/Navigation/navItems.js, src/index.scss
- Makes side navigation responsive
- We now have an empty top bar on smaller screens. Have room to put in the SP logo or other actions.
- Also scales root font-size at breakpoints. All the MB components use REMs for sizing so we can scale the UI proportionally whenever we want.
=> Responsive Nav

src/actions/reportFilters.js, src/helpers/metrics.js, src/pages/reports/components/DateFilter.js, src/pages/reports/components/DateFilter.module.scss, src/pages/reports/components/DateForm.js, src/pages/reports/components/DateForm.module.scss, src/reducers/reportFilters.js
- Selecting "Custom" opens Datepicker
- Datepicker & Date fields stay in sync
- Date Fields are validated on blur
- Dates must be valid dates
- From must be before To
- To must be before now
- Must match `MM/DD/YY` and `h:mma`
- Reverts to previous dates if invalid
=> Date range management FAD-5334

config/webpack.config.dev.js, config/webpack.config.prod.js, package.json, public/index.html, src/critical.scss, src/index.js, src/index.scss
- Both global and module css now extract to `.css` files.
- All css is now minified
- CSS in `critical.scss` inlines inside `<head>`
- Adds a loading screen with the SP logo
=> Critical CSS & Production build fixes

src/helpers/chart.js, src/helpers/metrics.js, src/pages/reports/SummaryPage/SummaryPage.module.scss, src/pages/reports/SummaryPage/components/ChartGroup.js, src/pages/reports/SummaryPage/components/LineChart.js, src/pages/reports/SummaryPage/components/LineChart.scss, src/pages/reports/components/DateFilter.js, src/reducers/reportFilters.js
- Closes #49
- When `precision` = `1min`, shows ticks every 15 minutes
- When `precision` = `15min`, shows ticks every 30 minutes
- Relative range dropdown works again.
- Adds y axis labels
- Closes #63
- fixes for percent graphs - forces 0 - 100 domain
- 0 - 100 also used if no data exists
- Adds extra padding above the highest line inside a graph
- Added `getYTicks` to format y axis ticks
- for linear percent graphs: `[0, 25, 50, 75, 100]`
=> Summary Chart Improvements

src/pages/Templates/EditPage.js, src/pages/Templates/ListPage.js, src/pages/Templates/PublishedPage.js, src/pages/Templates/components/Editor.js, src/pages/Templates/components/Editor.scss, src/pages/Templates/components/Form.js, src/pages/Templates/components/FormEditor.module.scss, src/pages/Templates/components/ToggleBlock.js
- Some global styles to override ace editor styles
- Cleanup, uses `loading` layout prop, shared redux textfield wrapper, etc
- Started some setup for the test data ticket
=> Templates Editor FAD-5345

src/components/auth/AccessControl.js, src/components/auth/tests/AccessControl.test.js, src/components/auth/tests/__snapshots__/AccessControl.test.js.snap, src/selectors/navItems.js
This is the bug where account mysteriously disappears from the nav after logout/login ... when the grants aren't found in the cookie (so first login or logout/login), it would compute access for nav items before it had grants and replace their children with empty arrays because none of the children had access yet. By the time we re-calculated it was too late and we had already mutated the children so they were gone forever, so we remove the parent too since none of the children were there.
Whole fix is just this:
```diff
export function filterNavByAccess(items, accessConditionState) {
-  return items.filter((item) => {
+  return items.filter((reference) => {
+    const item = { ...reference }; // prevent weird mutation bugs
```
I also added a memoize around the mapping of the nav items so …
=> Fixes recursive mutation bug in nav render

package.json
This is to enforce our "Don't use lodash _.chain" rule.
=> Enforce lodash/chaining never linting rule

src/components/navigation/Footer.js, src/config/navItems.js, src/config/routes.js, src/pages/comingSoon/ComingSoonPage.js, src/pages/comingSoon/tests/ComingSoonPage.snapshot.test.js, src/pages/comingSoon/tests/__snapshots__/ComingSoonPage.snapshot.test.js.snap, src/pages/index.js, src/pages/recipientLists/ListPage.js, src/pages/templates/EditPage.js, src/pages/trackingDomains/components/TrackingDomainRow.js
- Added a ComingSoonPage with only an EmptyState in it.
- Added the following coming soon pages:
- reports
- rejections
- accepted
- delayed
- engagement
- lists
- recipient lists -> create
- suppression lists
- account
- security
- sending domains
- smtp relay
- Fixed a lint issue in tracking domains
- Did *not* add account -> usage since its a dup of the dashboard. TBD?
- ComingSoonPage view and copy could use a sense of humour.
- A modal might be nicer for recipient lists -> create
- ~My test snapshots are made in GMT so any with dates will fail outside the UK (!).~ Sidestepped with `TZ=` env variable. Better fix in progress on `feature/FAD-5876`.
- The bounce report snapshot contains an ID attribute not in the snapshot. Just an out of date snapshot?
```
FAIL …
```
=> FAD-5884: coming soon pages

src/actions/reportFilters.js, src/actions/summaryChart.js, src/actions/tests/reportFilters.test.js, src/pages/reports/accepted/AcceptedPage.js, src/pages/reports/accepted/tests/AcceptedPage.test.js, src/pages/reports/bounce/BouncePage.js, src/pages/reports/bounce/tests/BouncePage.test.js, src/pages/reports/delays/DelayPage.js, src/pages/reports/delays/tests/DelayPage.test.js, src/pages/reports/engagement/components/EngagementFilters.js, src/pages/reports/engagement/components/tests/EngagementFilters.test.js, src/pages/reports/rejection/RejectionPage.js, src/pages/reports/rejection/tests/RejectionPage.test.js, src/pages/reports/summary/SummaryPage.js, src/pages/reports/summary/tests/SummaryPage.test.js
This is half of the work needed to fix the issue in FAD-6194, so we are cutting it loose and pushing it out. The rest of the work will be done in #276 and pushed ASAP
=> FAD-6194 (b) only initialize typeahead cache once

package-lock.json, package.json, src/components/collection/SortLabel.module.scss, src/components/collection/TableCollection.js, src/components/collection/TableCollection.module.scss, src/components/layout/Layout.module.scss, src/components/navigation/Navigation.module.scss
MB
- Fixes EmptyState svg styling that broke in 2.0.0
- Removes pastel background colors from Banner
- Removes white Tooltip borders
- Removes text-decoration from `a` links globally
- Adds UnstyledLink proptypes and story
- Removes word break from table headers
App
- Removes blue `focus` text color on nav items
- Darkens nav nested children background
- Fixed sort icon spacing on summary chart table
- Prevent tables from overflowing on smaller screen sizes
- They are now more responsive than before, but will need a better solution long term
=> Hotfix/mb 2.0.4

src/actions/trackingDomains.js, src/components/auth/ProtectedRoute.js, src/config/routes.js
`trackingDomains/CreatePage.js` is missing`history.push`.
This ticket:
- includes @jasonrhodes fix which passes react-router props down from `ProtectedRoute`
- improves error messages on tracking domain create using `src/helpers/apiMessages.js`
- Create a new tracking domain - watch it succeed
- Create a pre-existing tracking domain - watch it fail and give error details about the clash
=> FAD 6221: Tracking domains create throws after creation

src/pages/billing/SummaryPage.js, src/pages/billing/tests/SummaryPage.test.js
For non-free, self-billed accounts, `/account/billing` is meant to show a billing address and CC summary and a form for buying dedicated IPs.
Neither currently show because they use a condition variable based on `/account?include=billing`. Auth stopped loading billing details some time ago and so both parts of the billing page stayed hidden.
The fix below is to have the billing page preload account billing details on mount.
- Create a self-billed non-free account
[This page](https://confluence.int.messagesystems.com/pages/viewpage.action?pageId=43157618) may be useful in creating that account ;)
- Visit /account/billing
- Verify that billing address and CC details are visible
- Verify that you can buy dedicated IPs
=> FAD-6241: Missing billing summary and dedicated IPs purchase forms

src/pages/reports/messageEvents/EventPage.js, src/pages/reports/messageEvents/MessageEventsPage.js, src/pages/reports/messageEvents/components/ViewDetailsButton.js, src/pages/reports/messageEvents/components/ViewDetailsButton.module.scss, src/pages/reports/messageEvents/components/tests/ViewDetailsButton.test.js, src/pages/reports/messageEvents/components/tests/__snapshots__/ViewDetailsButton.test.js.snap, src/pages/reports/messageEvents/tests/MessageEventsPage.test.js, src/pages/reports/messageEvents/tests/__snapshots__/MessageEventsPage.test.js.snap
See ticket for the detail context
Didn't find a easy way to manually test it. It would be good if I could modify redux store to modify the data but didn't find a way even though feel like there is a way. 
However, this is pretty trivial and easy enough to verify from snapshot. 
*Update*
Testing:
You can test it using redux dev tool. Click 'Dispatcher'. 
put something like:
```
{
type: 'GET_MESSAGE_EVENTS_SUCCESS',
payload: [{
formattedDate: 'formatted',
type: 'injection',
friendly_from: 'mean@friendly',
rcpt_to: 'tom.haverford@pawnee.state.in.us',
message_id: '123abc',
event_id: '456xyz'
}, {
formattedDate: 'formatted',
type: 'policy_rejection',
friendly_from: 'mean@friendly',
rcpt_to: 'tom.haverford@pawnee.state.in.us',
event_id: '456xyz'
}]
}
```
And then click tiny little almost …
=> FAD-6234 Hide view details button when message_id does property does not exist

src/actions/templates.js, src/actions/tests/__snapshots__/templates.test.js.snap, src/actions/tests/templates.test.js
- `{"name": "blarg"}`
- `{"substitution_data": { "name": "blarg"} }`
- `{"substitution_data": { "name": "blarg"}, "metadata": { "k" } }`
- `{"substitution_data": { "name": "blarg"}, "metadata": { "k" }, "options": { "w": "asdf" } }`
=> FAD-6222: getTestData action creator now supports old style template test data

package-lock.json, package.json, public/static/tenant-config/production.js, src/App.js, src/components/siftScience/SiftScience.js, src/components/siftScience/tests/SiftScience.test.js, src/components/siftScience/tests/__snapshots__/SiftScience.test.js.snap, src/constants/index.js
_Refer to [FAD-6109](https://jira.int.messagesystems.com/browse/FAD-6109) for AC_
The intention of this PR is to integrate with Sift Science (SS) similar to the webui setup.
**About SS JavaScript Snippet**
Here are the [installation instructions](https://siftscience.com/developers/docs/javascript/javascript-api).  Communication is done by pushing one of the following events on a global variable, `window._sift`, and letting the snippet process them as needed.
* _setAccount - set with [Javascript Snippet Key](https://console.siftscience.com/developer/api-keys)
* _setUserId - set with user's customer ID (account prefixed if available)
* _setSessionId - set with a UUID that is shared our other sites (e.g. [sparkpost.com](https://github.com/SparkPost/sparkpost.com/blob/8bf34fd430e4ed55843040c07 …
=> FAD-6109 Support necessary Sift Science events

src/components/subaccountTypeahead/SubaccountTypeahead.js
Symptom: subaccount typeahead does not show newly created subaccounts until the app is hard refreshed.
Fix: Subaccount typeahead now always (re)loads subaccounts if the account has them.
1. Create a subaccount
1. Create a sending domain and assign it to the new subaccount
1. Win 🎉
=> FAD-6296: Subaccount typeahead only loads subaccounts once

src/selectors/api-keys.js, src/selectors/tests/api-keys.test.js
Peeked in to test a theory and it was right, so here we are with a fix! Summary:
* In FAD-6296 we made the SubaccountTypeahead re-fetch subaccounts on every mount. 
* In the Create and Details pages for the API Keys section, if `props.loading` is true, we render the `<Loading>` component, otherwise we render the page.
* The `loading` prop for both of these pages is from a selector that was checking if the subaccounts list was loading
* When the page stops loading, it mounts the `<ApiKeyForm>` which loads the typeahead, which mounts and re-fetches the subaccounts list, which makes subaccounts loading true, which puts the Create/Details page back into "loading" state, which then causes a remount  ............
**Easiest fix was to remove the check on subaccounts list loading for that …
=> FAD-6311 removed check for subaccount list loading to prevent infinite remounts

src/helpers/date.js, src/helpers/metrics.js, src/helpers/tests/__snapshots__/metrics.test.js.snap, src/helpers/tests/date.test.js, src/helpers/tests/metrics.test.js
Added timezone using native JS method, support seems good (no IE, missing some Android webview)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions
=> FAD-6305 send dates to metrics API with local timezone

src/pages/recipientLists/CreatePage.js, src/pages/recipientLists/components/RecipientListForm.js, src/pages/recipientLists/components/tests/RecipientListForm.test.js, src/pages/recipientLists/components/tests/__snapshots__/RecipientListForm.test.js.snap
Issue: We were using `throw SubmissionError()` along with component state to artifically handle CSV parsing errors. Also, constructing SubmissionError without an argument does not set the redux-form error state.
Fix: Use redux-form submission errors properly: `throw SubmissionError({ _error: '...'})` to stop form submission and set the form-connected components `error` prop on CSV parsing errors.
(Also fixed some broken language in `recipientLists/CreatePage.js`)
Create or update a recipient list with the following CSV file:
```
ewan,dennis
sue,storm
colin,powell
hidalgo,mundungus
bobby,brown
afifth,error
asixth,error
aseventh,error
```
=> FAD-6314: Handler rcpt list CSV errors properly

src/pages/join/JoinPage.js, src/pages/join/tests/JoinPage.test.js, src/pages/onboarding/ChoosePlan.js, src/pages/profile/components/DisableTfaModal.js, src/pages/profile/components/EnableTfaModal.js, src/pages/profile/components/TfaManager.js, src/pages/profile/components/tests/TfaManager.test.js, src/pages/profile/components/tests/__snapshots__/DisableTfaModal.test.js.snap, src/pages/profile/components/tests/__snapshots__/EnableTfaModal.test.js.snap, src/pages/profile/components/tests/__snapshots__/TfaManager.test.js.snap, src/pages/reports/components/Typeahead.js, src/pages/reports/components/tests/Typeahead.test.js, src/pages/reports/components/tests/TypeaheadItem.test.js, src/pages/reports/components/tests/__snapshots__/Typeahead.test.js.snap, src/pages/reports/components/tests/__snapshots__/TypeaheadItem.test.js.snap, src/selectors/accountBillingForms.js, src/selectors/tests/__snapshots__/accountBillingForms.test.js.snap, src/selectors/tests/accountBillingForms.test.js
Issue: Downshift had a hidden current selection prop.
- We now clear that state with `clearSelection()` on focus of the typeahead `TextField`.
- Also added to Typeahead tests
1. Visit a report
1. Type `gmail.com` into the filter typeahead and hit return
1. Note the added filter
1. Remove the `gmail.com` filter
1. Re-add it using the typeahead
Issue: External links to `/join` sometimes include a `plan=...` query param which we should use to pre-populate the plan picker during the onboarding flow.
- `/join` stashes the `plan` param in router state with `history.push(route, {plan: whatever})`
- `/onboarding/plan` extracts `plan` from `props.location.state` and sets the plan picker initial value
- I took some care to deal with invalid values of `plan` since its tainted
Note: I didn't bother …
=> FAD-6343 and friends

src/components/smtpDetails/SmtpDetails.js, src/components/smtpDetails/tests/__snapshots__/SmtpDetails.test.js.snap, src/pages/billing/components/BillingSummary.js, src/pages/billing/components/DedicatedIpCost.js, src/pages/billing/components/DedicatedIpSummarySection.js, src/pages/billing/components/tests/DedicatedIpCost.test.js, src/pages/billing/components/tests/DedicatedIpSummarySection.test.js, src/pages/billing/components/tests/__snapshots__/DedicatedIpSummarySection.test.js.snap, src/pages/templates/components/PreviewFrame.js, src/pages/webhooks/components/Fields.js, src/selectors/accountBillingInfo.js, src/selectors/tests/accountBillingInfo.test.js
Issue: for...of isn't well supported on DOM collections
Fix: Use `[...collection].forEach()`
Testing: Use Edge (!) or an old Safari to preview a template containing a link. Or just eyeball the patch in this PR.
Issue: we show AWS users incorrect monthly IP pricing in the billing summary
Fix: Pull the AWS account state from subscription details and the correct pricing from config
Testing: Use React dev tools to set isAWSAccount on the BillingSummary under `/account/billing` and voila.
Also fixed a type on `/account/smtp`.
Issue: Active webhooks appear inactive in our edit form and confuse the rest of the form's `dirty` state.
Fix: Tie our `<Checkbox />` `checked` state to `input.value` from redux-form.
Testing: Visit an active webhook and verify:
- the active checkbox shows the correct …
=> FAD-6372 and friends

src/pages/templates/components/PreviewFrame.js, src/pages/templates/components/tests/__snapshots__/PreviewFrame.test.js.snap
Refer to [FAD-6395](https://jira.int.messagesystems.com/browse/FAD-6395).
=> FAD-6395: Users are unable to open links when previewing a template in certain browsers

src/helpers/axiosInstances.js
Here's how I verified this:
1. Run the accusers API locally with nginx pointed locally for the accounts upstream
1. Log cookie from AWS Marketplace validator:
```diff
diff --git a/api/lib/validator/aws-marketplace.js b/api/lib/validator/aws-marketplace.js
index 758b6ded..106a9f0d 100644
--- a/api/lib/validator/aws-marketplace.js
+++ b/api/lib/validator/aws-marketplace.js
@@ -19,6 +19,9 @@ const { SpResponseError } = require('@sparkpost/msys-middleware');
function AwsMarketplaceValidator(req, res, next) {
const cookieValue = req.signedCookies['aws-mkt'];
+  console.log('in aws marketplace validator ... COOKIE TIME');
+  console.log(req.signedCookies);
```
1. Visit locally running UI (on master first) by going to https://app.sparkpost.test:3100/join **important: make sure you visit at …
=> FAD-6392 add withCredentials so that cookies are properly passed to the server

src/config/routes.js, src/pages/templates/EditPage.js, src/pages/templates/ListPage.js, src/pages/templates/PreviewPage.js, src/pages/templates/PublishedPage.js, src/pages/templates/components/Form.js, src/pages/templates/components/async/Editor.js, src/pages/templates/components/tests/Form.test.js, src/pages/templates/components/tests/__snapshots__/Form.test.js.snap, src/pages/templates/containers/EditPage.container.js, src/pages/templates/containers/ListPage.container.js, src/pages/templates/containers/PreviewDraftPage.container.js, src/pages/templates/containers/PreviewPublishedPage.container.js, src/pages/templates/containers/PublishedPage.container.js, src/pages/templates/tests/EditPage.test.js, src/pages/templates/tests/ListPage.test.js, src/pages/templates/tests/PreviewPage.test.js, src/pages/templates/tests/PublishedPage.test.js, src/pages/templates/tests/__snapshots__/EditPage.test.js.snap, src/pages/templates/tests/__snapshots__/ListPage.test.js.snap, src/pages/templates/tests/__snapshots__/PreviewPage.test.js.snap, src/pages/templates/tests/__snapshots__/PublishedPage.test.js.snap
_Refer to [FAD-6126](https://jira.int.messagesystems.com/browse/FAD-6126)_
**Todo**
=> FAD-6126: Template list/preview access for reporting users

src/actions/recipientLists.js, src/helpers/axiosInstances.js
Removes all client-side-enforced HTTP timeouts
Also reveals recipient list create/update errors so we don't swallow 4xx errors by accident
=> FAD-6401 remove http timeouts

src/selectors/accountBillingInfo.js, src/selectors/tests/accountBillingInfo.test.js
**Test Cases**
- For ccfree1 account, confirm billing info is visible and can be updated
- For free account, confirm billing info is hidden
- For paid account, confirm billing info is visible and can be updated
=> FAD-6386 Legacy ccfree1 users can't update billing information

README.md
The readme said `npm install` will start a local dev server, but the command is actually `npm start` (if I'm reading the scripts right).
=> updates readme to add npm start command

docs/config.md, public/static/tenant-config/production.js, src/App.js, src/actions/cookieConsent.js, src/actions/currentUser.js, src/actions/tests/__snapshots__/cookieConsent.test.js.snap, src/actions/tests/cookieConsent.test.js, src/components/cookieConsent/CookieConsent.js, src/components/cookieConsent/CookieConsent.module.scss, src/components/cookieConsent/components/ConsentBar.js, src/components/cookieConsent/components/tests/ConsentBar.test.js, src/components/cookieConsent/components/tests/__snapshots__/ConsentBar.test.js.snap, src/components/cookieConsent/tests/CookieConsent.test.js, src/components/cookieConsent/tests/__snapshots__/CookieConsent.test.js.snap, src/components/index.js, src/config/default.js, src/config/test-config.js, src/helpers/cookieConsent.js, src/helpers/tests/cookieConsent.test.js, src/pages/join/tests/JoinPage.test.js, src/pages/sendingDomains/components/tests/EditBounce.test.js, src/reducers/cookieConsent.js, src/reducers/currentUser.js, src/reducers/index.js, src/selectors/cookieConsent.js, src/selectors/currentUser.js, src/selectors/tests/cookieConsent.test.js
- Main component is under `src/components/cookieBanner`
- App.js loads CookieConsent, making it visible e-v-e-r-y-w-h-e-r-e
- Banner shows only if `consent` has not been given
- Dismissing the banner gives consent
- Consent is stored in 2 places:
1. in a `cookieConsent` cookie (with absolutely no irony)
1. `PUT /user/{username}` `{ "cookie_consent": true }`
**Note: test config sets a cookie on `.sparkpost.test` so use `app.sparkpost.test:3100` or similar to access the app locally on your machine.**
- ~Avoid blocking page content~ - slightly better with wider banner
- ~Don't rely on post-auth content~
=> FAD-6286: GDPR cookie consent banner

src/components/cookieConsent/CookieConsent.js, src/components/cookieConsent/tests/CookieConsent.test.js, src/components/cookieConsent/tests/__snapshots__/CookieConsent.test.js.snap, src/reducers/cookieConsent.js
- Show the banner before `state.accessControlReady` since we want to show it on `/auth` and `/join`
- Reinstate `state.cookieConsent.cookieSet` from the cookie on `LOGOUT` to avoid showing the banner to a consenting user after logout
=> FAD-6286: fixes

src/components/collection/Pagination.js, src/components/collection/tests/__snapshots__/Pagination.test.js.snap
_Refer to [FAD-6389](https://jira.int.messagesystems.com/browse/FAD-6389) for AC._
**What to test?**
- The "Save as CSV" button is always visible at the bottom of the table collection.
- The table collection itself is not visible when there are no results.
=> FAD-6389: Allow saving to CSV on collections smaller than 1 page

src/helpers/errorTracker.js, src/helpers/tests/errorTracker.test.js
I used [Ferdinand](https://gist.github.com/bkemper/4c1e9a87f4b0b921711ea6791c265cc0) to test.
=> FAD-6462: Suppress Sentry errors from Chrome and Firefox extensions

public/index.html, src/critical.scss
Edit:
The styles seemed to break on `tst` because the main app styles still loaded while we were blocking only the main js bundle. This doesn't happen when running webpack locally because blocking bundle also means blocking css. `position: relative` was being added to `html`.
This pr will make sure `#error` works regardless of what other styles are loaded.
How I verified the build -
```
npm run build
cd build
php -S localhost:5000
```
=> FAD-6279 Fix error screen css

src/pages/reports/components/ShareModal.js, src/pages/reports/components/tests/ShareModal.test.js, src/pages/reports/components/tests/__snapshots__/ShareModal.test.js.snap
To verify:
- Go to message events list
- Add an email to recipients filter with a `+`, like `1+2@test.com`
- Refresh
- Check that the active filter and request does not replace the + with a space between 1 and 2
=> FAD-6475 Message events reports filter does not handle + in email addresses properly

src/helpers/billing.js, src/helpers/tests/__snapshots__/billing.test.js.snap, src/helpers/tests/billing.test.js
To test this, we can use the Braintree payment gateway AVS test data seen here:
https://developers.braintreepayments.com/reference/general/testing/node#avs-postal-code-responses
Specifically, that means using the postal code `20000` which will auto-trigger an `'N'` AVS response. In Braintree, we have it configured so that the `'N'` AVS response fails a transaction for a US-based card but is ignored for any other non-US card. So to test:
1. Sign up for a new account and upgrade from free to paid (in the onboarding flow or from the billing page after sign up, both ways should use the same exact code paths)
1. While upgrading, first use country: `United States`, zip/postal: `20000`
1. Observe the AVS failure in the red error bar (see screenshot)
1. Next, use country `United Kingdom`, …
=> FAD-6500 sends country with card info for AVS rule decision in gateway

src/actions/helpers/sparkpostApiRequest.js, src/actions/helpers/tests/__snapshots__/sparkpostApiRequest.test.js.snap, src/actions/helpers/tests/sparkpostApiRequest.test.js, src/components/auth/AuthenticationGate.js, src/components/auth/ProtectedRoute.js, src/components/auth/tests/AuthenticationGate.test.js
Functionally, the only differences here should be the following:
1) A user should no longer be immediately logged out on any 403
2) A user will see a one-time dismissible suspended account alert if their account status changes to 'suspended' at anytime, including initial login and page refresh. Account status is fetched after any 403 (usually from PUT, POST, or DELETE requests).
3) The generic error alert will display the error (e.g. 'Forbidden' if caused by suspension) if a request returns a 401 or 403.
4) All 401's result in a logout (unless it's a token refresh)
=> FAD-6437 Don't log out on 403s, force logout terminated customers

src/components/domainStatus/DomainStatusCell.js, src/components/domainStatus/ReadyFor.js, src/components/domainStatus/tests/ReadyFor.test.js, src/components/domainStatus/tests/__snapshots__/ReadyFor.test.js.snap, src/pages/sendingDomains/ListPage.js, src/pages/sendingDomains/components/SetupSending.js, src/pages/sendingDomains/components/StatusDescription.js, src/pages/sendingDomains/components/tests/__snapshots__/StatusDescription.test.js.snap, src/pages/sendingDomains/tests/__snapshots__/ListPage.test.js.snap
Adds the "Subaccount" label to the "Default" tag when a sending domain is the default for a subaccount.
Also solves the bug in FAD-6508 where we weren't passing subaccount into the verify by email modal so it wasn't passing the subaccount header in the request.
=> FAD-6476 Subaccount Default tag for sending domains, plus bugfix

src/pages/reports/summary/components/async/LineChart.scss
Bug was introduced in https://github.com/SparkPost/2web2ui/pull/417.
Tested in FF as well.
=> FE-290 Fix summary tooltip overlap

src/pages/suppressions/components/Results.js, src/pages/suppressions/components/tests/Results.test.js
Cause: Delete modal expects the suppression item to exist after deletion
Solution: Make delete modal resilient to missing state
No solution yet
=> FE-295: Fix Suppression delete operation

config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json, src/pages/billing/components/tests/Banners.test.js, src/pages/billing/forms/tests/ChangePlan.test.js
Merges in changes for autoprefixer, lint-staged, and jest-enzyme.
* lint-staged only had minor bugfixes, upgrade looks safe
* jest-enzyme had breaking changes removing `toBePresent` and replacing with `toExist`, so I swapped those in 2 test files
* autoprefixer was a major version change that mostly revolved around upgrading their Browserslist dependency, with a new way to specify config (they recommend to use the `browserslist` key in package.json or a `.browserslistrc` file in the project root so that all of your deps that may use browserslist functionality will be targeting your correct browsers and not falling back to a default). We pulled the newest create-react-app config for autoprefixer from here: https://github.com/facebook/create-react-app/blob/bf3d73c2c6fd78d4eea23f5356fb26f3232 …
=> FE-301 Update greenkeeper dev-deps

src/helpers/string.js, src/helpers/tests/string.test.js, src/pages/auth/AuthPage.js, src/pages/auth/tests/AuthPage.test.js, src/pages/auth/tests/__snapshots__/AuthPage.test.js.snap
_Refer to [FE-35](https://jira.int.messagesystems.com/browse/FE-35)_
**How to test locally**
- Load auth page with error param set to any base64 encoded string (e.g. http://app.sparkpost.test/auth?error=VW5hYmxlIHRvIGNyZWF0ZSB0b2tlbiBmb3IgU0FNTCB1c2VyLg%3D%3D)
**How to test in UAT**
1. Navigate to https://app-speuat.tst.sparkpost.com _[should load SparkPost authentication form and only ask for email or username]_
1. Enter "appteam+sso" _[should redirect to OneLogin authentication form]_
1. Enter "appteam" credentials from LastPass _[should redirect back to SparkPost authentication page with an error message]_
=> FE-35: Error not surfaced to user when SSO sign-in fails

public/index.html, src/actions/support.js, src/actions/tests/__snapshots__/support.test.js.snap, src/actions/tests/support.test.js, src/components/support/Support.js, src/components/support/components/SupportForm.js, src/components/support/tests/Support.test.js, src/pages/auth/AuthPage.js, src/pages/auth/tests/AuthPage.test.js, src/pages/defaultRedirect/DefaultRedirect.js, src/pages/defaultRedirect/tests/DefaultRedirect.test.js, src/reducers/support.js
Jira ticket: https://jira.int.messagesystems.com/browse/FE-292
---
Support ticket UI can be triggered through query params or through redux actions
```js
// Support component opens form and hydrates on mount
app.sparkpost.com?supportTicket=true&supportMessage=message&supportSubject=subject
```
```js
// Toggles the support panel UI
toggleSupportPanel()
// Toggles support ticket form (algolia search shown when false)
toggleTicketForm()     
// Fills support ticket form
hydrateTicketForm({ message, subject })
```
=> FE-292 Allow deep linking to in-app support

src/pages/reports/delays/DelayPage.js, src/pages/reports/delays/components/DelaysDataTable.js, src/pages/reports/delays/components/tests/__snapshots__/DelaysDataTable.test.js.snap, src/pages/reports/delays/tests/__snapshots__/DelayPage.test.js.snap
Revised the top level message a bit:
New
> **5,309** of **231,119** accepted messages were delayed on first attempt in the **last 24 hours**.
Old
>**5,503** of your messages were delayed of **233,189** messages accepted in the **last 24 hours**.
=> FE-307 Show total delays

src/helpers/subaccounts.js, src/helpers/tests/subaccounts.test.js, src/pages/webhooks/components/SubaccountSection.js, src/pages/webhooks/components/WebhookForm.js, src/pages/webhooks/components/tests/__snapshots__/SubaccountSection.test.js.snap
_Refer to [FE-313](https://jira.int.messagesystems.com/browse/FE-313)_
The originally reported issue is more an annoyance than a bug.  A webhook can listen for events for a all accounts, only the master account, or a designated subaccount.  The default was set to only the master account.  Which is annoying if you create a webhook, do a bunch integration work with it, then decide to create subaccounts.
While triaging/testing, I found a bug.  Here are the steps to reproduce.
1. With an account that has subaccounts.
1. Navigate to create webhook page <http://app.sparkpost.test/webhooks/create>
1. Fill-out all the required fields, select "Master and all subaccounts" option
1. Click "Create Webhook"
**Expected result:** After creation, you should be redirected to the edit page.
**Actual …
=> FE-313: Webhooks subaccount is getting set to 0 on create

src/pages/join/JoinPage.js, src/pages/join/tests/JoinPage.test.js, src/pages/join/tests/__snapshots__/JoinPage.test.js.snap
Now we read from the query string and merge those values on top of anything we find in the `attribution` cookie, and send the resulting merge along with the account create call. I verified this works in tst end-to-end from local UI to sandbox Salesforce (it wasn't easy either, so let me know if you are planning to try an end-to-end test of this).
This mainly fixes this bug:
* If the attribution cookie was mistakenly set to `{}` (or set to anything at all), we would ignore the query param data -- now we merge the query param data on top of the cookie data
We no longer store the cookie in this flow. As best as I can tell, the original tickets (FAD-4947 and FAD-4948) don't mention that requirement and nobody is aware of a reason for doing that.
=> FE-309 simplifies attribution on sign up

src/actions/billingCreate.js, src/helpers/errorTracker.js, src/pages/billing/forms/fields/PaymentForm.js, src/pages/billing/forms/fields/tests/__snapshots__/PaymentForm.test.js.snap
There are multiple ways to solve this but IMO this is simplest. So far it seems to be working fine but real test would be on tst/stg. 
other approaches
- rename fields
- set state locally 
- calculate these upon submit
all those require more work than this is. renaming field may be trivial but still can't be tested locally. 
https://cs.chromium.org/chromium/src/components/autofill/core/common/autofill_regex_constants.cc?l=135-194 is the regex chrome use for field matching. as i couldn't enable cc auto fill locally, it's tough to test. also seemed this approach isn't very uncommon. 
notes: 
- also reverting the code that we used to log zuora payload
- someone may not ask "why not just autocomplete='off'". most browsers/extensions ignores that now. there is a SO thread about it but i lost …
=> disallow chrome to autofill cc hidden fields, reverts error tracking code

src/actions/support.js, src/actions/tests/__snapshots__/support.test.js.snap, src/actions/tests/support.test.js, src/components/auth/SuspensionAlerts.js, src/components/auth/tests/SuspensionAlerts.test.js, src/components/support/Support.js, src/components/support/tests/Support.test.js, src/components/usageReport/SendMoreCTA.js, src/components/usageReport/tests/SendMoreCTA.test.js, src/helpers/conditions/tests/user.test.js, src/helpers/conditions/user.js, src/pages/profile/ProfilePage.js, src/pages/profile/tests/ProfilePage.test.js, src/pages/profile/tests/__snapshots__/ProfilePage.test.js.snap
_Refer to [FE-97](https://jira.int.messagesystems.com/browse/FE-97)_
The majority of the AC for this ticket was completed in previous tickets.  The only thing completed was a little refactor to create `openSupportTicketForm` action creator and a "Request Account Cancellation" panel on the profile page which will only show for admin users (excludes reporting, heroku, azure, etc.).
=> FE-97: Request to cancel account thru in-app support

package-lock.json, package.json
Merging three Greenkeeper PR's, sass-loader #415, style-loader #425, and url-loader #337.
**sass-loader (6.0.7 ~> 7.0.1)**
The major changes were dropping support for Node v4 and throwing an error if peerDependencies are not met.  The Node support won't affect us because we are all pretty much on latest.  The peerDependencies error is easily testable by running the build locally.
**style-loader (0.20 ~> 0.21)**
Nothing major, a new configuration option was added and handling for empty `url()`.  Both did not affect us.
**url-loader (0.6.2 ~> 1.0.1)**
The major change was dropping support for Node v5 and Webpack v2.  There were some other bug fixes, but they were internal and will not affect us.
**Todo**
=> FE-320: Update webpack loaders

package-lock.json, package.json, public/index.html
- link http://browserl.ist/  in app not loading page. let me know objections
- Added browserslist dep as, otherwise, `npx browserslist` doesn't follow the rule in `package.json`
- explicitly disallowed all IE
we've about 83% coverage now
Notes: 
- Adding `not dead` isn't working during build (version issue, i guess). but > 1% and last 2 versions combination would probably give us something similar. 
- Browserlist repo suggested not to disallow unknown browsers but in our case our query disallowed browsers like baido, opera mobile, qq browsers. 
- There are some notes in ticket.
=> FE-298 make browsers support official 

src/components/support/components/SupportForm.js, src/components/support/components/tests/__snapshots__/SupportForm.test.js.snap, src/components/supportTicketLink/SupportTicketLink.js, src/components/supportTicketLink/tests/SupportTicketLink.test.js, src/components/supportTicketLink/tests/__snapshots__/SupportTicketLink.test.js.snap, src/config/default.js, src/pages/billing/components/Banners.js, src/pages/billing/components/Confirmation.js, src/pages/billing/components/SuspendedForBilling.js, src/pages/billing/components/tests/SuspendedForBilling.test.js, src/pages/billing/components/tests/__snapshots__/Banners.test.js.snap, src/pages/billing/components/tests/__snapshots__/Confirmation.test.js.snap, src/pages/billing/components/tests/__snapshots__/SuspendedForBilling.test.js.snap
The following are the different scenarios that need to be tested.
1. Before downgrading an account that includes a free dedicated IP to a paid account that does not, the user is warned they will have to start paying for the dedicated IP and the user is asked to contact support if they want to remove it.  This mailto:support@sparkpost.com link was changed to a submit a support ticket link that opens the support panel.  To test, sign-in as brian.kemper+fe-93-150k@sparkpost.com, navigate to the plan picker page and change the dropdown to the 50k plan.  
2. When a user is suspended for billing, the billing summary page warns the user and provides instructions to unsuspend their account.  There was a generic contact us if you have any questions and I changed it to this submit a support ticket …
=> FE-93: Remove support@ email address from app and site

src/components/auth/ConditionSwitch.js, src/components/auth/tests/ConditionSwitch.test.js, src/components/support/Support.js, src/components/support/components/NoIssues.js, src/components/support/components/NoIssues.module.scss, src/components/support/components/SearchPanel.js, src/components/support/components/SearchPanel.module.scss, src/components/support/components/SupportForm.js, src/components/support/components/tests/NoIssues.test.js, src/components/support/components/tests/SearchPanel.test.js, src/components/support/components/tests/SupportForm.test.js, src/components/support/components/tests/__snapshots__/NoIssues.test.js.snap, src/components/support/components/tests/__snapshots__/SearchPanel.test.js.snap, src/components/support/components/tests/__snapshots__/SupportForm.test.js.snap, src/components/support/tests/__snapshots__/Support.test.js.snap, src/components/usageReport/SendMoreCTA.js, src/components/usageReport/tests/SendMoreCTA.test.js, src/components/usageReport/tests/__snapshots__/SendMoreCTA.test.js.snap, src/config/supportIssues.js, src/helpers/conditions/tests/user.test.js, src/helpers/conditions/user.js, src/pages/dashboard/DashboardPage.js, src/pages/dashboard/tests/DashboardPage.test.js, src/pages/dashboard/tests/__snapshots__/DashboardPage.test.js.snap, src/selectors/support.js, src/selectors/tests/support.test.js
[Jira ticket](https://jira.int.messagesystems.com/browse/FE-342)
[Issue matrix](https://docs.google.com/spreadsheets/d/1Z8M-gnewvkcemxKOINxlbP3m4jkq7o56ceQ6I32y8f8/edit?usp=sharing)
---
- Adds access conditions to support issue types
- Adds a "no issues" view to the support panel instead of reverting to the algolia search panel
- Showing some sort of message is probably a better experience
Decided to leave the 1-issue case as is (did not replace the Select)
To verify (DM for passwords)
- Free admin-  jon.ambas+free@sparkpost.com
- Free reporting - jon.ambas+freereporting@sparkpost.com
- Paid admin - jon.ambas+paid@sparkpost.com
- Paid reporting - jon.ambas+paidreporting@sparkpost.com
- For suspended cases, use control endpoint
- note: its not possible to test "suspended due to billing …
=> FE-342 Support ticket UI should account for number of available issue types

src/helpers/tests/validation.test.js, src/helpers/validation.js, src/pages/billing/forms/fields/PaymentForm.js, src/pages/billing/forms/fields/tests/PaymentForm.test.js, src/pages/billing/forms/fields/tests/__snapshots__/PaymentForm.test.js.snap
Before, the card had to be entered as `MM / YYYY`. There is a formatter watching the input that reformats as you type, so this is usually not a problem, but when Chrome auto-fill puts data in that field, the formatter doesn't run and it's left as `MM/YYYY` which broke the validation (because it lacked the spacing around the `/`). 
This ticket:
* Allows `MM / YYYY`, `MM/YYYY`, `MM / YY`, and `MM/YY` formats
* Implements a cardExpiry validator that validates the month is a valid month and that the month/year combo is either the current month/year, or in the future
=> FE-355 updated card expiration validation

src/actions/helpers/templates.js, src/actions/helpers/tests/templates.test.js, src/actions/templates.js, src/actions/tests/__snapshots__/templates.test.js.snap
How to test?
1. Create a template with a reply to email.
2. Remove the reply to email
3. Click Save or Publish
=> FE-400: Users cannot remove reply-to email from a template

src/pages/onboarding/ChoosePlan.js, src/selectors/onboarding.js, src/selectors/tests/__snapshots__/onboarding.test.js.snap, src/selectors/tests/onboarding.test.js
Main bug was caused by react-router not initializing `location.state` to an empty object, so if there is no state set, you have to check if the object is there before referencing any variable on the state. 
This PR also moves that mapStateToProps into a selector to test this case and some other logic.
=> FE-409 fixes bug with onboarding location state

src/pages/ipPools/EditPage.js, src/pages/ipPools/ListPage.js, src/pages/ipPools/components/PoolForm.js, src/pages/ipPools/components/tests/PoolForm.test.js, src/pages/ipPools/components/tests/__snapshots__/PoolForm.test.js.snap, src/pages/ipPools/tests/EditPage.test.js, src/pages/ipPools/tests/ListPage.test.js, src/pages/ipPools/tests/__snapshots__/EditPage.test.js.snap, src/pages/ipPools/tests/__snapshots__/ListPage.test.js.snap
- Removed the empty state from the ip pools list page
- Added the `shouldShowIpPurchaseCTA` selector to the form and edit pages, wrapped around the purchase links/copy
- Some clean up
=> FE-429 Remove ip pool empty state & small ui improvements

src/components/support/components/HerokuMessage.js, src/components/support/components/SupportForm.js, src/components/support/components/tests/HerokuMessage.test.js, src/components/support/components/tests/SupportForm.test.js, src/components/support/components/tests/__snapshots__/HerokuMessage.test.js.snap, src/components/support/components/tests/__snapshots__/SupportForm.test.js.snap
Two things:
- Not sure how to test a heroku user locally
- Is this the right url?
=> FE-428 Replace support ticket form with message for heroku users

src/config/default.js, src/pages/join/JoinPage.js, src/pages/join/tests/JoinPage.test.js, src/pages/join/tests/__snapshots__/JoinPage.test.js.snap
**Notes:**
- ~From [this spec](https://github.com/SparkPost/sparkpost-admin-api-documentation/pull/249/files#diff-67ec3e3387465afb64e4f66518e488a6R48) it "appears to be" expecting EVERYTHING in creation_params. Reached out to @James-Burba to clarify and he'll confirm tomorrow.~ Currently, I'm only sending what's not already being sent.
Update: Confirmed that params that aren't already passed otherwise, need to be passed here.
- Remove `sfdcid` from `salesforceDataParams` config, as that we're not actually sending in `salesforce_data`. 
- ~Accusers (master) API doesn't seem to complain about extra param, creation_params. However, I'll test with AC-129 branch tomorrow.~ Done
- Related accusers PR https://github.com/SparkPost/accusers-api/pull/415
**Testing:**
- Visit a signup URL with query …
=> FE-406 - Pass query params in creation_params during signup

.travis.yml, src/actions/sendingDomains.js, src/actions/subaccounts.js, src/actions/tests/__snapshots__/sendingDomains.test.js.snap, src/actions/tests/__snapshots__/subaccounts.test.js.snap, src/actions/tests/sendingDomains.test.js, src/actions/tests/subaccounts.test.js, src/pages/sendingDomains/EditPage.js, src/pages/sendingDomains/tests/EditPage.test.js, src/pages/sendingDomains/tests/__snapshots__/EditPage.test.js.snap, src/pages/subaccounts/DetailsPage.js, src/pages/subaccounts/tests/DetailsPage.test.js, src/pages/subaccounts/tests/__snapshots__/DetailsPage.test.js.snap, src/reducers/sendingDomains.js, src/reducers/subaccounts.js, src/reducers/tests/__snapshots__/sendingDomains.test.js.snap, src/reducers/tests/__snapshots__/subaccounts.test.js.snap, src/reducers/tests/sendingDomains.test.js, src/reducers/tests/subaccounts.test.js
**How to test?**
- For subaccount page, open a link to a subaccount that does not exist (e.g. http://app.sparkpost.test/account/subaccounts/0).  The expected result is to be redirected to the subaccount list page with a warning.
- For sending domain page, open a link to a sending domain that does not exist (e.g. http://app.sparkpost.test/account/sending-domains/edit/0).  The expected result is to be redirected to the sending domains list page with a warning.
=> FE-395:  Handle GET failures correctly in Subaccounts and Sending Domains

.eslintrc, src/components/billing/PlanPrice.js, src/components/billing/tests/__snapshots__/PlanPrice.test.js.snap, src/components/reduxFormWrappers/FileFieldWrapper.js, src/components/reduxFormWrappers/tests/__snapshots__/FileFieldWrapper.test.js.snap, src/components/tags/DomainStatusTag.js, src/components/tags/tests/__snapshots__/DomainStatusTag.test.js.snap, src/pages/sendingDomains/components/SetupSending.js, src/pages/sendingDomains/components/tests/__snapshots__/SetupSending.test.js.snap, src/pages/users/ListPage.js, src/pages/users/tests/__snapshots__/ListPage.test.js.snap
This PR starts to address the [interaction between React and Chrome's page translation feature](https://github.com/facebook/react/issues/11538).
In essence, Chrome replaces text nodes in the DOM with translated equivalents. React expects exclusive access to the DOM so it throws when it next tries to do updates around translated content.
For instance, in the following:
```jsx
<h1>{ showIcon && 'This is bare text' }</h1>
```
If we toggle `showIcon` after Chrome translates the text, React tries to remove a now-nonexistent node.
I added an eslint rule to warn about the most common instance of the issue. It detects a bare string inside JSX with at least 1 sibling. For example:
```jsx
const MyThing = () => <div>This is bare text with this sibling: <Sibling /></div>;
```
This doesn't catch …
=> FE-442: Make Chrome translate users less unhappy

src/config/supportIssues.js
Notes:
- We can't ship this until SC cutover
- As per ticket, we had to remove Technical Support. That will require updating, at least, https://www.sparkpost.com/docs/getting-started/how-to-get-help/. Support docs PR https://github.com/SparkPost/support-docs/pull/261
- I think it's worth renaming this part to something appropriate as that category is gone
> Additional technical support is available on paid plans. Upgrade now.
to like,
> Additional support categories are available on paid plans. Upgrade now.
=> FE-382 - add new support category, remove technical support category

docs/access-control.md, src/actions/accessControl.js, src/actions/tests/accessControl.test.js, src/components/usageReport/SendMoreCTA.js, src/components/usageReport/tests/__snapshots__/SendMoreCTA.test.js.snap, src/config/supportIssues.js, src/helpers/conditions/README.md, src/helpers/conditions/__mocks__/account.js, src/helpers/conditions/account.js, src/helpers/conditions/tests/account.test.js, src/pages/billing/forms/ChangePlanForm.js, src/pages/billing/forms/tests/ChangePlanForm.test.js, src/selectors/__mocks__/accessConditionState.js, src/selectors/accessConditionState.js, src/selectors/accountBillingInfo.js, src/selectors/tests/accessConditionState.test.js, src/selectors/tests/accountBillingInfo.test.js
* updated access control to include plans
* moved around some selectors so that they still work
* added a README to explain a few things about condition helpers
* updated SendMoreCTA so that deprecated plans prompt for upgrade instead of allowing sending limits support request
* updated test
TODO:
=> FE-407 Deprecated plans cannot submit sending limit increase requests

src/actions/abTesting.js, src/actions/tests/__snapshots__/abTesting.test.js.snap, src/components/typeahead/TemplateTypeahead.js, src/components/typeahead/Typeahead.js, src/helpers/templates.js, src/helpers/tests/__snapshots__/templates.test.js.snap, src/helpers/tests/templates.test.js, src/helpers/validation.js, src/pages/abTesting/CreatePage.js, src/pages/abTesting/components/AbTestCreateForm.js, src/pages/abTesting/components/tests/__snapshots__/AbTestCreateForm.test.js.snap, src/pages/abTesting/tests/CreatePage.test.js, src/reducers/abTesting.js, src/reducers/tests/__snapshots__/abTesting.test.js.snap, src/reducers/tests/abTesting.test.js, src/selectors/templates.js, src/selectors/tests/__snapshots__/templates.test.js.snap, src/selectors/tests/templates.test.js
To verify
(1)
- Go to create page
- Select a template that is assigned to master and not shared with all
- Select a subaccount
- Attempt to submit, error should be visible
(2)
- Create a test assigned to master
- The following redirect should not include `?subaccount=0` and subaccount tag should not be visible
(3)
- Cancel a test from the list page
- Status tag should update to 'Cancelled'
- Test with an AB test assigned to a subaccount as well
=> FE-495 Fix AB Testing Defects

src/pages/billing/forms/fields/BillingAddressForm.js, src/pages/billing/forms/fields/BillingContactForm.js, src/pages/billing/forms/fields/tests/BillingAddressForm.test.js, src/pages/billing/forms/fields/tests/BillingContactForm.test.js, src/pages/billing/forms/fields/tests/__snapshots__/BillingAddressForm.test.js.snap, src/pages/billing/forms/fields/tests/__snapshots__/BillingContactForm.test.js.snap, src/selectors/accountBillingForms.js, src/selectors/tests/__snapshots__/accountBillingForms.test.js.snap, src/selectors/tests/accountBillingForms.test.js
To reproduce:
- Open either the change plan page, onboarding plan page, or update payment modal.
- Make sure the billing address field is visible - select a new paid plan, and do not use saved credit card.
- Country initial value error:
- Do no touch fields.
- Attempt to submit to force validation
- Country will show "Required"
- State field is not displayed
- State initial value error:
- Select a country without states (not US or CA)
- Immediately select a country with states (US or CA)
- States field should be visible 
- Attempt to submit to force validation
- State will show "Required"
=> FE-502 Fix billing country and state validation

src/helpers/tests/units.test.js, src/helpers/units.js
To repro log into a high volume account  and look at the summary report over a 6 month window.
Alternatively, hack a report to include a value in the billions.
=> FE-509: Format numbers >= 1 billion with 'B' suffix

public/index.html
Marketing will use the url (like /onboarding) to detect if signup success. i've pointed to possible false positives as we can visit that page at anytime. but seems there can be javascript condition from optimizely. so they'll check `document.referrer` to verify the referrer is `/join`.
we'll have to do a end to end test on staging as optimizely needs to reach our page to run test. @jettpendleton will help us verify on staging before we deploy to prod.
=> Add optimizely

src/pages/billing/components/ManuallyBilledBanner.js, src/pages/billing/components/tests/ManuallyBilledBanner.test.js, src/pages/billing/components/tests/__snapshots__/ManuallyBilledBanner.test.js.snap
When in staging, it was found that we should enforce the existence of `recurring_charge` before allowing a custom plan to enable automatic billing.
=> Fix for AC-287: Custom billing page for customers on annual plans

public/static/tenant-config/production.js, src/actions/auth.js, src/actions/tests/__snapshots__/auth.test.js.snap, src/actions/tests/auth.test.js, src/actions/tests/websiteAuth.test.js, src/actions/websiteAuth.js, src/config/default.js, src/config/test-config.js, src/helpers/authCookie.js, src/helpers/http.js, src/helpers/tests/authCookie.test.js, src/helpers/tests/websiteAuthCookie.test.js, src/helpers/websiteAuthCookie.js, src/pages/join/tests/JoinPage.test.js, src/pages/sendingDomains/components/tests/EditBounce.test.js, src/reducers/index.js, src/reducers/websiteAuth.js
**Testing Locally**
1. Log in
1. Confirm both "auth" and "website_auth" cookies were created with "Application" tab of dev tools
- Note: verify format and token values for each cookie
1. Log out
1. Confirm both "auth" and "website_auth" cookies were deleted with "Application" tab of dev tools
TBD:
=> FE-508: Reinstate website auth cookie

src/pages/reports/engagement/EngagementPage.js, src/pages/reports/engagement/tests/EngagementPage.test.js
`EngagementPage` used a deep comparison of `prevProps` with `this.props` in `cDU` to control its refresh logic:
```js
componentDidUpdate(prevProps) {
if (_.isEqual(prevProps.reportOptions, this.props.reportOptions)) {
this.props.refreshEngagementReport(this.props.reportOptions);
}
}
```
`props.reportOptions` does not spontaneously change after mount so the refresh action is not dispatched until the user changes a report option.
The other report pages use an identity check:
```js
componentDidUpdate(prevProps) {
if (prevProps.reportOptions !== this.props.reportOptions) {
this.props.refreshEngagementReport(this.props.reportOptions);
}
}
```
...which does trigger after mount since the `ReportOptions` child component always dispatches `REFRESH_REPORT_OPTIONS` on mount.
- Visit the engagement …
=> FE-553: report now refreshes after mount

src/helpers/messageEvents.js, src/helpers/tests/__snapshots__/messageEvents.test.js.snap, src/helpers/tests/messageEvents.test.js, src/pages/reports/messageEvents/components/AdvancedFilters.js, src/pages/reports/messageEvents/components/AdvancedFilters.module.scss, src/pages/reports/messageEvents/components/EventTypeFilters.js, src/pages/reports/messageEvents/components/tests/AdvancedFilters.test.js, src/pages/reports/messageEvents/components/tests/EventTypeFilters.test.js, src/pages/reports/messageEvents/components/tests/__snapshots__/AdvancedFilters.test.js.snap, src/pages/reports/messageEvents/components/tests/__snapshots__/EventTypeFilters.test.js.snap, src/selectors/eventListing.js, src/selectors/tests/__snapshots__/eventListing.test.js.snap, src/selectors/tests/eventListing.test.js
Updated msg events report advanced filters to use new `displayName` and `description` fields from the msg events documentation endpoint.
2 design options:
- Reuse existing design. Surface event type descriptions as tooltips. ([video](https://www.useloom.com/share/da1e3c8f4ec04f9d912184abdcb699b0))
- Use webhooks create form style: checkbox+title+description in long form, 2-column layout. ([video](https://www.useloom.com/share/ed8a03c9da6149c180d3ab701536fb41))
=> FE-535: Message events report: event type names and descriptions

src/pages/templates/EditPage.js, src/pages/templates/PublishedPage.js, src/pages/templates/containers/PublishedPage.container.js, src/pages/templates/tests/EditPage.test.js, src/pages/templates/tests/PublishedPage.test.js
Show message when error in loading template
Test:
- In `master`, try visiting a non-existing template edit url. You can change directly in URL. It would redirect to list page without any message. However, doing same in this branch would show a message.
=> FE-560 Show template loading error

src/pages/onboarding/ChoosePlan.js, src/pages/onboarding/tests/__snapshots__/ChoosePlan.test.js.snap
See convo for details: https://msys.slack.com/archives/CDLSCST38/p1540228840000100
Copy: https://docs.google.com/document/d/1fqioihD4JpXHB_zhOe3uYq9tULp_qLPFDUT9OkyJRMQ/edit
Note: I wasn't able to update the subheading under the free plan. We tried to have "15,000 free emails for first 30 days, then 500/month forever" as a subheading. However this would also be shown when downgrading to the 500 free plan on the billing page and would be misleading. We opted to not change the subheading for free plans.
=> AC-357 updates language during onboarding for new free plans

src/helpers/conditions/account.js, src/helpers/conditions/tests/account.test.js, src/pages/billing/SummaryPage.js, src/pages/billing/components/ManuallyBilledBanner.js, src/pages/billing/components/tests/ManuallyBilledBanner.test.js, src/pages/billing/components/tests/__snapshots__/ManuallyBilledBanner.test.js.snap, src/pages/billing/tests/SummaryPage.test.js, src/pages/billing/tests/__snapshots__/SummaryPage.test.js.snap, src/selectors/accountBillingInfo.js, src/selectors/tests/accountBillingInfo.test.js
- Added a condition to detect if the current plan is "in Zuora" aka has `billingId`
- Used the condition show/hide `ManuallyBilledBanner` on `/account/billing`
- Review `/account/billing` while varying the following plan fields:
- custom - boolean - is this a custom plan?
- billingId - string / uuid - Zuora plan ID - exists iff the plan exists in Zuora
=> FE-550: offer auto billing only to folk on zuora plans

package-lock.json, src/pages/users/EditPage.js, src/pages/users/components/RoleRadioGroup.js, src/pages/users/components/tests/__snapshots__/RoleRadioGroup.test.js.snap, src/pages/users/tests/__snapshots__/EditPage.test.js.snap
After doing this I feel like we should show this only when they check it on. so here is my thought:
Status: Unchecked
Action: Check
Note: show the note as in this PR
Status: Checked
Action: Uncheck
Note: <You'll need to reset your password....> Possibly with an action that sends password reset email directly from here rather than visiting the log in page.
=> FE-543 - Add a note about removing password upon enabling single sign on

src/constants/index.js, src/pages/users/EditPage.container.js, src/pages/users/EditPage.js, src/pages/users/components/EditForm.js, src/pages/users/components/tests/EditForm.test.js, src/pages/users/components/tests/__snapshots__/EditForm.test.js.snap, src/pages/users/index.js, src/pages/users/tests/EditPage.test.js, src/pages/users/tests/__snapshots__/EditPage.test.js.snap, src/reducers/tests/__snapshots__/users.test.js.snap, src/reducers/users.js
- `/account/users/edit/:user` now has a secondary action named `Disable Two-Factor Authentication` when `:user` has it enabled.
- Refactored `users.EditPage` into a container, page and form components.
- Updated users reducer to allow updating `tfa_enabled`.
=> AC-401: Allow admin users to disable TFA for a user

src/pages/users/EditPage.js, src/pages/users/tests/EditPage.test.js
`s/() => handleSubmit(...)/handleSubmit(...)/`
There is a separate issue with `PUT /users/:username` where setting `is_sso` doesn't stick. This is unrelated.
- Manage users -> click on a username (not your current login)
- Make a change on the edit form
- Submit
- Verify the `PUT /users/:username` call matches your form content.
=> FE-577: reinstate user edit form submission handler

src/components/billing/PlanPrice.js, src/components/billing/tests/PlanPrice.test.js, src/components/billing/tests/__snapshots__/PlanPrice.test.js.snap, src/components/planPicker/Plan.js, src/components/planPicker/tests/__snapshots__/Plan.test.js.snap, src/pages/billing/components/Confirmation.js, src/pages/billing/components/Confirmation.module.scss, src/pages/billing/components/tests/__snapshots__/Confirmation.test.js.snap
- Plan picker shows new CSM note
- Plan summary test on billing page is now orange
- Use a free or CC-billing account
- Navigate to billing page from account top nav dropdown `/account/billing/plan`
- Select the 5M plan :)
=> AC-402: add CSM plan note to 5M plan

src/actions/auth.js, src/actions/tests/auth.test.js, src/pages/register/RegisterPage.js, src/pages/register/tests/RegisterPage.test.js, src/pages/register/tests/__snapshots__/RegisterPage.test.js.snap
- The `authenticate()` action creator now resolves to an object describing auth and tfa status 
- `RegisterPage` checks `authenticate()` result and redirects to `/auth/enable-tfa` if required
- Minor unrelated test cleanup
- Set `tfa_required` on your test account
- Invite a new user to your test account
- Hint: you can capture the invitation token using Chrome devtools - it's in the response to `POST /users/invite`
- Either click the link in the invitation email or visit `YOUR_HOST/register?token=YOUR_INVITATION_TOKEN`
- Verify that after setting a password, you must enable TFA
=> AC-417: Add enable-tfa page to user registration flow

src/pages/account/AccountSettingsPage.js, src/pages/account/tests/AccountSettingsPage.test.js, src/pages/account/tests/__snapshots__/AccountSettingsPage.test.js.snap, src/pages/profile/components/TfaManager.js, src/pages/profile/components/tests/TfaManager.test.js, src/pages/profile/components/tests/__snapshots__/TfaManager.test.js.snap, src/pages/users/EditPage.container.js, src/pages/users/EditPage.js, src/pages/users/tests/EditPage.test.js
- Removed the `tfaRequired` feature flag check so any admin can make TFA mandatory
- Fixed an issue where you could still disable your own TFA when mandatory
- Fixed an issue where an admin could still disable another user's TFA when mandatory
- Verify an account without `options.ui.tfaRequired` can set TFA to required in `/account/settings`
- Enable mandatory TFA
- Verify users cannot disable their own TFA
- Verify admins cannot disable others' TFA
=> AC-446: mandatory TFA for all

package-lock.json, package.json, src/pages/signals/OverviewPage.js, src/pages/signals/components/viewControls/Calculation.js, src/pages/signals/components/viewControls/ChartType.js, src/pages/signals/components/viewControls/ControlGroup.js, src/pages/signals/components/viewControls/ControlGroup.module.scss, src/pages/signals/components/viewControls/tests/Calculation.test.js, src/pages/signals/components/viewControls/tests/ChartType.test.js, src/pages/signals/components/viewControls/tests/ControlGroup.test.js, src/pages/signals/components/viewControls/tests/__snapshots__/Calculation.test.js.snap, src/pages/signals/components/viewControls/tests/__snapshots__/ChartType.test.js.snap, src/pages/signals/components/viewControls/tests/__snapshots__/ControlGroup.test.js.snap
Adds a control group component, and two wrappers for Chart Type and Calculation:
```js
// Usage
<Calculation initialSelected='absolute' onChange={(selected) => ()} />
<ChartType onChange={(selected) => ()} />
// ControlGroup usage
const Foo = () => (
<ControlGroup 
options={{
foo: 'Friendly Label',
bar: <CustomComponent/>
}}
onChange={(selected) => ()}
initialSelected='foo'
/>
);
```
=> EO-433 Create Presentational Table Control Components

src/config/navItems.js
Added 'NEW' tag to the Events Search link in the left navigation panel under reports.
=> SA-449 Add 'NEW' tag to Events Search

scripts/generateConfigs/tenants/production.js
The [default configuration is to allow default bounce domains for subaccounts](https://github.com/SparkPost/2web2ui/blob/master/scripts/generateConfigs/defaultTemplate.js#L9).
Please note that this can only be verified from a users perspective in production.  To verify locally and in staging, we will check the built configuration for spceu.
=> TR-949: Enable configuration to allow default bounce domains in EU

src/helpers/messageEvents.js, src/helpers/tests/__snapshots__/messageEvents.test.js.snap, src/helpers/tests/messageEvents.test.js
Some query parameters in URLs saved from old message events page do not correspond with the new Events UI. This causes errors in both the customer's expected results as well as placeholder text lookup. 
Fix:
* Translate all old message events query params to the corresponding new events query params.  
* message_ids->messages
* campaign_ids->campaigns
* template_ids->templates
* ab_test_ids->ab_tests
* transmission_ids->transmissions
* friendly_froms -> from_addresses
You can see an example using this link: (https://app.sparkpost.com/reports/message-events?friendly_froms=sender%40ymail.com)
=> SA-453 Filter and transform events query parameters from URL link

src/components/collection/SaveCSVButton.js
`encodeURI` expects an entire URI, which causes Firefox to truncate pound signs (#). Using `encodeURIComponent` encodes the entire string.
=> FE-603: Changed encoding to work on Firefox

src/pages/templates/components/Form.js, src/pages/templates/components/FromEmail.js, src/pages/templates/components/FromEmailInput.js, src/pages/templates/components/containers/Form.container.js, src/pages/templates/components/tests/Form.test.js, src/pages/templates/components/tests/FromEmail.test.js, src/pages/templates/components/tests/__snapshots__/Form.test.js.snap
**What changed?**
- Template form will load immediately (previously, it would show a spinner while loading sending domains which could be 30+ seconds for some of our accounts with a large number of sending domains)
- Let API validate sending domain in the "From Email" field
This is the error that users should receive if they provide an invalid sending domain.
=> TR-938: Do not wait for supporting data to render template form

src/helpers/signals.js, src/helpers/tests/signals.test.js, src/pages/signals/EngagementRecencyPage.js, src/pages/signals/HealthScorePage.js, src/pages/signals/SpamTrapPage.js, src/pages/signals/components/OtherChartsHeader.js, src/pages/signals/components/SignalsPage.js, src/pages/signals/components/tests/OtherChartsHeader.test.js, src/pages/signals/components/tests/SignalsPage.test.js, src/pages/signals/components/tests/__snapshots__/OtherChartsHeader.test.js.snap, src/pages/signals/tests/__snapshots__/SpamTrapPage.test.js.snap
This PR:
- Appends either `subaccount ID` or `master account` to all Signals details page titles when viewing data pertaining to a single subaccount
=> EO-581 Display subaccount when viewing subaccount only data

src/pages/signals/EngagementRecencyPage.js, src/pages/signals/components/charts/barchart/BarChart.js, src/pages/signals/components/charts/barchart/tests/__snapshots__/BarChart.test.js.snap, src/pages/signals/components/charts/divergingBar/tests/__snapshots__/DivergingBar.test.js.snap, src/pages/signals/components/charts/horizontalbar/tests/__snapshots__/HorizontalBar.test.js.snap, src/pages/signals/components/charts/sparkline/tests/__snapshots__/Sparkline.test.js.snap, src/pages/signals/components/charts/tooltip/Tooltip.js, src/pages/signals/components/charts/tooltip/Tooltip.module.scss, src/pages/signals/components/charts/tooltip/TooltipMetric.js, src/pages/signals/components/charts/tooltip/TooltipMetric.module.scss, src/pages/signals/components/charts/tooltip/tests/Tooltip.test.js, src/pages/signals/components/charts/tooltip/tests/TooltipMetric.test.js, src/pages/signals/components/charts/tooltip/tests/__snapshots__/Tooltip.test.js.snap, src/pages/signals/components/charts/tooltip/tests/__snapshots__/TooltipMetric.test.js.snap, src/pages/signals/components/previews/tests/__snapshots__/EngagementRecencyPreview.test.js.snap, src/pages/signals/constants/cohorts.js, src/pages/signals/tests/__snapshots__/EngagementRecencyPage.test.js.snap
This PR:
- Adds in cohort `description`s into the tooltips
- Makes tooltip width configurable
- Moves the `new` cohort to the top of the graph to better illustrate its 'badness'
--- 
Difficult to verify locally / staging. I can provide reviewer with a way to view some data.
=> EO-575 Add Eng Rec tooltip descriptions, Move NEW cohort

.travis.yml, package.json
Coveralls began failing today with [this error](https://github.com/lemurheavy/coveralls-public/issues/1264) in our Travis builds. This PR aims to leave coveralls running but ignore its return value _temporarily_ so we can keep using travis build status in our PRs.
I changed our travis config to make our builds succeed even if the coveralls step fails.
(I took 2 attempts as you'll see from the commit)
Wait for this PR's Travis build to finish :)
=> Ignore coveralls return value in Travis builds

src/pages/signals/EngagementRecencyPage.js, src/pages/signals/HealthScorePage.js, src/pages/signals/SpamTrapPage.js, src/pages/signals/components/ChartHeader.js, src/pages/signals/components/actionContent/EngagementRecencyActions.js, src/pages/signals/components/actionContent/HealthScoreActions.js, src/pages/signals/components/actionContent/SpamTrapActions.js, src/pages/signals/components/tests/ChartHeader.test.js, src/pages/signals/components/tests/__snapshots__/ChartHeader.test.js.snap, src/pages/signals/containers/EngagementRecencyDetailsContainer.js, src/pages/signals/containers/SpamTrapDetailsContainer.js, src/pages/signals/containers/tests/EngagementRecencyDetailsContainer.test.js, src/pages/signals/containers/tests/HealthScoreDetailsContainer.test.js, src/pages/signals/containers/tests/SpamTrapDetailsContainer.test.js, src/pages/signals/containers/tests/__snapshots__/EngagementRecencyDetailsContainer.test.js.snap, src/pages/signals/containers/tests/__snapshots__/HealthScoreDetailsContainer.test.js.snap, src/pages/signals/containers/tests/__snapshots__/SpamTrapDetailsContainer.test.js.snap, src/pages/signals/tests/EngagementRecencyPage.test.js, src/pages/signals/tests/HealthScorePage.test.js, src/pages/signals/tests/SpamTrapPage.test.js, src/pages/signals/tests/__snapshots__/EngagementRecencyPage.test.js.snap, src/pages/signals/tests/__snapshots__/HealthScorePage.test.js.snap, src/pages/signals/tests/__snapshots__/SpamTrapPage.test.js.snap
This PR:
-  Adds day selection into the engagement recency and spam trap details pages. Similar to day selection in health score.
- Displays recommended actions based on the day selected on all details pages
--- 
Difficult to verify locally / staging. I can provide reviewer with a way to view some data.
=> EO-574 Display recommended actions for selected day

package-lock.json, src/constants/index.js, src/pages/users/ListPage.js, src/pages/users/tests/ListPage.test.js, src/pages/users/tests/__snapshots__/ListPage.test.js.snap
**What I did**
- Added a subaccount id column to the users list page
- Added 'subaccount' to search terms
**How to test**
- Create a user with a linked subaccount in Dynamobd
- Load the users list page and verify your user has been picked up
- Verify subaccount search feature, keyword : subaccount
**Todo**
=> AC-573: Add subaccount to users list page

package-lock.json, package.json, src/actions/alerts.js, src/actions/tests/__snapshots__/alerts.test.js.snap, src/actions/tests/alerts.test.js, src/pages/alerts-new/components/AlertCollection.js, src/pages/alerts-new/components/AlertToggle.js, src/pages/alerts-new/components/AlertToggle.module.scss, src/pages/alerts-new/components/tests/AlertToggle.test.js, src/pages/alerts-new/components/tests/__snapshots__/AlertCollection.test.js.snap, src/pages/alerts-new/components/tests/__snapshots__/AlertToggle.test.js.snap, src/pages/alerts-new/containers/ListPage.container.js, src/reducers/alerts.js, src/reducers/tests/__snapshots__/alerts.test.js.snap, src/reducers/tests/alerts.test.js
- Bumped matchbox to 3.3.4 to include new `compact` style `<Toggle/>`
- Adds new AlertToggle component inlined within the alerts table collection
- Component manages `enabled` local state and handles the update request
- A successful delete action from the list page now excludes the row
- Log into `appteam` or enable the `feature-alerts` account UI options
- Go to `/alerts-new` (hidden route)
- Due to EO-604, certain entries may 404 on update or 500 on delete.
- API reference: https://developers.sparkpost.com/api/alerts
- Small visual bug with toggles, `border-radius` should be `50%` not `100%` (might not fix in this ticket)
=> EO-591 - Add Alerts enable/disable action to List Page

package-lock.json, package.json, src/actions/messageEvents.js, src/actions/tests/messageEvents.test.js
- Added `qs` as a dependency.
- Use `qs` in events page
- Add tests for cursor
- Go to Events Search page and navigate through pages.
=> FE-628: Use qs instead of query-string to parse URI

src/__integration__/__snapshots__/billing.test.js.snap, src/__integration__/http-responses/v1/account/billing/get.js, src/__integration__/http-responses/v1/account/get.js, src/actions/account.js, src/actions/billing.js, src/actions/billingCreate.js, src/actions/billingUpdate.js, src/actions/tests/__snapshots__/account.test.js.snap, src/actions/tests/account.test.js, src/actions/tests/billingCreate.test.js, src/actions/tests/billingUpdate.test.js, src/pages/billing/SummaryPage.js, src/pages/billing/forms/ChangePlanForm.js, src/pages/billing/forms/tests/ChangePlanForm.test.js, src/pages/billing/tests/SummaryPage.test.js, src/reducers/account.js, src/reducers/tests/__snapshots__/account.test.js.snap, src/reducers/tests/account.test.js, src/selectors/accountBillingInfo.js
- Removed usage of GET on /account?includes=billing
- Added usage of GET on /account/billing
- Updated tests
- Added mock request for /account/billing
- Open /account/billing page
- Verify that /account request does not contain query for 'includes=billing'
- Verify that a billing request is made
=> AC-590: Changed billingInfo to utilize billing endpoint 

src/pages/recipientLists/helpers/csv.js, src/pages/recipientLists/helpers/tests/csv.test.js
When creating or updating a recipient list, fixed the handling if Papaparse is unable able to read the file provided.  Specifically, `RecipientListForm` expects an array of errors from `parseRecipientListCsv`, but `error` callback was rejecting with an `Error`.  Changed it to return an array with a static message.
1. Navigate to /lists/recipient-lists/create
2. Download the example recipient list
3. Fill out the form, provide a label, identifier, and select example recipient list from your downloads directory
4. Rename the example recipient list file in your downloads directory
5. Click "Create Recipient List" button
You should expect to get a "Unable to read your file" error.
=> TR-1118: Some recipient list upload errors handled incorrectly

src/config/routes.js
The grant: https://github.com/SparkPost/access/blob/master/lib/token-access.js#L519
- Recipient validation top level route now checks for the `recipient_lists/manage` grant
- Log into app as a reporting user
- Recipient Validation should not appear in the nav
=> EO-620 Hide RV if user does not have access grant

src/pages/alerts-new/CreatePage.js, src/pages/alerts-new/EditPage.js, src/pages/alerts-new/components/AlertForm.js, src/pages/alerts-new/components/tests/AlertForm.test.js, src/pages/alerts-new/components/tests/__snapshots__/AlertForm.test.js.snap, src/pages/alerts-new/constants/defaultFormValues.js, src/pages/alerts-new/tests/__snapshots__/EditPage.test.js.snap
EO-616: Alerts UI Product Feedback
AC:
- Enable on Create Form is hidden (automatically enabled)
- Set Default Criteria Comparator to 'lt' (below)
- Show name of alert being edited in page title
=> Alert UI Product Feedback

.storybook/webpack.config.js, package-lock.json, package.json
- The `devDependency` [@storybook/addon-actions](https://github.com/storybooks/storybook) was updated from `4.1.14` to `5.0.1`.
- The `devDependency` [@storybook/react](https://github.com/storybooks/storybook) was updated from `4.1.14` to `5.0.1`.
[Update to these versions instead 🚀](https://github.com/SparkPost/2web2ui/compare/master...SparkPost:greenkeeper%2Fmonorepo.storybook-20190308180234) 
<details>
<summary>Commits</summary>
<p>The new version differs by  commits.</p>
<p>See the <a href="https://urls.greenkeeper.io/storybooks/storybook/compare/ae7a4cf0720cb9d528163f9411ade78aa379708a...ae7a4cf0720cb9d528163f9411ade78aa379708a">full diff</a></p>
</details>
```
$ npm run storybook
```
Open http://localhost:9001 and make sure it renders correctly.
=> Update storybook to the latest version 🚀

src/components/billing/PlanPrice.js, src/components/billing/tests/__snapshots__/PlanPrice.test.js.snap, src/pages/onboarding/ChoosePlan.js, src/pages/onboarding/tests/__snapshots__/ChoosePlan.test.js.snap
Small PR to change the naming used for the free account teir in the ChoosePlan and PlanPrice components. The subtext for free accounts when selecting a plan has been removed. The 
`50,000 emails/month for free` has been replaced with `Test Account`.
=> AC-600 Onboarding copy changes to position as test account

src/components/typeahead/Typeahead.module.scss
- Increases typeahead list z index
- Open alerts create page
- Select day over day, or week over week metric
- Open the subaccount typeahead
- Ensure other elements below do not appear above the typeahead
=> FE-631 Bump typeahead z index

src/config/navItems.js, src/config/routes.js, src/pages/signals/dashboards/EngagementRecencyDashboard.js, src/pages/signals/dashboards/HealthScoreDashboard.js, src/pages/signals/dashboards/SpamTrapDashboard.js, src/pages/signals/dashboards/index.js, src/pages/signals/dashboards/tests/EngagementRecencyDashboard.test.js, src/pages/signals/dashboards/tests/HealthScoreDashboard.test.js, src/pages/signals/dashboards/tests/SpamTrapDashboard.test.js, src/pages/signals/dashboards/tests/__snapshots__/EngagementRecencyDashboard.test.js.snap, src/pages/signals/dashboards/tests/__snapshots__/HealthScoreDashboard.test.js.snap, src/pages/signals/dashboards/tests/__snapshots__/SpamTrapDashboard.test.js.snap, src/pages/signals/index.js
- Creates three new pages, one for each leaderboard
- Nests all new page routes under a new signals nav item
- Verify new routes
- Log into appteam, or add the `feature_signals_v2` UI option to your account
- Verify new nav item renders and each page renders its leaderboard
- Verify current experience is not affected
- Log into an account without the UI option
- Verify the current signals nav item works, and the new nav item does not render
- Verify new routes 404
=> EO-619 Create signals v2 dashboard pages and routes

package-lock.json, package.json, src/helpers/errorTracker.js, src/helpers/tests/__snapshots__/errorTracker.test.js.snap, src/helpers/tests/errorTracker.test.js
To make testing easier, added extra data with each error reported to Sentry.  Bowser was upgraded -- here is the [diff](https://github.com/lancedikson/bowser/compare/943adfb..28bff84) and change log (primarily fixes and documentation).
```
- [FIX] Fix buggy `getFirstMatch` reference
- [ADD] Add detection of PlayStation 4 (#291)
- [ADD] Deploy docs on GH Pages (#293)
- [FIX] Fix files extensions for importing (#294)
- [FIX] Fix docs (#295)
```
Bowser is only used in our `errorTracker`.  It is used to parse the UserAgent, check if browser is on list of supported browsers, and if not supported, may mark errors reported to Sentry as warnings.  To test:
- Login
- Visit http://app.sparkpost.test/webhooks/details/0
- Find error in Sentry and confirm error has correct `isSupportedBrowser` value …
=> Update bowser to the latest version 🚀

src/components/usageReport/UsageReport.js, src/components/usageReport/tests/UsageReport.test.js, src/config/routes.js, src/constants/index.js, src/helpers/conditions/tests/user.test.js, src/helpers/conditions/user.js, src/pages/dashboard/DashboardPage.container.js, src/pages/dashboard/DashboardPage.js, src/pages/dashboard/components/Tutorial.js, src/pages/dashboard/components/tests/Tutorial.test.js, src/pages/dashboard/components/tests/__snapshots__/Tutorial.test.js.snap, src/pages/dashboard/index.js, src/pages/dashboard/tests/DashboardPage.test.js, src/pages/dashboard/tests/__snapshots__/DashboardPage.test.js.snap, src/pages/defaultRedirect/DefaultRedirect.js, src/pages/defaultRedirect/tests/DefaultRedirect.test.js, src/pages/index.js, src/pages/users/ListPage.js
- Dashboard available to other roles (except subaccount roles)
- Checklist hidden from those missing grants instead of whole dashboard
- Route prevents subaccount roles
- Email users directed to dashboard, reporting still directed to summary report
- Dashboard now shows usage from the start
- Login to check where you are directed depending on Role
- Admin, Developer, Email directed to dashboard
- Reporting directed to summary w/ link to dashboard in navbar
- Subaccount reporting directed to summary w/ no link to dashboard
- Admin and developer should have access to checklist on dashboard
=> AC-652: Dashboard Role Changes

src/components/actionPopover/ActionPopover.js, src/components/actionPopover/tests/__snapshots__/ActionPopover.test.js.snap, src/pages/snippets/ListPage.container.js, src/pages/snippets/ListPage.js, src/pages/snippets/components/SnippetCollection.js, src/pages/snippets/components/tests/SnippetCollection.test.js, src/pages/snippets/tests/ListPage.test.js, src/pages/snippets/tests/__snapshots__/ListPage.test.js.snap, src/pages/templates/ListPage.js, src/pages/templates/containers/ListPage.container.js, src/pages/templates/tests/ListPage.test.js, src/pages/templates/tests/__snapshots__/ListPage.test.js.snap
- Hid subaccount columns for any with subaccount_reporting access level
- Hid in templates list page
-  Hid in snippets list page
- Right aligned icon in ActionPopover to be consistent with other lists
- ActionPopover used in users list and snippets list
- Check that subaccounts columns show up in list for non subaccount users
- Check that the column gone if user is a subaccount reporting user
=> AC-647: Removed subaccount columns for subaccount users

src/components/contentEditor/ContentEditor.js, src/components/contentEditor/ContentEditor.test.js, src/components/contentEditor/__snapshots__/ContentEditor.test.js.snap, src/pages/snippets/CreatePage.container.js, src/pages/snippets/CreatePage.js, src/pages/snippets/EditPage.container.js, src/pages/snippets/EditPage.js, src/pages/snippets/tests/CreatePage.test.js, src/pages/snippets/tests/EditPage.test.js, src/pages/templates/CreatePage.js, src/pages/templates/EditPage.js, src/pages/templates/PreviewPage.js, src/pages/templates/PublishedPage.js, src/pages/templates/components/PreviewPanel.js, src/pages/templates/components/tests/PreviewPanel.test.js, src/pages/templates/components/tests/__snapshots__/PreviewPanel.test.js.snap, src/pages/templates/containers/CreatePage.container.js, src/pages/templates/containers/EditPage.container.js, src/pages/templates/containers/PreviewDraftPage.container.js, src/pages/templates/containers/PreviewPublishedPage.container.js, src/pages/templates/containers/PublishedPage.container.js, src/pages/templates/tests/PreviewPage.test.js, src/pages/templates/tests/PublishedPage.test.js, src/pages/templates/tests/__snapshots__/PreviewPage.test.js.snap, src/pages/templates/tests/__snapshots__/PublishedPage.test.js.snap
_Refer to [TR-1124](https://jira.int.messagesystems.com/browse/TR-1124) for more details._
- Removed "amp_html" feature toggles for snippets and templates
- Confirm with any account a user can perform management tasks for templates and snippets (e.g. create, edit, clone, etc.)
- Confirm content validation works for both templates and snippet
- Confirm there is no "AMP HTML" preview tab
- [ x ] ~Confirm AMP preview works with amp specific tags, specifically scripts~ (removed tab for now, will implement with follow-up ticket)
- [ x ] Provide info above for "What Changed" and "How to Test"
=> TR-1124: Launch AMP for all in UI

src/pages/signals/HealthScorePage.js, src/pages/signals/tests/HealthScorePage.test.js, src/pages/signals/tests/__snapshots__/HealthScorePage.test.js.snap
- Tooltip label for the third bar chart in the health score details page now references its friendly label.
- [Point your local upstreams to staging](https://confluence.int.messagesystems.com/display/ENG/Configuring+Openresty+Upstreams).
- Go to a health score details page
- Select one of the engagement weights on the right
- Hover over the third bar chart
=> EO-646 Fix Health score component tooltip labels

src/pages/alerts-new/components/AlertForm.js, src/pages/alerts-new/components/tests/AlertForm.test.js, src/pages/alerts-new/components/tests/__snapshots__/AlertForm.test.js.snap
- Removes the sending domain typeahead from the alerts form
- Adds a domain validator to the facet_value field
- Add the `feature_alerts` UI option to your account, or log into appteam
- Go to `/alerts-new/create`, or an alerts edit page
- Select a health score metric, and set facet name to 'Sending Domain'
=> EO-650 Remove sending domain typeahead

src/pages/ipPools/CreatePage.js, src/pages/ipPools/tests/CreatePage.test.js, src/pages/ipPools/tests/EditIpPage.test.js, src/pages/ipPools/tests/__snapshots__/CreatePage.test.js.snap
Fix following issue:
If you directly visit create pool page, it doesn't populate overflow pools
Solutions:
Because it doesn't list pools on create page upon refresh. 
**How to test**
- Go to create pool page
- Refresh page
- Overflow pools list is populate
=> load pools data on creation on refresh

src/pages/webhooks/components/EditTab.js, src/pages/webhooks/components/Fields.js, src/pages/webhooks/components/SubaccountSection.js, src/pages/webhooks/components/WebhookForm.js, src/pages/webhooks/components/tests/Fields.test.js, src/pages/webhooks/components/tests/SubaccountSection.test.js, src/pages/webhooks/components/tests/WebhookForm.test.js, src/pages/webhooks/components/tests/__snapshots__/EditTab.test.js.snap, src/pages/webhooks/components/tests/__snapshots__/Fields.test.js.snap, src/pages/webhooks/components/tests/__snapshots__/SubaccountSection.test.js.snap, src/pages/webhooks/components/tests/__snapshots__/WebhookForm.test.js.snap
- Moved variables derived from redux form props out of `mapStateToProps` and into the render function.
- Added tests
- Changed `EditTab` to explicitly pass the newWebhook prop as false to `WebhookForm`. 
- Navigate to webhooks page. Try to create a new webhook. When you click the `create webhook` button, it should start submitting. The button should now be disabled and say `Submiting`. The button should also be disabled when no changes have occurred. 
- Do the same with updating page.
=> FE-640 Fix Webhooks form submitting state

scripts/generateConfigs/tenants/production.js, scripts/generateConfigs/tests/__snapshots__/index.func.test.js.snap, src/config/default.js, src/config/env/dev-config.js
SD-732: Enable IP Pool DKIM signing domain UI by default for all tenants except amex
Amex was migrated and no longer needs to avoid this restriction, so it can be true for amex. Creditag has not yet migrated and this option must be false for them.
=> SD-732 default allow_default_signing_domains_for_ip_pools to true

src/actions/signals.js, src/actions/tests/__snapshots__/signals.test.js.snap, src/actions/tests/signals.test.js, src/pages/signals/dashboards/HealthScoreDashboard.js, src/pages/signals/dashboards/components/CurrentHealthGauge/CurrentHealthGauge.js, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/CurrentHealthGauge.test.js, src/pages/signals/dashboards/components/HealthScoreChart/HealthScoreChart.js, src/pages/signals/dashboards/components/HealthScoreChart/tests/HealthScoreChart.test.js, src/pages/signals/dashboards/components/HealthScoreChart/tests/__snapshots__/HealthScoreChart.test.js.snap, src/pages/signals/dashboards/tests/HealthScoreDashboard.test.js, src/reducers/signals.js, src/reducers/tests/__snapshots__/signals.test.js.snap, src/selectors/signals.js, src/selectors/tests/__snapshots__/signals.test.js.snap, src/selectors/tests/signals.test.js
- Created a new health score action for the dashboard that always gets the account aggregated current score (`-1`)
- [Point your local upstreams to staging](https://confluence.int.messagesystems.com/display/ENG/Configuring+Openresty+Upstreams)
- Data available in account 108 (spc)
- Log into appteam or enable the `feature_signals_v2` UI option
- Navigate to the new Health Score page from the main side nav
- Verify the top two panels contain valid data when changing the filters:
- Date ranges (should update)
- Facet filters (should not update)
- Subaccount (should not update)
=> EO-661 Fix current health score dashboard

src/pages/signals/components/HealthScoreOverview.js, src/pages/signals/components/tests/HealthScoreOverview.test.js
- Filters out subaccount id `-1` from the health score summary table
- [Point your local upstreams to staging](https://confluence.int.messagesystems.com/display/ENG/Configuring+Openresty+Upstreams)
- Log into appteam
- Verify "master and all subaccounts" does not appear in table
- Verify pagination still works (if possible)
Before:
=> EO-669 Filter out master and all subaccounts row

src/config/env/index.js, src/config/tests/env.test.js
Needed to set a default environment for enterprise tenants.
=> Follow-up for FE-635: Set runtime environment correctly for enterprise tenants

src/pages/signals/ComplaintsByCohortPage.js, src/pages/signals/EngagementRateByCohortPage.js, src/pages/signals/SpamTrapPage.js, src/pages/signals/UnsubscribeRateByCohortPage.js, src/pages/signals/components/charts/barchart/BarChart.scss, src/pages/signals/components/previews/HealthScorePreview.js, src/pages/signals/components/previews/SpamTrapsPreview.js, src/pages/signals/components/previews/tests/HealthScorePreview.test.js, src/pages/signals/components/previews/tests/SpamTrapsPreview.test.js, src/pages/signals/components/previews/tests/__snapshots__/HealthScorePreview.test.js.snap, src/pages/signals/components/previews/tests/__snapshots__/SpamTrapsPreview.test.js.snap, src/pages/signals/tests/EngagementRateByCohortPage.test.js, src/pages/signals/tests/UnsubscribeRateByCohortPage.test.js, src/pages/signals/tests/__snapshots__/EngagementRateByCohortPage.test.js.snap, src/pages/signals/tests/__snapshots__/UnsubscribeRateByCohortPage.test.js.snap
- New engagement charts
- Default Y domain is now [0, 1] for all charts with percent values. Recharts defaults to  [0, 4] with zero values.
- Spam Trap Preview
- Y domain ticks should match the default calculation (ratio%) on the details page.
- Health Score Preview
- Remove % from the Y tick formatters
- [Point your local upstreams to staging](https://confluence.int.messagesystems.com/display/ENG/Configuring+Openresty+Upstreams)
- appteam account has 0 values to test the default y domain cases
- Visit the new engagement charts
- Check spam trap preview
- Check health score preview
Default Y domain on engagement charts:
Previews:
=> EO-663 More signals design feedback

src/pages/sendingDomains/components/BounceSetupInstructionPanel.js, src/pages/sendingDomains/components/tests/BounceSetupInstructionPanel.test.js
Refer to ESCSP-2939 or TR-1238 for more information.
When creating the verify domain action, need to use the correct variable, `subbacount_id`.
- Create a bounce domain and assign it to a subaccount
- Setup the DNS
- Click verify CNAME or MX record (if BYOIP customer)
=> TR-1238: Fix bounce domain verification to pass subaccount id correctly

src/pages/signals/dashboards/HealthScoreDashboard.js, src/pages/signals/dashboards/tests/HealthScoreDashboard.test.js
Health score dashboard now requests data in ascending SID order, with a limit of 1. This is done to make sure the account rollup (sid -1) is always returned.
- This bug is not obvious in appteam or 108, but was found on an enterprise tenant
- Visit the V2 health score dashboard
- Inspect the request to make sure -1 is returned
=> EO-691 Guarantee -1 is returned to health dashboard

src/pages/signals/ComplaintsByCohortPage.js, src/pages/signals/UnsubscribeRateByCohortPage.js, src/pages/signals/tests/ComplaintsByCohortPage.test.js, src/pages/signals/tests/UnsubscribeRateByCohortPage.test.js, src/pages/signals/tests/__snapshots__/ComplaintsByCohortPage.test.js.snap, src/pages/signals/tests/__snapshots__/UnsubscribeRateByCohortPage.test.js.snap
- Increases Y axis tick and tooltip metric precision to 3 decimals
Example of current behavior:
- Visit v2 engagement details pages
=> EO-687 Increase precision on eng cohort charts

src/actions/metrics.js, src/actions/reportOptions.js, src/actions/tests/__snapshots__/metrics.test.js.snap, src/actions/tests/metrics.test.js, src/actions/tests/reportOptions.test.js, src/reducers/metrics.js, src/selectors/reportFilterTypeaheadCache.js, src/selectors/tests/reportFilterTypeaheadCache.test.js
The summary report typeahead no longer uses the `/templates` endpoint but the `/metrics/templates` endpoint. 
- Search for a template in the summary page typeahead. The template should appear in the typeahead dropdown
-  Can also test that accounts with >50k templates have all of them available.
=> SA-560 Changed summary report typeahead to use metrics template endpoint

src/hooks/useTabs.js, src/hooks/useTabs.test.js, src/pages/templates/PreviewPage.js, src/pages/templates/components/PreviewFrame.js, src/pages/templates/components/PreviewPanel.js, src/pages/templates/components/tests/PreviewFrame.test.js, src/pages/templates/components/tests/PreviewPanel.test.js, src/pages/templates/components/tests/__snapshots__/PreviewFrame.test.js.snap, src/pages/templates/components/tests/__snapshots__/PreviewPanel.test.js.snap, src/pages/templates/tests/PreviewPage.test.js, src/pages/templates/tests/__snapshots__/PreviewPage.test.js.snap
Refer to [TR-1206](https://jira.int.messagesystems.com/browse/TR-1206) for more info.
- Users can now preview their AMP content
- Create a new template with AMP HTML content — an example is provided below
- Click "Save as Draft"
- Click "Preview & Send"
- Select the new "AMP HTML" tab
```html
<!doctype html>
<html ⚡4email>
<head>
<meta charset="utf-8">
<script async src="https://cdn.ampproject.org/v0.js"></script>
<script async custom-element="amp-anim" src="https://cdn.ampproject.org/v0/amp-anim-0.1.js"></script>
<style amp4email-boilerplate>body{visibility:hidden}</style>
</head>
<body>
<h1>AMP'd</h1>
<div>
<amp-anim 
width="500"
height="189"
src="https://media.giphy.com/media/nem4a3nunlA4M/giphy.gif"
alt="an animation"
/>
</div>
</body>
</html>
```
=> TR-1206: AMP previewer for stored templates

src/pages/snippets/ListPage.js, src/pages/snippets/tests/ListPage.test.js, src/pages/templates/ListPage.js, src/pages/templates/components/ListComponents.js, src/pages/templates/components/ListComponents.module.scss, src/pages/templates/components/tests/ListComponents.test.js, src/pages/templates/components/tests/__snapshots__/ListComponents.test.js.snap, src/pages/templates/containers/ListPage.container.js, src/pages/templates/tests/ListPage.test.js, src/pages/templates/tests/__snapshots__/ListPage.test.js.snap
Refer to [TR-1203](https://jira.int.messagesystems.com/browse/TR-1203) for more information.
- Template list page is initially sorted by last updated column descending
- Slightly modify published tag style — moved bullet to lead and italicized
- Removed static widths on metadata field columns to allow name column to grow
- Bonus: fixed both template and snippet list pages to show error banner if load error occurs
- Navigate to templates list page and observe list is sorted by last updated column and the metadata columns are fixed widths to allow room for long template names
- Find a appteam template that is in published, but has draft changes
- Block /templates request in devtools network tab, then reload the page, the error banner should be displayed
=> TR-1203: Template List Page UX Fix of Whitespace

src/constants/index.js, src/pages/ipPools/components/IpForm.js, src/pages/ipPools/components/PoolForm.js, src/pages/ipPools/components/tests/IpForm.test.js, src/pages/ipPools/components/tests/PoolForm.test.js, src/pages/ipPools/components/tests/__snapshots__/IpForm.test.js.snap, src/pages/ipPools/components/tests/__snapshots__/PoolForm.test.js.snap
Refer to [SD-904](https://jira.int.messagesystems.com/browse/SD-904) for AC.
- Removed "ip_auto_warmup" feature flag on IP Pools form and IP form
- Updated "What is Auto Warmup?" link url
- Open IP pools list page
- Open IP pools edit page for an IP pool with at least one IP
- Open IP edit page
- Click "What is Auto Warmup?" link
=> SD-904: Redirect Knowledge Base Article

src/pages/templates/EditPage.js, src/pages/templates/tests/EditPage.test.js, src/pages/templates/tests/__snapshots__/EditPage.test.js.snap
Refer to [TR-1205](https://jira.int.messagesystems.com/browse/TR-1205) for AC.
- After saving a template draft, we were refetching the template.  I believe this was a safeguard, but it was causing a full page reload which would cause the user to lose focus on the current content tab and their place in the content editor.  The fix is to not refetch after save.
- Bonus: Disabled delete and duplicate secondary actions when saving.
1. Open a draft template
2. Switch to "Text" or "AMP HTML" tab 
3. Click "Save as Draft" button
Expected Result: The primary and secondary should all disable temporarily while saving and user should not lose the focus on content tab.
=> TR-1205: Do not lose focus on content tab after save

src/pages/signals/EngagementRateByCohortPage.js, src/pages/signals/tests/EngagementRateByCohortPage.test.js, src/pages/signals/tests/__snapshots__/EngagementRateByCohortPage.test.js.snap
- Fixes a bug that rounded out tooltip metric values
- Y axis now also matches precision
- Go to the engagement rate by cohort details page
- Verify tooltip values round to the nearest tenth
=> EO-722 Fix engagement by cohort precision

src/pages/signals/EngagementRecencyPage.js, src/pages/signals/components/ChartHeader.js, src/pages/signals/components/ChartHeader.module.scss, src/pages/signals/components/InfoTooltip.js, src/pages/signals/components/InfoTooltip.module.scss, src/pages/signals/components/tests/InfoTooltip.test.js, src/pages/signals/components/tests/__snapshots__/ChartHeader.test.js.snap, src/pages/signals/components/tests/__snapshots__/InfoTooltip.test.js.snap, src/pages/signals/dashboards/EngagementRecencyDashboard.js, src/pages/signals/dashboards/HealthScoreDashboard.js, src/pages/signals/dashboards/SpamTrapDashboard.js, src/pages/signals/dashboards/components/CurrentHealthGauge/CurrentHealthGauge.js, src/pages/signals/dashboards/components/CurrentHealthGauge/CurrentHealthGauge.module.scss, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/__snapshots__/CurrentHealthGauge.test.js.snap, src/pages/signals/dashboards/tests/__snapshots__/EngagementRecencyDashboard.test.js.snap, src/pages/signals/dashboards/tests/__snapshots__/HealthScoreDashboard.test.js.snap, src/pages/signals/dashboards/tests/__snapshots__/SpamTrapDashboard.test.js.snap, src/pages/signals/tests/__snapshots__/EngagementRecencyPage.test.js.snap
- Abstracts the blue tooltips in Signals
- Adds tooltips to v2 dashboards and engagement recency page
- Visit v2 dashboards, and the v1 engagement recency details page
- Verify tooltips appear in the page title
- Verify other tooltips are still there (preview components, v1 overview)
=> EO-697 Abstract informational tooltips & Add to V2 pages

src/pages/signals/containers/tests/__snapshots__/withDetails.test.js.snap, src/pages/signals/containers/tests/withDetails.test.js, src/pages/signals/containers/withDetails.js, src/selectors/signals.js, src/selectors/tests/signals.test.js
- Engagement cohort behavioral charts no longer display **empty** data between now and 3 days ago
- This PR only adjust what is displayed in the charts, and does not modify the requests or DateFilter
- This PR does not shift `from`, only `to`
- DateFilter does not represent its displayed dates. It is agnostic of its page/location, and we would need to consider some UX to make that change.
- navigation between charts with custom dates (would need to store the displayed and intended dates separately in redux, and switch between those depending on location)
- disabling last 3 days in datepicker depending on location
- adjusting both `from` and `to` when selecting custom dates feels like a bad interaction to me
- [Point your local upstreams to staging or …
=> EO-689 Shift behavior by cohorts to display data from 3 days ago 

src/actions/signals.js, src/actions/tests/__snapshots__/signals.test.js.snap, src/actions/tests/signals.test.js
- In the health score dashboard, sorting by subaccount with a facet selected now works correctly
- Visit overview page and v2 dashboards
- Verify sorting works with and without a facet
=> EO-738 Fix health score subaccount sorting behavior

src/helpers/axiosInterceptors.js, src/helpers/tests/axiosInterceptors.test.js
Checks if `response` is truthy before accessing property
- Go to a webhook 
- Open chrome's network panel
- Check `Offline`
- click `Send Test Batch` (or `Re-send batch`)
it should show Network error instead of `Cannot read property 'status' of undefined`
=> FE-675 handle case when response is undefined

src/reducers/signalOptions.js, src/reducers/tests/__snapshots__/signalOptions.test.js.snap
- Changes default date filter  range to 30 days
- Go to any signals page
- Verify date filter defaults to 30 days
=> EO-760 Default signal option dates to 30 days

src/pages/signals/HealthScorePage.js, src/pages/signals/tests/HealthScorePage.test.js
Refer to ticket EO-763 for why the injections chart is hidden.
- Hides the injections chart when faceted by mailbox provider
- Go to health score dashboard, and select mailbox provider as a facet
- Click on a mailbox provider to go to the details page (second column)
- Verify injections chart does not display
- The request to spam hits still runs, and fails. There's no easy way to conditionally make this call without refactor.
=> EO-763 Hide injections chart when faceted by mb provider

src/components/collection/Collection.js, src/components/collection/Collection.propTypes.js, src/components/collection/tests/Collection.test.js, src/pages/recipientLists/CreatePage.js, src/pages/recipientLists/EditPage.js, src/pages/recipientLists/components/Form.module.scss, src/pages/recipientLists/components/RecipientListForm.js, src/pages/recipientLists/components/RecipientsCollection.js, src/pages/recipientLists/components/tests/RecipientListForm.test.js, src/pages/recipientLists/components/tests/RecipientsCollection.test.js, src/pages/recipientLists/components/tests/__snapshots__/RecipientListForm.test.js.snap, src/pages/recipientLists/components/tests/__snapshots__/RecipientsCollection.test.js.snap, src/pages/recipientLists/tests/CreatePage.test.js, src/pages/recipientLists/tests/EditPage.test.js, src/pages/recipientLists/tests/__snapshots__/CreatePage.test.js.snap, src/pages/recipientLists/tests/__snapshots__/EditPage.test.js.snap
- Moved redux form decoration to Create/Edit page (parent component) so after upload recipients can be managed from parent component
- Update create page according to mock
- Update edit page briefly (more to do on relevant ticket)
- Unlike past, CSV will be uploaded as soon as file is selected
- Create a new recipient list with upload
-- Upon upload you should see the recipients preview below
- Edit list should work as usual 
There are some improvements needed on Edit page, which i'll do in the relevant ticket that's coming next.
=> TR-1208 Create Recipients List

src/pages/users/components/RoleRadioGroup.js, src/pages/users/components/tests/RoleRadioGroup.test.js, src/pages/users/components/tests/__snapshots__/RoleRadioGroup.test.js.snap
- Released new user roles
- Removed ui feature flag `developer_and_email_roles`
- Check that with an account (w/o ui feature flag), users can be invited w/ new role `Developer` or `Templates`
- Check that existing user roles can be modified between roles
=> AC-660: Release new user roles

package-lock.json, package.json
- Bumps matchbox (https://github.com/SparkPost/matchbox/releases/tag/%40sparkpost%2Fmatchbox%403.3.12)
- Radio buttons now use SVGs
- Verify Radio inputs work in various forms (interactions shouldnt change, but rendering should be fixed)
=> FE-633 Bumps matchbox to 3.3.12 for Radio update

src/pages/templates/EditAndPreviewPage.js, src/pages/templates/components/EditSection.js, src/pages/templates/components/Editor.js, src/pages/templates/components/PreviewErrorFrame.js, src/pages/templates/components/PreviewErrorFrame.module.scss, src/pages/templates/components/PreviewFrame.js, src/pages/templates/components/PreviewSection.js, src/pages/templates/components/PreviewSection.module.scss, src/pages/templates/components/tests/EditSection.test.js, src/pages/templates/components/tests/PreviewErrorFrame.test.js, src/pages/templates/components/tests/PreviewFrame.test.js, src/pages/templates/components/tests/PreviewSection.test.js, src/pages/templates/components/tests/__snapshots__/Editor.test.js.snap, src/pages/templates/components/tests/__snapshots__/PreviewErrorFrame.test.js.snap, src/pages/templates/components/tests/__snapshots__/PreviewSection.test.js.snap, src/pages/templates/containers/EditAndPreviewPage.container.js, src/pages/templates/context/EditorContext.js, src/pages/templates/context/tests/EditorContext.test.js, src/pages/templates/context/tests/__snapshots__/EditorContext.test.js.snap, src/pages/templates/hooks/tests/useEditorContent.test.js, src/pages/templates/hooks/tests/useEditorPreview.test.js, src/pages/templates/hooks/useEditorContent.js, src/pages/templates/hooks/useEditorPreview.js, src/pages/templates/tests/__snapshots__/EditAndPreviewPage.test.js.snap, src/reducers/templates.js, src/reducers/tests/__snapshots__/templates.test.js.snap, src/reducers/tests/templates.test.js, src/selectors/templates.js, src/selectors/tests/__snapshots__/templates.test.js.snap, src/selectors/tests/templates.test.js
Refer to subtask [TR-1285](https://jira.int.messagesystems.com/browse/TR-1285).
- The preview automatically updates when content on left is modified.
- Display an error with some guidance if there is a preview error.
*** I was going to surface line errors in the editors margin as annotations, but found that our API only returns the first error.
1. Modify some content in next editor — should update content in preview
1. Update content with `{{ break; }}` — should present full panel error message
=> TR-1285: Live previewing for prototype fullscreen code editor

src/pages/templates/components/PreviewHeader.js, src/pages/templates/components/PreviewHeader.module.scss, src/pages/templates/components/PreviewSection.js, src/pages/templates/components/tests/PreviewHeader.test.js, src/pages/templates/components/tests/__snapshots__/PreviewHeader.test.js.snap, src/pages/templates/components/tests/__snapshots__/PreviewSection.test.js.snap
This is a subtask [TR-1452](https://jira.int.messagesystems.com/browse/TR-1452).
- Preview subject and from address in desktop preview
- Preview subject and from address in mobile preview
- Confirm subject renders
- Confirm long a from address truncates
=> TR-1452: Preview subject and from for prototype fullscreen code editor

src/pages/templatesV2/EditAndPreview.module.scss, src/pages/templatesV2/EditAndPreviewPage.js, src/pages/templatesV2/tests/__snapshots__/EditAndPreviewPage.test.js.snap
Secondary panel in the top nav is made fixed so it's not lost in scroll as this section will contain crucial actions for the page. Please see the ticket if it's not clear which panel is being referred. 
- Campaigns -> Templates -> Open a template
- Scroll and you should see the section with items like `Content`, `Settings` is fixed.
=> TR-1470 - Makes the second top panel fixed 

src/actions/alertsV1.js, src/actions/tests/__snapshots__/alertsV1.test.js.snap, src/actions/tests/alertsV1.test.js, src/pages/alerts/ListPageNew.js, src/pages/alerts/components/AlertCollectionNew.js, src/pages/alerts/components/AlertToggleNew.js, src/pages/alerts/components/tests/AlertCollectionNew.test.js, src/pages/alerts/components/tests/AlertToggleNew.test.js, src/pages/alerts/components/tests/__snapshots__/AlertCollectionNew.test.js.snap, src/pages/alerts/components/tests/__snapshots__/AlertToggleNew.test.js.snap, src/pages/alerts/constants/metricsV1.js, src/pages/alerts/containers/ListPage.container.js, src/pages/alerts/containers/ListPageNew.container.js, src/pages/alerts/tests/ListPageNew.test.js, src/pages/alerts/tests/__snapshots__/ListPageNew.test.js.snap, src/pages/reports/messageEvents/MessageEventsPage.js, src/pages/reports/messageEvents/components/TableElements.js, src/reducers/alertsV1.js, src/reducers/index.js, src/selectors/alertsV1.js, src/selectors/tests/alertsV1.test.js
- Created action/reducer/selector for alerts v1.
- Added a formatted date and sort key in the selector to modify the list of alerts. 
- Changed response params from labs/alerts -> v1.  EX:  'alert_metric'->'metric', 'enabled'->'muted'
- Sorted by last trigger by using a sort key. Also added logic to only show last 4 triggered alerts in the cards panel.
- Enable user account option `alerts`. This is already enabled in appteam staging.
- See [here](https://github.com/SparkPost/2web2ui/blob/master/docs/feature-flags.md) to enable user options. Alternatively, [point your local upstreams to staging](https://confluence.int.messagesystems.com/display/ENG/Configuring+Openresty+Upstreams) and login to our appteam, CID 107 account
- Edit your openresty configs to contain 
```
location …
```
=> EO-801 Switch over to Alerts v1 API for Alerts List page

src/actions/auth.js, src/actions/tests/__snapshots__/auth.test.js.snap, src/actions/tests/auth.test.js
- Access and Refresh tokens are invalidated when the user clicks the logout button
- Login on the development webpage
- Gather access/refresh key from DynamoDB
- Logout
- Confirm the keys are removed from Dynamo and can't be used to access api/v1/account
=> AC-746 : Logout invalidates both access and refresh token

src/pages/alerts/components/tests/__snapshots__/AlertFormNew.test.js.snap, src/pages/alerts/constants/formConstants.js, src/pages/alerts/helpers/alertForm.js, src/pages/alerts/helpers/tests/alertForm.test.js
Added Soft and hard bounce rate as a selectable metric. 
- Added hard and soft bounces to to constants file and added them  
- Enable user account option `alerts`. This is already enabled in appteam staging.
- See [here](https://github.com/SparkPost/2web2ui/blob/master/docs/feature-flags.md) to enable user options. Alternatively, [point your local upstreams to staging](https://confluence.int.messagesystems.com/display/ENG/Configuring+Openresty+Upstreams) and login to our appteam, CID 107 account
- Edit your openresty configs to contain 
```
location /api/v1/alerts {
proxy_pass http://sp-alerts-api;
include cors;
}
```
under `server:80`,   `location /api/v1`
- Create an alert. Verify that soft and hard bounces are options in the alert metric dropdown.
- Also verify that the evaluator has …
=> EO-893 - Add soft and hard bounce metrics as options

src/selectors/customReports.js, src/selectors/tests/__snapshots__/customReports.test.js.snap, src/selectors/tests/customReports.test.js
- Fixes the custom reports selector to default to `false`
- Custom Reports UI should no longer render without the flag
- Log into an account without  the `feature_reports_enhancements` user flag – check summary report
=> SA-852 Custom reports access check defaults to false

package-lock.json, package.json
Resolves issue with `package.json` `"engines"`.
- Replaced engine config referencing NPM with node.
- Verify that running `npm install` does not work with a Node version < 10.8
- Verify that it works with 10.8 or higher
=> Resolve engines field problem by replacing 'npm' with 'node'

src/helpers/messageEvents.js, src/helpers/metrics.js, src/helpers/signals.js, src/helpers/tests/metrics.test.js, src/reducers/messageEvents.js, src/reducers/suppressions.js
Fix datepicker from https://github.com/SparkPost/2web2ui/pull/1174. 
Prevent to date from being set into the future by not rounding the to if it's already set to now.
Also disable rounding in suppressions and events.
=> SA-603 Datepicker Day Precision fix

package-lock.json, package.json, src/components/reduxFormWrappers/tests/__snapshots__/ComboBoxTypeaheadWrapper.test.js.snap, src/components/typeahead/ComboBoxTypeahead.js, src/components/typeahead/tests/ComboBoxTypeahead.test.js, src/pages/alerts/components/fields/SubaccountsField.js, src/pages/alerts/components/fields/tests/SubaccountsField.test.js, src/pages/alerts/components/fields/tests/__snapshots__/SubaccountsField.test.js.snap
Refer to [SE-260](https://jira.int.messagesystems.com/browse/SE-260)
- Combo box typeahead should only render a max of 100 options
- Combo box menu should remain open after a selection
- Open /alerts/create page using an account with thousands of subaccounts (e.g. brian.kemper+se-260@sparkpost.com)
- Select "Health Score" from "Alert Metric" dropdown
_This is the point when your browser would freeze because all the subaccounts were being written to DOM for the combo box menu.  Now, it should not freeze and allow you to continue with creation of an alert._
=> SE-260: Alert create page freezes for certain enterprise customers

src/actions/signals.js, src/actions/tests/__snapshots__/signals.test.js.snap, src/actions/tests/signals.test.js, src/pages/signals/HealthScorePage.js, src/pages/signals/dashboards/HealthScoreDashboard.js, src/pages/signals/dashboards/tests/HealthScoreDashboard.test.js, src/pages/signals/tests/HealthScorePage.test.js, src/reducers/signals.js, src/reducers/tests/__snapshots__/signals.test.js.snap, src/reducers/tests/signals.test.js, src/selectors/signals.js, src/selectors/tests/__snapshots__/signals.test.js.snap, src/selectors/tests/signals.test.js
- Used `total_injection_count` from the health score endpoint in the selector to get injections.
- Removed the call to `/signals/injection` in the health score page and all related code.
- Allow the injection chart to be shown for mailbox provider facet.
- Best to point to production and use the 108 account but there is still one data point in staging from June 10th.
- Go to the health score overview page `signals/health-score`. Check that the number of injections came from the health score endpoint by checking the UI value and the value returned by the API call.
- Do the same thing for the details view. You can access the details view by clicking one of hte facet links in table in the health score overview page.
- Check that the injections chart appears for mailbox-provider facet. Do …
=> SA-888 - Use Health Score endpoint to get injections data

src/actions/helpers/templates.js, src/actions/helpers/tests/templates.test.js
[TR-1781](https://jira.int.messagesystems.com/browse/TR-1781)
- Text content passed to create method will travel with `POST` as the API does not support a null value for the text field
- This was introduced as the result of a prior bug fix for the original templates implementation
- Go to `/templatesV2` and click 'Create New'
- Complete the form and click 'Next'
=> TR-1781 - Fix creating new template in V2

src/pages/inboxPlacement/TestListPage.js, src/pages/inboxPlacement/tests/__snapshots__/TestListPage.test.js.snap
- Removed Link to API docs (since it's a private API) in inbox placement page.
- go to `/inbox-placement`. Verify that the link to the API no longer exists. The empty page only shows up for accounts without any data, You may need to create an account and add the `inbox_placement` account feature flag. See the feature flag confluence doc for instructions.
=> SA-902 - Remove link to API docs for Inbox Placement

src/pages/onboarding/ChoosePlan.js, src/pages/onboarding/tests/ChoosePlan.test.js
AC 985 - Promocode Field
added flag to verifyPromocode in ChangePlan to stop showing double alerts.
Check if this field works correctly on /account/billing/plan(requires feature flag - account_feature_limits ) and /onboarding/plan.
=> AC 985 - Promocode Field

src/pages/inboxPlacement/helpers/formatScheduleLine.js
SA-933 https://jira.int.messagesystems.com/browse/SA-933
Screenshot in description
Moment formatting bug, minutes displayed with only 1 digit if starting with 0. 
Added mm instead of m for moment formatting.
So 5:8pm instead of 5:08pm for inbox placement test start time on test list page.
SA-933
Go to inbox placement from nav, lands on test list page. 
Look at scheduled start and end dates in staging 107
=> SA-933 Inbox Placement fix for moment formatting bug

src/pages/inboxPlacement/components/ProvidersBreakdown.js
- Removed broken link for inbox-placement mailbox breakdown
- point openresty to prod. Go to `/inbox-placement/details/48/details`. Verify that the yahoo text in the Placement Breakdown panel is not a link.
- If pointed to staging, ping me and I'll share an account with data.
=> SA-938 - Remove broken inbox placement link

src/components/CopyToClipboard/CopyToClipboard.js, src/components/collection/SaveCSVButton.js, src/components/collection/tests/SaveCSVButton.test.js, src/pages/inboxPlacement/SeedList.module.scss, src/pages/inboxPlacement/SeedListPage.js, src/pages/inboxPlacement/TestDetailsPage.js, src/pages/inboxPlacement/TestListPage.module.scss, src/pages/inboxPlacement/components/InfoBlock.js, src/pages/inboxPlacement/components/StopTest.js, src/pages/inboxPlacement/components/TestContent.js, src/pages/inboxPlacement/components/tests/__snapshots__/InfoBlock.test.js.snap, src/pages/inboxPlacement/components/tests/__snapshots__/StopTest.test.js.snap, src/pages/inboxPlacement/components/tests/__snapshots__/TestContent.test.js.snap, src/pages/inboxPlacement/helpers/formatScheduleLine.js, src/pages/inboxPlacement/helpers/tests/formatScheduleLine.test.js, src/pages/inboxPlacement/tests/__snapshots__/SeedListPage.test.js.snap, src/pages/inboxPlacement/tests/__snapshots__/TestDetailsPage.test.js.snap
- Addressed UX feedback for Inbox-placement.
- Verify that all UX feedback has been addressed.
Individual Test Pages:
=> SA-853 - UX feedback for inbox-placement

src/pages/signals/HealthScorePage.js, src/pages/signals/tests/HealthScorePage.test.js, src/pages/signals/tests/__snapshots__/HealthScorePage.test.js.snap
- Health score chart percentage when containing 0 data caps at 100%
- Switch env to prod and use 108 account (ask me if you need help getting it set up)
- Go to `/signals/health-score/sid/0` and switch to `Unsubscribes` component from right side
- Check that chart caps at 100%
- I checked other charts and it doesn't seem like anything else needs the restriction since it seems like other percentages are already capping domain.
=> SA-891: Charts max out at 100%

src/pages/signals/HealthScorePage.js, src/pages/signals/tests/HealthScorePage.test.js
- Added check for undefined in charts
- Point env to prod and use 108 account (I can help if needed with this step)
- Go to `/signals/health-score/sid/0`
- Check the different components on right side and click `Unsubscribes`
- Check that the chart has 100%
- Check the other charts with data keep proper scaling with data
=> SA-891: Updated behavior for `undefined` data

src/pages/billing/forms/NewChangePlanForm.js, src/pages/billing/forms/tests/NewChangePlanForm.test.js, src/pages/billing/forms/tests/__snapshots__/NewChangePlanForm.test.js.snap
AC-986: Handle query param for selected plan and promo code
* clicking on a link of this format `/account/billing/plan?code={code}&promo={promoCode}` selects plan(if correct) and applies promocode.
use code = 50K-starter-0519 and any promocode to test
=> AC-986: Handle query param for selected plan and promo code

src/pages/signals/EngagementRecencyPage.js, src/pages/signals/components/charts/barchart/BarChart.js, src/pages/signals/components/charts/barchart/tests/BarChart.test.js, src/pages/signals/components/charts/barchart/tests/__snapshots__/BarChart.test.js.snap, src/pages/signals/components/previews/EngagementRecencyPreview.js, src/pages/signals/components/previews/HealthScorePreview.js, src/pages/signals/components/previews/SpamTrapsPreview.js, src/pages/signals/components/previews/tests/__snapshots__/EngagementRecencyPreview.test.js.snap, src/pages/signals/components/previews/tests/__snapshots__/HealthScorePreview.test.js.snap, src/pages/signals/components/previews/tests/__snapshots__/SpamTrapsPreview.test.js.snap, src/pages/signals/containers/tests/withDateSelection.test.js, src/pages/signals/containers/withDateSelection.js
- Selected and hovered dates have opacity 1 while unselected have opacity ~.7~ .5 for spam trap and engagement recency. All charts on the health score detail page remain the same. 
- Changed tests to assertion tests. 
- Log into account with signals data. Go to engagement recency details page or spam trap details page. Verify that hovering and selecting the bars shows a highlighted state.
=> SA-890 -Selected and Hovered dates are highlighted

src/pages/billing/forms/NewChangePlanForm.js
- Fix bug with query params being cleared before loading bundles or async initialize state
- Navigate to http://app.sparkpost.test/account/billing/plan?code=100K-premier-0519&promo=THXFISH2 on staging
- Check that behavior is correct
=> AC-987: Fixed promo code state bug

src/pages/signals/ComplaintsByCohortPage.js, src/pages/signals/EngagementRateByCohortPage.js, src/pages/signals/EngagementRecencyPage.js, src/pages/signals/HealthScorePage.js, src/pages/signals/SpamTrapPage.js, src/pages/signals/UnsubscribeRateByCohortPage.js, src/pages/signals/components/charts/barchart/BarChart.js, src/pages/signals/components/charts/barchart/tests/BarChart.test.js, src/pages/signals/components/charts/barchart/tests/__snapshots__/BarChart.test.js.snap, src/pages/signals/components/charts/linechart/LineChart.js, src/pages/signals/components/charts/linechart/tests/LineChart.test.js, src/pages/signals/components/charts/linechart/tests/__snapshots__/LineChart.test.js.snap, src/pages/signals/components/previews/tests/__snapshots__/EngagementRecencyPreview.test.js.snap, src/pages/signals/components/previews/tests/__snapshots__/HealthScorePreview.test.js.snap, src/pages/signals/components/previews/tests/__snapshots__/SpamTrapsPreview.test.js.snap, src/pages/signals/containers/tests/__snapshots__/withDateSelection.test.js.snap, src/pages/signals/containers/tests/withDateSelection.test.js, src/pages/signals/containers/withDateSelection.js, src/pages/signals/dashboards/components/HealthScoreChart/HealthScoreChart.js, src/pages/signals/dashboards/components/HealthScoreChart/tests/__snapshots__/HealthScoreChart.test.js.snap, src/pages/signals/tests/ComplaintsByCohortPage.test.js, src/pages/signals/tests/EngagementRateByCohortPage.test.js, src/pages/signals/tests/UnsubscribeRateByCohortPage.test.js, src/pages/signals/tests/__snapshots__/ComplaintsByCohortPage.test.js.snap, src/pages/signals/tests/__snapshots__/EngagementRateByCohortPage.test.js.snap, src/pages/signals/tests/__snapshots__/EngagementRecencyPage.test.js.snap, src/pages/signals/tests/__snapshots__/HealthScorePage.test.js.snap, src/pages/signals/tests/__snapshots__/SpamTrapPage.test.js.snap, src/pages/signals/tests/__snapshots__/UnsubscribeRateByCohortPage.test.js.snap
- Added a flag `shouldHighlightSelected` to Barchart. This is set to false in the default state which shows the latest recommendations but does not highlight the bar. 
- Added the flag as props to signals charts. 
- Go to health score/spam trap/engagement recency pages and hover/select the bars in each graph.
=> SA-954 - Improve Selected and Hovered states

src/pages/billing/components/CurrentPlanSection.js, src/pages/billing/components/CurrentPlanSection.module.scss, src/pages/billing/components/tests/CurrentPlanSection.test.js, src/pages/billing/forms/NewChangePlanForm.js, src/pages/billing/forms/tests/__snapshots__/NewChangePlanForm.test.js.snap
- Add deprecated plan warning when selecting new plan
- If you have an account with deprecated plan, select a new plan
- Warning should show on right
- Not sure how to get deprecated plan. May have to ask accounts
=> AC-989: Add deprecated plan warning

src/components/navigation/components/NavGroup.js, src/components/navigation/components/NavItem.js, src/components/navigation/components/NavItem.module.scss, src/components/navigation/components/tests/NavGroup.test.js, src/components/navigation/components/tests/__snapshots__/NavGroup.test.js.snap
[FE-724](https://jira.int.messagesystems.com/browse/FE-724)
- Added `href` values to links that were missing them to make them keyboard accessible
- Added `role="button"` to `a` elements that do not navigate to new routes or pages
- Added `aria-expanded` attribute to relevant nav items that collapse and expand. This value toggles when clicked (or by hitting enter with the keyboard)
- Replaced `transition` property to target `color` specifically to improve performance 
- Use the keyboard to tab to the relevant nav items
- Make sure the keyboard can be used to expand and collapse subsections within the nav via the enter key
- Make sure all items can be "clicked" on using the enter key
=> FE-724 - Updating sidebar navigation markup to make it keyboard accessible

src/helpers/tests/validation.test.js, src/helpers/validation.js, src/pages/reports/components/ShareModal.js, src/pages/reports/messageEvents/components/AdvancedFiltersModal.js, src/pages/reports/messageEvents/components/MessageEventsSearch.js, src/pages/reports/messageEvents/components/MessageEventsSearch.module.scss, src/pages/reports/messageEvents/components/SearchForm.js, src/pages/reports/messageEvents/components/SearchForm.module.scss, src/pages/reports/messageEvents/components/SearchQuery.js, src/pages/reports/messageEvents/components/tests/AdvancedFiltersModal.test.js, src/pages/reports/messageEvents/components/tests/SearchQuery.test.js, src/pages/reports/messageEvents/components/tests/__snapshots__/AdvancedFiltersModal.test.js.snap, src/pages/reports/messageEvents/components/tests/__snapshots__/MessageEventsSearch.test.js.snap, src/pages/reports/messageEvents/components/tests/__snapshots__/SearchQuery.test.js.snap, src/pages/reports/messageEvents/helpers/transformData.js
- Change made to events filter box
=> SE-268: Events Filters UX Improvements

src/pages/templates/CreatePage.container.js, src/pages/templates/EditPage.container.js, src/pages/templates/PreviewDraftPage.container.js, src/pages/templates/PreviewPublishedPage.container.js, src/pages/templates/PublishedPage.container.js, src/pages/templatesV2/CreatePage.container.js, src/pages/templatesV2/EditAndPreviewPage.container.js, src/selectors/accessConditionState.js, src/selectors/account.js, src/selectors/templates.js, src/selectors/tests/__snapshots__/templates.test.js.snap, src/selectors/tests/accessConditionState.test.js, src/selectors/tests/account.test.js, src/selectors/tests/templates.test.js
Refer to [TR-1750](https://jira.int.messagesystems.com/browse/TR-1750)
- If template options are not define for a template, they should be initialized with default account options for both new and old editors 
Must test all template actions in both old and new template editors.  The expectation is if the template options are not set, they will use the account option defaults.
- Create
- Duplicate
- Edit
- Publish
- Preview
- Send Test
=> TR-1750: AMP enabled Test Emails Sent in-app always send with open tracking enabled

src/actions/inboxPlacement.js, src/actions/tests/inboxPlacement.test.js, src/config/routes/inboxPlacement.js, src/pages/inboxPlacement/AllMessagesPage.js, src/pages/inboxPlacement/AllMessagesPage.module.scss, src/pages/inboxPlacement/TestDetailsPage.js, src/pages/inboxPlacement/TestListPage.js, src/pages/inboxPlacement/components/AllMessagesCollection.js, src/pages/inboxPlacement/components/AllMessagesCollection.module.scss, src/pages/inboxPlacement/components/InfoBlock.js, src/pages/inboxPlacement/components/ProvidersBreakdown.js, src/pages/inboxPlacement/components/StopTest.js, src/pages/inboxPlacement/components/tests/AllMessagesCollection.test.js, src/pages/inboxPlacement/components/tests/InfoBlock.test.js, src/pages/inboxPlacement/components/tests/StopTest.test.js, src/pages/inboxPlacement/components/tests/__snapshots__/AllMessagesCollection.test.js.snap, src/pages/inboxPlacement/components/tests/__snapshots__/InfoBlock.test.js.snap, src/pages/inboxPlacement/components/tests/__snapshots__/ProvidersBreakdown.test.js.snap, src/pages/inboxPlacement/index.js, src/pages/inboxPlacement/tests/AllMessagesPage.test.js, src/pages/inboxPlacement/tests/TestDetailsPage.test.js, src/pages/inboxPlacement/tests/__snapshots__/AllMessagesPage.test.js.snap, src/pages/inboxPlacement/tests/__snapshots__/TestDetailsPage.test.js.snap, src/reducers/inboxPlacement.js, src/reducers/tests/__snapshots__/inboxPlacement.test.js.snap, src/reducers/tests/inboxPlacement.test.js
- Update StopTest component to be more independent. Moved the dispatched calls into the component rather than being passed as a prop.
- Updated the InfoBox component to have custom css styling. Also removed the break tag as it didn't seem to affect the current implementations. 
- Added new routes and action/reducers for the all messages page /endpoint. 
- Created the all messages page. Currently only supports mailbox-providers but code for future sending ip support is included. 
- Added link to the all messages page in the details page in the breakdown by mailbox provider section
- Go to /inbox-placement. Click on any (real) test. On the details page, scroll down and click on one of the mailbox-providers. Verify that the new page looks like the mocks.
=> SA-770 - Display results by seed addresses for mailbox provider

src/selectors/account.js, src/selectors/tests/account.test.js
[TR-1888](https://jira.int.messagesystems.com/browse/)
- Guard against account options being undefined
- Create a subaccount
- Create a template assigned to that subaccount
- Create a subaccount reporting user 
- Open the template (was displaying sorry page, now should load editor as expected)
=> TR-1888 Default account options to empty object for selectDefaultTemplateOptions

src/pages/templatesV2/ListPage.js, src/pages/templatesV2/tests/ListPage.test.js
TR-1374 - Resolve test data duplication persistence issue
- Resolves issue with test data not persisting for published templates on the list page
- Go to `/templatesV2`
- Find a published template with test data
- Duplicate that template and verify that the same test data exists in the copy
- Double check that drafts duplicate in a similar manner
=> TR-1374 - List Page duplication fix

src/pages/templatesV2/context/EditorContext.js, src/pages/templatesV2/context/tests/EditorContext.test.js
[TR-1895](https://jira.int.messagesystems.com/browse/TR-1895)
- Added check for which version of the template is currently being viewed before retrieving 
- Go to `/templatesV2`
- Go to the details page of any template in draft mode and check in the console for any 404s related to a request for the published draft
- Update relevant tests to match updated implementation
=> TR-1895 - Remove unnecessary extra request on mount

src/pages/billing/components/CardSection.js, src/pages/billing/components/SubmitSection.js, src/pages/billing/components/tests/CardSection.test.js, src/pages/billing/components/tests/SubmitSection.test.js, src/pages/billing/forms/NewChangePlanForm.js
AC-1033 - Credit Card in Form
- In the new change plan form, the credit card form appears
- Credit card section loads once content in FeatureComparisonSection is complete
- Credit card section loads existing credit card information if available
- Navigate to account/billing/plan
- Check that credit card form loads if no card is present after the FeatureChangeSection is complete.
- Check that credit card section loads with saved card information after the FeatureChangeSection is complete.
-Credit card section doesn't show up when selected plan is free.
=> AC-1033 - Credit Card in Form

src/pages/templatesV2/EditAndPreviewPage.container.js, src/pages/templatesV2/components/EditSection.js, src/pages/templatesV2/components/EditSection.module.scss, src/pages/templatesV2/components/InsertSnippetModal.js, src/pages/templatesV2/components/PreviewControlBar.module.scss, src/pages/templatesV2/components/tests/EditSection.test.js, src/pages/templatesV2/components/tests/InsertSnippetModal.test.js, src/pages/templatesV2/components/tests/__snapshots__/EditSection.test.js.snap
[TR-1347](https://jira.int.messagesystems.com/browse/TR-1347)
- Adds popover to the templates editor with "Insert Snippet" action
- Adds new `<InsertSnippetModal/>` component
- Adds supporting tests for both of these changes
- Simplifies `EditSection.module.scss` styles
- Go to `/templatesV2` and click on a template
- Verify that the kebab menu opens the popover
- Verify that the "Insert Snippet" action opens a modal and closes the popover
- Verify that snippets are searchable in the typeahead
- Verify that the selected snippet is populated in the copy field
=> TR-1347 - Insert snippets in Templates V2

src/pages/templatesV2/ListPage.js, src/pages/templatesV2/components/EditNavigation.js, src/pages/templatesV2/components/EditSection.js, src/pages/templatesV2/components/ListComponents.js, src/pages/templatesV2/components/PreviewControlBar.js, src/pages/templatesV2/components/RecentActivity.js, src/pages/templatesV2/components/SendTestEmailButton.js, src/pages/templatesV2/components/editorActions/DeleteTemplate.js, src/pages/templatesV2/components/editorActions/DraftModeActions.js, src/pages/templatesV2/components/editorActions/DuplicateTemplate.js, src/pages/templatesV2/components/editorActions/DuplicateTemplateModal.js, src/pages/templatesV2/components/editorActions/PublishedModeActions.js, src/pages/templatesV2/components/editorActions/SaveAndPublish.js, src/pages/templatesV2/components/editorActions/SaveDraft.js, src/pages/templatesV2/components/editorActions/ViewPublished.js, src/pages/templatesV2/components/editorActions/tests/__snapshots__/DraftModeActions.test.js.snap, src/pages/templatesV2/components/editorActions/tests/__snapshots__/DuplicateTemplateModal.test.js.snap, src/pages/templatesV2/components/editorActions/tests/__snapshots__/PublishedModeActions.test.js.snap, src/pages/templatesV2/components/editorActions/tests/__snapshots__/SaveAndPublish.test.js.snap, src/pages/templatesV2/components/editorActions/tests/__snapshots__/SaveDraft.test.js.snap, src/pages/templatesV2/components/editorActions/tests/__snapshots__/ViewPublished.test.js.snap, src/pages/templatesV2/components/tests/__snapshots__/EditNavigation.test.js.snap, src/pages/templatesV2/components/tests/__snapshots__/EditSection.test.js.snap, src/pages/templatesV2/components/tests/__snapshots__/PreviewControlBar.test.js.snap, src/pages/templatesV2/constants/editTabs.js
[TR-1900](https://jira.int.messagesystems.com/browse/TR-1900)
- Added `data-id` attributes to interactive elements within the templates editor.
- Added some missing ARIA roles
- Updated relevant snapshots
Verify `data-id` attributes exist on the following elements:
- The duplicate and delete buttons on the table collection
- The subnavigation items
- The edit section popover trigger
- The desktop and mobile preview buttons on the preview panel
- The duplicate and delete buttons in the 'Recent Activity' section on the list page
- The 'Send a Test' button on the preview panel
- The text fields within the 'Send a Test' modal
- The 'Delete' button within the delete template modal
- The editor actions popover trigger in the top right of the view
- Each action in the editor actions popover in …
=> TR-1900 - Adds `data-id` attributes to various interactive elements in the new templates editor

src/pages/templatesV2/components/EditHtmlSection.js, src/pages/templatesV2/components/EditSection.js, src/pages/templatesV2/components/EditSection.module.scss, src/pages/templatesV2/components/Editor.js, src/pages/templatesV2/components/Editor.module.scss, src/pages/templatesV2/components/tests/EditSection.test.js, src/pages/templatesV2/components/tests/__snapshots__/EditSection.test.js.snap
[TR-1899](https://jira.int.messagesystems.com/browse/TR-1899)
- Add `<Tag/>` component instance for editor tabs when in published mode:
- Swap vertical kebab with horizontal kebab after chat with UX
- Added conditional rendering to the popover
- Updated editor styles when in read only mode
- Go to `/templatesV2` and click on a template in draft mode
- Click 'Save and Publish' in the top right
- Verify that the Popover is no longer available on the editor tabs
- Verify that the `<Tag/>` renders for the HTML, AMP HTML, and Text tabs but *not* for the Test Data tab
=> TR-1899 - Add  style to editor tabs that are in read only mode

src/pages/account/components/CancellationPanel.js, src/pages/account/components/tests/CancellationPanel.test.js
- The button on the account cancellation pane (/account/settings at bottom) is now using the "destructive" variant of Matchbox's Button
- Go to /account/settings, scroll to bottom, ensure button for "Cancel Account" is like this one: https://sparkpost.github.io/matchbox/?selectedKind=Action%7CButton&selectedStory=Destructive
=> FE-734: Make Cancellation Button Destructive

src/pages/templatesV2/components/RecentActivity.js, src/pages/templatesV2/components/tests/RecentActivity.test.js
[TR-1946](https://jira.int.messagesystems.com/browse/TR-1946)
- When fewer than three templates are present, `null` is returned instead of nothing
- Updated tests to fail by using a full `mount`, then verified that the fix addressed the issue
- With a new account (or any account with fewer than 3 templates), go to `/templatesV2` and verify that no Recent Activity component renders *and* the app does not render the error boundary UI
=> TR-1946 - Resolve issue with RecentActivity component returning nothing when fewer than 3 templates are present

src/pages/templatesV2/components/settings/SettingsForm.js, src/pages/templatesV2/components/settings/tests/SettingsForm.test.js
TR-1901 - When updating the draft from the template settings view, the updated state of the template content should be saved
- updated state of template is now being saved when switching tabs and when settings are updated.
- Make changes to the HTML tab of the editor
- Swap to "Template Settings"
- Save those settings
- Saved Indicator changes to SAVED
- Return to the HTML tab and verify that the content stays the same
=> TR-1901 - When updating the draft from the template settings view, the updated state of the template content should be saved

cypress/tests/templates/templates.js, src/pages/templatesV2/components/EditSection.js, src/pages/templatesV2/components/tests/EditSection.test.js, src/pages/templatesV2/components/tests/__snapshots__/EditSection.test.js.snap
[TR-1849](https://jira.int.messagesystems.com/browse/TR-1849)
- Adds AMP Boilerplate modal to control insertion of AMP boilerplate in to the AMP HTML editor tab
1. Go to `/templatesV2`
1. Create a new template
1. Go to the 'AMP HTML' tab and click on the popover trigger kebab in top right, then 'Insert AMP Boilerplate'
1. Confirm!
1. Verify that there are no typos in my content and that it makes sense!
1. Verify that the AMP boilerplate was inserted appropriately
=> TR-1849 - Add insert AMP boilerplate modal

package-lock.json, package.json, src/actions/templates.js, src/actions/tests/__snapshots__/templates.test.js.snap, src/pages/templatesV2/EditAndPreviewPage.container.js, src/pages/templatesV2/components/ListComponents.js, src/pages/templatesV2/components/editorActions/PublishedModeActions.js, src/pages/templatesV2/components/editorActions/SaveAndPublishConfirmationModal.js, src/pages/templatesV2/components/editorActions/tests/PublishedModeActions.test.js, src/pages/templatesV2/components/editorActions/tests/SaveAndPublishConfirmationModal.test.js, src/pages/templatesV2/components/editorActions/tests/__snapshots__/PublishedModeActions.test.js.snap, src/pages/templatesV2/components/tests/__snapshots__/ListComponents.test.js.snap, src/selectors/templates.js, src/selectors/tests/__snapshots__/templates.test.js.snap
[TR-1948](https://jira.int.messagesystems.com/browse/TR-1948)
- Updated Matchbox version to get a11y updates
- Updated `publishV2` to use `updateV2` instead of `update`
- Renamed some variables for clarity's sake
- Updated markup for rendering status on the list page
- Removed unnecessary spreading of data on the `SaveAndPublishConfirmationModal`
- Updated templates selector to accurately reflect the template's current status
1. Go to `/templatesV2`
1. Create a new template
1. Go back to the list page and verify that the template is marked as a 'Draft'
1. Open that template and publish it
1. Go back to the list page and verify that the template is marked as 'Published'
1. Open the template and click 'Edit Draft'
1. Make a change to the draft and click 'Save and Publish'
1. Verify that the …
=> TR-1948 - Resolve bug with updating an existing template from the draft state to the published state

src/pages/templatesV2/components/RecentActivity.js, src/pages/templatesV2/components/tests/RecentActivity.test.js
[TR-1958](https://jira.int.messagesystems.com/browse/TR-1958)
- Incorporated `<PageLink/>` component in to `<RecentActivity/>` component
- Added supporting unit tests
- Go to `/templatesV2` and verify that each Panel links to a the relevant template
=> TR-1958 - Add links to RecentActivity section

src/pages/inboxPlacement/components/TestDetails.js, src/pages/inboxPlacement/components/TestDetails.module.scss, src/pages/inboxPlacement/components/tests/TestDetails.test.js, src/pages/inboxPlacement/components/tests/__snapshots__/TestDetails.test.js.snap
- Added a search bar to the top of the inbox placement details page
- You can now filter the list by Mailbox Providers by case insensitive text matching of region name or mailbox provider name
- You can now filter the list by Region by case insensitive text matching of region name
- Use /inbox-placement/details/74/details on 108 account
- Search "america" on the mailbox provider's list and you should see at&t and comcast
- Switch to filtering by region and you should see North America
=> SA-1001: Filter Inbox Placement Tests by Text Field

src/components/navigation/components/Top.module.scss
- Set the height of the container of the icon so that safari can determine the height of the logo 
- Check the SparkPost logo at the top on the mobile (small viewport) view of the app in:
- Chrome
- Safari 
- Firefox
- Ensure they all have the same look and feel
=> FE-740: Set Container Height of SparkPost Logo For Safari

src/pages/inboxPlacement/AllMessagesPage.js, src/pages/inboxPlacement/components/PlacementBreakdown.js, src/pages/inboxPlacement/components/tests/__snapshots__/PlacementBreakdown.test.js.snap, src/pages/inboxPlacement/helpers/formatFilterName.js, src/pages/inboxPlacement/helpers/tests/formatFilterName.test.js, src/pages/inboxPlacement/tests/AllMessagesPage.test.js, src/pages/inboxPlacement/tests/__snapshots__/AllMessagesPage.test.js.snap, src/selectors/inboxPlacement.js, src/selectors/tests/inboxPlacement.test.js
- Added all messages filtered by region
- To to /inbox-placement and click on any tests to access the details page
- Switch dropdown to region. 
- Click on any of the regions.
- The all messages page should load. Verify that filtering is correct by checking that the number sent matches the number of messages in the table.
=> SA-1002: Add inbox placement messages filtered by region

src/components/planPicker/PlanPicker.js, src/components/planPicker/tests/__snapshots__/PlanPicker.test.js.snap
- The keyboard in iOS does not open when you use the "custom select" when selecting a plan on the /onboarding/plan page.
- Use the device simulator from xcode and navigate to the /onboarding/plan page. (Turns out you can go directly there without making a new account)
- Press the "Select a Plan" dropdown and see that the keyboard does not trigger itself open (Note: You need to have the simulator set up to not use the hardware keyboard for the on-screen keyboard to pop up to begin with).
- Ensure that choosing an option besides the default indeed changes the value
=> FE-754 Do Not Trigger Keyboard on iOS for Select a Plan Dropdown

src/components/card/Card.module.scss, src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/GettingStartedGuide.module.scss, src/pages/dashboard/components/tests/GettingStartedGuide.test.js
AC-1080 - Sending module guide set
- Includes the options for "Show Me SparkPost" guide set and the "Let's Code" guide set
- reduced the margin for CardContent.
- BreadCrumbs are not the part of this ticket.
- Enable "messaging_onboarding" ui option for the account.
- Navigate to /dashboard.
- check if the second step of guide is similar to [mocks](https://sparkpost.invisionapp.com/share/DHULLYL45GB#/screens/390961094)
=> AC-1080 - Sending module guide set

src/pages/users/ListPage.js, src/pages/users/tests/__snapshots__/ListPage.test.js.snap
- Use abbreviation for Two factor authentication column label.
- Go to `/account/users`. Verify that the 2fa column is on one line and hovering over shows the unabbreviated word.
=> FE-735: Fix 2fa column name

src/pages/inboxPlacement/AllMessagesPage.js, src/pages/inboxPlacement/tests/AllMessagesPage.test.js
- Updated query param from `mailbox-provider` to `mailbox_providers`.
- Fixed typo in variable name
- Improved tests
- Go to '/inbox-placement`.
- Click on any test.
- Click on an email domain in the table.
- Verify that the api call uses `mailbox_providers` and that filtering still works. IE: The aggregate
results show 10 responses so there should be 10 messages in the table.
=> SA-1033 - Update query params for all-messages endpoint

src/components/breadcrumbs/BreadCrumbs.js, src/components/breadcrumbs/BreadCrumbs.module.scss, src/components/breadcrumbs/index.js, src/components/breadcrumbs/tests/BreadCrumbs.test.js, src/components/index.js, src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js
AC-1081 - Breadcrumbs for the modules
- Added a shared components to display BreadCrumbs.
- Added breadCrumbs to the GettingStartedGuide
- Enable "messaging_onboarding" ui option for the account.
- Navigate to /dashboard.
- check if breadcrumbs are similar to [mocks](https://sparkpost.invisionapp.com/share/DHULLYL45GB#/screens/390961094)
=> AC-1081 - Breadcrumbs for the modules

src/actions/alerts.js, src/config/navItems/index.js, src/constants/index.js, src/helpers/date.js, src/pages/alerts/DetailsPage.js, src/pages/alerts/components/AlertIncidents.js, src/pages/alerts/components/AlertIncidents.module.scss, src/pages/alerts/components/tests/AlertIncidents.test.js, src/pages/alerts/components/tests/__snapshots__/AlertIncidents.test.js.snap, src/pages/alerts/constants/formConstants.js, src/pages/alerts/containers/DetailsPage.container.js, src/pages/alerts/tests/DetailsPage.test.js, src/pages/alerts/tests/__snapshots__/DetailsPage.test.js.snap, src/pages/inboxPlacement/helpers/formatScheduleLine.js, src/reducers/alerts.js
- Added alert incidents table
- Added alert incidents action/reducer
- Using appteam account (prod works nicely), go to `/alerts`
- Go to one of the alerts page
- Check that table is at bottom
- Check empty state
- Check that table properly renders active tag
=> SE-379: List incidents on alert details page

src/components/shortKeyCode/ShortKeyCode.js
FE-733 -  Reduce API key shortcode font size
- changed the  API key shortcode font size to be consistent with our other fonts
- Navigate to /account/api-keys and check key columns font-size.
=> FE-733 -  Reduce API key shortcode font size

src/pages/inboxPlacement/components/TrendsChart.js
- Fixed floating point bug.
- on appteam staging, to to `/inbox-placement`. Check the data for 11/7. The values should be integers now.
=> SA-970: Fix floating point bug

src/helpers/conditions/account.js, src/helpers/conditions/tests/account.test.js, src/pages/dashboard/DashboardPage.js, src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/GuideListItem.js, src/pages/dashboard/components/GuideListItem.module.scss, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/dashboard/components/tests/GuideListItem.test.js
AC-1082 : "Show Me SparkPost" list for onboarding
- Added the GuideListItem.
- List shows up when Show Me SparkPost button is clicked.
- Breadcrumb includes "Show Me SparkPost".
- Enable "messaging_onboarding" ui option for the account.
- Navigate to /dashboard.
- Click on "Start Sending" and then on "Show Me SparkPost".
- check if list is similar to [mocks](https://sparkpost.invisionapp.com/share/DHULLYL45GB#/screens/390961095)
- adding itemCompleted={true} to one of the <GuideListItem> and check if it is similar to mocks. 
- List persists as the active list through session until switching off of guide set explicitly.
=> AC-1082 : "Show Me SparkPost" list for onboarding

.eslintrc
- Used canonical eslint ruleset instead of recommended
- This is essentially just the recommended ruleset in addition to using the lodash object everywhere (import _ from "lodash"). 
- Turn off all "Lodash over Native Functions" rules that are in the canonical ruleset.
- Not extremely testable, but make sure you can write code in your IDE that uses native functions, for example. `Object.keys(arr).map(blah => blah.doIt())`
=> FE-770 Remove all lodash method over native function rules in eslint

src/pages/inboxPlacement/TestDetailsPage.js, src/pages/inboxPlacement/components/PlacementBreakdown.js, src/pages/inboxPlacement/components/TestDetails.js, src/pages/inboxPlacement/components/tests/PlacementBreakdown.test.js, src/pages/inboxPlacement/components/tests/TestDetails.test.js, src/pages/inboxPlacement/components/tests/__snapshots__/PlacementBreakdown.test.js.snap, src/pages/inboxPlacement/components/tests/__snapshots__/TestDetails.test.js.snap, src/pages/inboxPlacement/helpers/formatFilterName.js, src/pages/inboxPlacement/helpers/tests/formatFilterName.test.js, src/pages/inboxPlacement/tests/TestDetailsPage.test.js, src/reducers/inboxPlacement.js
- Added Sending- IP as an option in the dropdown + related tests
- Added formatting to display Sending IP in the table
- Random prettier changes
- Go to `/inbox-placement`. Click on a test. On the details page, use the dropdown to change the selector from `mailbox provider` to `sending ip`.
=> Sa 1078 - Inbox Placement grouped by sending ip

src/pages/templates/EditAndPreviewPage.container.js, src/pages/templates/components/SendTestEmailButton.js, src/pages/templates/components/tests/SendTestEmailButton.test.js
[TR-2005](https://jira.int.messagesystems.com/browse/TR-2005)
- Renamed import of `setTestData` action to fix issue with duplicate function names in editor context
- Invoke the `setTestData` action when the user opens the send preview modal in published mode
- Added supporting test
1. Go to `/templates`
1. Make a new template, add some substitution data and use the substitution data in your template with curly braces, e.g. `{{ data }}`
1. Click "Save and Publish"
1. When in published mode, edit the test data and click "Send a Test"
1. Send a preview email to your email address and verify that the new data is present
1. Additionally, leave the currently opened, published template, then  open it again from the list page
1. Verify that the new test data persisted.
=> TR-2005 - Implement saving test data in published mode before sending a template preview

src/pages/alerts/components/AlertDetails.module.scss
- Removed manual alignment for matchbox Tag component
- Create an alert (or view an existing one) that has an icon in a Tag (slack/webbook notify).
- Ensure the icon is vertically aligned.
Note: I searched through the rest of the code base for instances where we override the styles of the matchbox Tag component and this is the only one that interfered with the alignment. All others were margin related.
=> FE-762 Removed override for Tag styles from Matchbox bug that is now fixed

.eslintrc, src/pages/templates/components/SendTestEmailButton.js, src/pages/templates/components/editorActions/SaveAndPublishConfirmationModal.js, src/pages/templates/components/editorActions/SaveDraft.js, src/pages/templates/components/settings/SettingsForm.js, src/pages/templates/components/settings/tests/SettingsForm.test.js, src/pages/templates/components/tests/SendTestEmailButton.test.js
- The PUT request to save a template is made with all the template params instead of just content.
- Open a draft template in the editor
- Open the "template settings" tab
- Modify any of the fields (easiest with click & open options)
- Click "Save Settings" button
- Click "Save as Draft" button
- Refresh the page to confirm changes persisted
=> TR-2017: Unable to save and publish changes to template options

cypress/tests/templates/templates.js, package-lock.json, src/__testHelpers__/renderWithRedux.js, src/pages/templates/ListPage.js, src/pages/templates/components/editorActions/DeleteTemplateModal.js, src/pages/templates/components/editorActions/DeleteTemplateModal.module.scss, src/pages/templates/components/editorActions/DraftModeActions.js, src/pages/templates/components/editorActions/PublishedModeActions.js, src/pages/templates/components/editorActions/tests/DeleteTemplateModal.test.js, src/pages/templates/components/editorActions/tests/DraftModeActions.test.js, src/pages/templates/components/editorActions/tests/PublishedModeActions.test.js, src/pages/templates/components/editorActions/tests/__snapshots__/DraftModeActions.test.js.snap, src/pages/templates/components/editorActions/tests/__snapshots__/PublishedModeActions.test.js.snap, src/pages/templates/tests/ListPage.test.js, src/pages/templates/tests/__snapshots__/ListPage.test.js.snap
[TR-2010](https://jira.int.messagesystems.com/browse/TR-2010)
- Refactored delete template modal to use pure props instead of editor context
- Updated styles for the delete template modal to be a lot scarier (matching the very frightening mocks)
- Refactored delete template modal tests to use React Testing Library
- Updated some old Enzyme tests to match the new implementation
- ...it maybe goes without saying, but some Prettier reformatting going on here
- Go to `/templates` and delete a template from the 'Recent Activity' section and the `<table/>` - verify that the new styles are present *and* that deleting works as expected
- Click on a template in draft mode and use the editor actions in the top right and delete the template. Verify that the new styles are present and that deleting …
=> TR-2010 - Updates delete template modal styles to be much *much* scarier 

config/jest/matchers/index.js, config/jest/matchers/toBeValid.js, config/jest/matchers/toBeValidMomentDate.js, config/jest/matchers/toHaveTextContent.js, config/jest/matchers/toHaveValue.js, config/jest/setup.js, src/components/multiEmailField/tests/MultiEmailField.test.js, src/helpers/tests/date.test.js, src/pages/templates/components/tests/SendTestEmailButton.test.js
[FE-797](https://jira.int.messagesystems.com/browse/FE-797)
- Added custom `toHaveValue` matcher that conditionally runs the Enzyme and Testing Library `.toHaveValue` matchers
- Updated `toHaveTextContent` custom matcher to conditionally run the Testing Library variant
- Renamed `toBeValid` => `toBeValidMomentDate`
- `npm run test SendTestEmailButton.test.js`, then:
+ on line 101, change the asserted value to `'nick'` and verify the test feedback works as expected
+ on line 101, change the selected element from a valid one to a random variable (i.e., `2`)
+ on line 101, change the assertion to a negative one (by chaining `.not`) and verify the test feedback works as expected
- `npm run test MultiEmailField.test.js`, then:
+ on line 103, change the asserted value to 'you@me.com' and verify …
=> FE-797 - Resolve React Testing Library matcher conflicts

src/pages/dashboard/components/FeaturesStepList.js, src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/SendingStepList.js, src/pages/dashboard/components/tests/FeatureStepList.test.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/dashboard/components/tests/SendingStepList.test.js, src/pages/dashboard/constants.js
AC-1087 - "Let's Code" list for onboarding
- Bread crumb includes "Let's Code"
- List persists as the active list through session until switching off guide explicitly
- mock - https://sparkpost.invisionapp.com/share/DHULLYL45GB#/screens/390961106
- Enable messaging_onboarding ui flag.
- Check if it matches the mock.
=> AC-1087 - "Let's Code" list for onboarding

src/config/default.js, src/pages/recipientValidation/components/tests/ListForm.test.js
[TR-2047](https://jira.int.messagesystems.com/browse/TR-2047)
- Reformatted two files with Prettier
- Lowered max RV file size upload from 200MB to 20MB (NOTE: the config defines the limit in bytes, which was derived from https://www.gbmb.org/bytes-to-mb)
- Updated your local `ngnix.conf` (mine was in `/usr/local/etc/openresty`) file to accept larger file uploads, then restart openresty:
- Directions here: https://stackoverflow.com/questions/26717013/how-to-edit-nginx-conf-to-increase-file-size-upload
- Go to `/recipient-validation/list` and upload a file that is above 20MB and another that is below 20 MB - **For whoever picks up the review, I have some uploaded CSV files in a Google Drive folder that I will share with you**
- Verify that the file size under 20 MB uploads successfully
- …
=> TR-2047 - Lower max file size for RV from 200MB to 20MB

package.json
- Adds the `FORCE_COLOR` env variable to foreman script
- Run `npm start` and verify that the output has colors vs. only white text
=> Adds FORCE_COLOR env variable to foreman script

src/pages/alerts/components/AlertForm.js, src/pages/alerts/components/AlertIncidents.js, src/pages/alerts/components/fields/EvaluatorFields.js, src/pages/alerts/components/fields/tests/__snapshots__/EvaluatorFields.test.js.snap, src/pages/alerts/components/tests/__snapshots__/AlertForm.test.js.snap, src/pages/alerts/components/tests/__snapshots__/AlertIncidents.test.js.snap
- Alert edit form disabled changing metric/evaluator
- Health score (raw) now removes percent correctly in alert incidents
- Health score label will now show appropriate evaluator as column header in incidents table
- Added keys to table
- Changed precision of values
- Go to `/alerts` page and click on a health score alert (or create one)
- Create form should be able to change the metric/evaluator
- Edit form should disable metric field and evaluator (if health score metric alert)
- Verify alert incident table changes are made
=> SE-463: Alert incidents polish

src/actions/helpers/sparkpostApiRequest.js, src/actions/helpers/tests/sparkpostApiRequest.test.js, src/config/default.js, src/pages/recipientLists/components/RecipientListForm.js, src/pages/recipientLists/components/tests/__snapshots__/RecipientListForm.test.js.snap
[TR-2038](https://jira.int.messagesystems.com/browse/TR-2038)
- Prettier formatting for multiple files
- Incorporate default message details content
- Updates sparkPostApi request tests so they no longer violate the ESLint `jest/no-try-expect` rule (https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-try-expect.md)
1. Reach out to me and I'll give access to example CSV files that can be used to verify the frontend validation behavior
1. Upload said files and encounter the new error
=> TR-2038 - Simpler implementation - sync validation of recipient list file size handling by updating config, add global 413 error handling

src/actions/blacklist.js, src/actions/tests/blacklist.test.js, src/pages/blacklist/WatchlistPage.js, src/pages/blacklist/components/MonitorsCollection.js, src/pages/blacklist/components/StopMonitoringModal.js, src/pages/blacklist/components/StopMonitoringModal.module.scss, src/pages/blacklist/components/tests/StopMonitoringModal.test.js, src/pages/blacklist/tests/WatchlistPage.test.js, src/reducers/blacklist.js, src/reducers/tests/__snapshots__/blacklist.test.js.snap, src/reducers/tests/blacklist.test.js
- Added delete modal
- go to `/blacklist/watchlist` and click on the `Stop Monitoring` Button.
- The delete success reducer deletes the resource from redux store upon success to have a cleaner transition.
=> SA-1132 - Add delete functionality for blacklist monitors

src/actions/bounceReport.js, src/actions/delayReport.js, src/actions/engagementReport.js, src/actions/tests/bounceReport.test.js, src/actions/tests/delayReport.test.js, src/actions/tests/engagementReport.test.js
See [SA-1145](https://jira.int.messagesystems.com/browse/SA-1145)
- Modified how metrics parameter values are joined on bounce, delayed, and engagement reports
- Create a subaccount with a comma in the name
- Open each bounce, delayed, and engagement reports
- Add filter for your new subaccount
Expected, to not break.
=> SA-1145: Invalid metrics parameter on bounce, delayed, and engagement report

src/components/pendo/Pendo.js, src/components/pendo/tests/Pendo.test.js, src/components/pendo/tests/__snapshots__/Pendo.test.js.snap
Refer to [FE-799](https://jira.int.messagesystems.com/browse/FE-799)
- Sending account created timestamp to Pendo
- Execute `pendo.validateInstall()` in devtools console and confirm "accountCreatedAt" is set
- Confirm Pendo is correctly translating our timestamp — https://app.pendo.io/account/app_107
=> FE-799 Provide account creation timestamp to Pendo

src/__func__/billing/__snapshots__/changePlanFirstTime.test.js.snap, src/__func__/billing/__snapshots__/updateBillingDetails.test.js.snap, src/__func__/signup/__snapshots__/choosePaidPlan.test.js.snap, src/actions/billing.js, src/actions/billingCreate.js, src/actions/billingUpdate.js, src/actions/tests/billingCreate.test.js, src/actions/tests/billingUpdate.test.js, src/pages/billing/components/PlanSelect.js, src/pages/billing/context/FeatureChangeContext.js, src/pages/billing/context/tests/__snapshots__/FeatureChangeContext.test.js.snap
AC-1158 - Test new billing page (Fixes)
1. Changing the wordings - “Your new plan doesn’t include dedicated IPs. Your current IP(s) will be removed at the end of your current billing cycle.”
2. Adding the filtering for secret bundles in PlanSelect
3. users were still able to "enable tfa required " after selecting a starter plan. Solved by - [an additional call to {{/billing/subscription/check}} after the form has been submitted when a user upgrade from free to paid (along with the call to {{/account/subscription/check}})]
- enable ui flag - "account_feature_limits"
- to test the first change downgrade from premier plan to starter/free and check the wording in Changes to Features Section
- to test the second change make sure 2.5M plan gets selected when you click on this url …
=> AC-1158 - Test new billing page (Fixes)

src/components/vwo/VisualWebsiteOptimizer.js, src/components/vwo/tests/__snapshots__/VisualWebsiteOptimizer.test.js.snap
- Instead of the Synchronous script, we needed to include the so called, "smart script" from VWO
- Load the page (in prod) and check that `window._vwo_settings_timer` is set
=> FE-834: Use the "Smart Script" from VWO

src/actions/blacklist.js, src/actions/tests/blacklist.test.js, src/components/collection/Collection.js, src/components/collection/tests/Collection.test.js, src/pages/blacklist/IncidentsPage.js, src/pages/blacklist/components/IncidentsCollection.js, src/pages/blacklist/components/IncidentsCollection.module.scss, src/pages/blacklist/components/tests/IncidentsCollection.test.js, src/pages/blacklist/tests/IncidentsPage.test.js
- Added datepicker to incidents page
- Updated Collection to allow for am empty page component when there are no rows.
- Updated Incidents page to hold the date options as state.
- Updated the dispatched action to use the from and to dates from the datepicker.
- Go to /blacklist/incidents. Verify that the date picker is working.
=> SA-1135 - Add Datepicker to Incidents Page.

cypress/fixtures/recipient-validation/list/400.get.usage-limit-exceeded.json, cypress/fixtures/recipient-validation/single/400.get.usage-limit-exceeded.json, cypress/tests/integration/recipient-validation/tr-2130.spec.js, src/pages/recipientValidation/RecipientValidationPage.js, src/pages/recipientValidation/SingleResult.js, src/pages/recipientValidation/UploadedListPage.js, src/pages/recipientValidation/components/JobStatusTag.js, src/pages/recipientValidation/components/JobStatusTag.module.scss, src/pages/recipientValidation/components/JobsTableCollection.js, src/pages/recipientValidation/components/ListProgress.js, src/pages/recipientValidation/components/tests/ListProgress.test.js, src/pages/recipientValidation/components/tests/__snapshots__/JobStatusTag.test.js.snap, src/pages/recipientValidation/components/tests/__snapshots__/ListProgress.test.js.snap, src/pages/recipientValidation/tests/SingleResult.test.js
[TR-2130](https://jira.int.messagesystems.com/browse/TR-2130)
- Fixes icon alignment issue on RV pages within status tags - *not really related to this ticket, but it was bothering me and won't impact other features*
- Reformats a few files with Prettier
- Adds error handling for "Usage limit exceeded" error that will return a `400` status code
- Adds Cypress integration tests to handle "Usage limit exceeded" states for both the single validation and list progress pages
- These changes are in support of upcoming API changes here: https://github.com/SparkPost/recipient-verification/pull/422
- The backend team initially deployed these changes to staging, but they caused some issue with the list progress page, so were rolled back. Though the above PR is marked as merged, we are going to …
=> TR-2130 - Adds handling for "Usage limit exceeded" error state for the Recipient Validation feature

src/pages/recipientValidation/SingleResult.js, src/pages/recipientValidation/tests/SingleResult.test.js
[TR-2139](https://jira.int.messagesystems.com/browse/TR-2139)
- Adds `data-id` prop to the `<WhiteText/>` component
- Adds test that checks for expected rendering
- Removes truthiness conditional that was inappropriately rendering portions of the UI as empty
- Go to `/recipient-validation/single/hello@me.com` and verify that `"is_disposable"` has a value of `false` instead of nothing
- Go to `/recipient-validation/single/nick.lemmon@gmail.com` and verify that `"is_disposable"` and `"is_role"` render as `false` instead of blank
- Go to `/recipient-validation/single/me@nicklemmon.com` and verify that `"is_role"` and `"is_disposable"` and `"is_free"` all have a value of `false`
- Go to `/recipient-validation/single/hello@gm` and verify that `"valid"` has a value of `false`
=> TR-2139 - Address rendering problem with empty values in the RV single validation raw API response

cypress/tests/integration/accounts/onboarding/billing-plan-page.spec.js, src/components/globalAlert/Animator.module.scss
[FE-838](https://jira.int.messagesystems.com/browse/FE-838)
**NOTE:** - I did not add any automated testing to check for this change in this PR. Future Cypress tests will end up testing this behavior "naturally" without having to introduce a test with a 15 second `cy.wait()`
- Updated global alert animation styles to use `visibility` CSS property
- Adds some `cy.wait()` to two tests that have proven to be somewhat flaky in the pipeline (no flake locally! I would assume due to a hardware difference between the runner and our Macs)
1. Go to `/templates`
1. Find a random template, click the trash can icon
1. Confirm the modal and verify that the alert animates in as usual
1. Confirm that the modal animates out as usual as well
=> FE-838 - Update styles to properly hide global alerts from screen readers and Cypress tests

src/config/default.js, src/helpers/date.js, src/helpers/tests/date.test.js, src/pages/reports/messageEvents/MessageEventsPage.js, src/selectors/messageEvents.js, src/selectors/tests/__snapshots__/messageEvents.test.js.snap
- Added a new config for `dateFormatWithoutYear`
- Added new date formatter function `formatDateTimeWithoutYear`
- Use this new formatter on the messageEvents selector (but only for the events list, not the CSV)
- Open /reports/message-events
- Move to the next page so dates show up
- Ensure there is no year on the dates
=> SE-485 Remove Year from Events Page Date

src/hooks/useABTest/hash.js, src/hooks/useABTest/hash.test.js, src/hooks/useABTest/index.js, src/hooks/useABTest/useABTest.js, src/hooks/useABTest/useABTest.test.js
- Added a hook to get a specific variant of an experiment AB Test based on UID
- Ensure tests are passing and are good enough coverage
- Determine if we should import the redux store in the hook so that we don't need to pass the customer_id from every use of this hook.
=> FE-727 Add useABTest hook

src/helpers/billing.js
Refer to [AC-1214](https://jira.int.messagesystems.com/browse/AC-1214)
- When upgrading an account from free to paid in the new billing form, plan_id should be set for the /cors-data request
In devtools network tab, confirm `plan_id` is set for the /cors-data request when...
- Creating a new account from onboarding plan selector
- Transitioning a manually billed account to self service
- Upgrading from free to paid in new billing form
- Upgrading from free to paid in old billing form
=> AC-1214: New billing form should pass plan_id to POST /billing/cors-data

src/actions/billing.js
[AC-1217] Unable to change plan when Use Another Credit Card is clicked and another credit card is used
- Fix when upgrading your paid account with a new credit card
- Create a paid account
- Navigate to /account/billing/plan page
- Upgrade your account and use a new credit card
- Click "Change Plan"
Expect, billing summary to update with new plan
=> [AC-1217] Unable to change plan when Use Another Credit Card is clicked and another credit card is used

src/pages/billing/constants.js
- Updated modal to compare plan tiers to have events be check marks
- Navigate to `/account/billing/plan`
- Click on "Compare Features` and find feature `Searchable Email Event Data`
- All columns should be check marks
=> SE-517: Update billing plan table for events

src/pages/reports/messageEvents/MessageEventsPage.js, src/pages/reports/messageEvents/MessageEventsPage.module.scss, src/pages/reports/messageEvents/tests/__snapshots__/MessageEventsPage.test.js.snap
- Fixed word wrapping on columns Event and Time column
- Navigate to events table and decrease viewport to where words wrap
-Event and time columns shouldn't cut split characters in middle of word
=> SE-518: Fixed word wrapping on events table

src/components/billing/CreditCardSection.js, src/pages/billing/components/CardSection.js, src/pages/billing/forms/NewChangePlanForm.js
Fix for TypeError: Cannot read property 'securityCode' of undefined
- Added a default state to CreditCard Section.
- Navigate to /account/billing/plan.
1. Select a new Plan.
2. Click on Use Another Credit Card. Click on a field.
3. Click Change.
4. Select Another Plan.
5. Submit the form. Check you see the above error in console.
=> AC-1221 - Fix for TypeError: Cannot read property 'securityCode' of undefined

src/components/datePicker/DatePicker.js, src/components/datePicker/tests/DatePicker.test.js, src/components/datePicker/tests/__snapshots__/DatePicker.test.js.snap, src/pages/inboxPlacement/TestListPage.js
- Disabled Date Picker submit button when only selected one date.
- Go to signals page. Open date picker and select only 1 date. You should not be able to submit the change.
- Check other date pickers to make sure nothing else breaks. Especially for inbox placement trends since it also uses validation
- This isn't quite the same as the AC but this was the most painless way to fix the bug.
=> SA-1093: Prevent submitting date picker update with only 1 date selected

cypress/fixtures/authenticate/grants/200.get.admin.json, src/__testHelpers__/http-responses/default/v1/authenticate/grants/get.js, src/config/navItems/index.js, src/config/routes/index.js, src/pages/recipientValidation/RecipientValidationPage.js, src/pages/recipientValidation/components/SingleAddressForm.js, src/pages/recipientValidation/components/SingleAddressForm.module.scss, src/pages/recipientValidation/tests/RecipientValidationPage.test.js
AC-1126: Add Payment Functionality Recipient Validation - Single Address Tab
- Feature Flag to hide this new flow/page.(_standalone_rv_)
- (UX-Change - Show the Add Credit Card Form with the validate button instead of Add Payment method button and the modal.)
- Once CC is added the details of the entered CC shows up along with validate button.
- If the user already has a CC on file then CC details show up along with validate button.
- Create an account and enable 'standalone_rv' flag.
- Navigate to /recipient-validation/single.
- Check if it works as described above.
=> AC-1126: Add Payment Functionality Recipient Validation - Single Address Tab

src/helpers/chart.js, src/helpers/metrics.js, src/helpers/tests/chart.test.js, src/helpers/tests/metrics.test.js, src/pages/reports/summary/SummaryPage.js, src/pages/reports/summary/components/ChartGroup.js, src/pages/reports/summary/tests/__snapshots__/SummaryPage.test.js.snap
- Added Options for month and week labels for the tooltip.
- Added Monthly display for the x-axis ticks.
- Go to /reports/summary. Change the date ranges to see hourly, <hourly, daily, weekly, and monthly precision.
=> SA-953 - Add Week and Month precision labels for Metrics Summary Chart

src/pages/recipientValidation/RecipientValidationPage.js, src/pages/recipientValidation/RecipientValidationPage.module.scss, src/pages/recipientValidation/components/ApiDetails.js, src/pages/recipientValidation/components/ValidateSection.js, src/pages/recipientValidation/tests/RecipientValidationPage.test.js
AC-1125 -  Add Payment Functionality Recipient Validation -  API Integration Tab
-  Show the Add Credit Card Form with the Create API key button in API Integration Tab.
- Enable 'standalone_rv' flag.
- Navigate to /recipient-validation/api
- Check if it matches mocks, expect the Update Payment Method Button(Changed after discussion with Haley.)
=> AC-1125 -  Add Payment Functionality Recipient Validation -  API Integration Tab

src/pages/blacklist/components/StopMonitoringModal.js, src/pages/blacklist/components/tests/StopMonitoringModal.test.js
- When clicking "Stop Monitoring" on a resource, the modal text will dynamically change based on if it is a sending domain or IP address.
- Click "Stop Monitoring" on a sending domain, check text is correct
- Click "Stop Monitoring" on an IP address, check text is correct
=> SA-1203 Dynamically change stop monitoring modal text based on resource

src/selectors/currentUser.js, src/selectors/signals.js, src/selectors/tests/signals.test.js
-Selects the correct health score data for subaccount reporting user.
- Create suabccount Reporting user in an account w/ signals data
- Go to `/signals/health-score`. Verify that the health score dashboard contains data calculated for that subaccount only.
=> SA-1196: Health Score display for subaccount reporting users

cypress/tests/integration/accounts/change-billingplan-page.spec.js, src/actions/billing.js, src/pages/billing/context/ChangePlanContext.js
- Billing page hits the billing endpoint with query param for type=messaging
- Go to `/account/billing/plan/`
- Check that network request is made for `/billing/bundles?type=messaging`
=> AC-1212: Added type query param to bundles endpoint

src/components/pendo/Pendo.js, src/components/pendo/tests/Pendo.test.js, src/components/pendo/tests/__snapshots__/Pendo.test.js.snap
- Added status and status reason to pendo account information
- Create a new account
- Terminate account through account control endpoint
- Login to the account
- In console, use command `pendo.enableDebugger();`
- Using debugger, check that account information was sent to pendo
=> FE-850: Added account status and status reason to pendo

src/helpers/billing.js
- Spaces are removed from card number before pulling first 6 characters
- Create a new account
- Select a paid plan and keep an eye on the network requests
- Check that in the /cors-data request, the bin includes 6 characters with no spaces
You can also check master branch to see that spaces were previously being sent.
=> AC-1235: Biling uploads first 6 digits of card for bin number

src/pages/alerts/components/AlertDetails.js
- Blacklist alerts will not rendered "Filtered By parts if 
- Create a blacklist alert (available on appteam account)
- Create alert with no filters no filters, or only filters on one of blacklist provider or blacklist resources
=> SE-531: Fix filtered by message for blacklist alerts

src/actions/addRVtoSubscription.js, src/actions/billing.js, src/actions/tests/addRVtoSubscription.test.js, src/components/billing/CreditCardSection.js, src/config/routes/index.js, src/helpers/billing.js, src/pages/index.js, src/pages/recipientValidation/RecipientValidationPage.container.js, src/pages/recipientValidation/RecipientValidationPage.js, src/pages/recipientValidation/UploadedListPage.container.js, src/pages/recipientValidation/UploadedListPage.js, src/pages/recipientValidation/components/ApiDetails.js, src/pages/recipientValidation/components/ListForm.js, src/pages/recipientValidation/components/SingleAddressForm.js, src/pages/recipientValidation/components/ValidateSection.js, src/pages/recipientValidation/components/tests/ApiDetails.test.js, src/pages/recipientValidation/components/tests/__snapshots__/SingleAddressForm.test.js.snap, src/pages/recipientValidation/tests/RecipientValidationPage.test.js, src/pages/recipientValidation/tests/UploadedListPage.test.js, src/selectors/accountBillingInfo.js, src/selectors/recipientValidation.js
AC-1196: "Validate" button on RV list & single views subscribes to RV bundle
- "Validate" button on the list and single RV tabs checks if there is a Zuora account
* If there is no Zuora account, create an account and add the RV bundle to the subscription
* If there is a Zuora account, check if RV is on the subscription. If not, add the RV bundle to the subscription.
* When RV bundle is successfully added to the subscription, process the RVs.
- Enable ui flag `standalone_rv`
- Navigate to the list tab and single validation tab on RecipientValidationPage. (mostly you will see errors since backend is still in progress.)
- Check the logic of addRVtoSubscription
=> AC-1196: "Validate" button on RV list & single views subscribes to RV bundle

cypress/fixtures/templates/stubbed-template-1/200.get.content-null-values.json, cypress/tests/integration/templates/editDraftPage.spec.js, src/selectors/templates.js, src/selectors/tests/templates.test.js
[TR-2221](https://jira.int.messagesystems.com/browse/TR-2221)
- Adds unit test cases for the templates selector
- Adds Cypress test to check for exception
- Resolves bug by filtering out falsy values from the `template.content` object received from a request
- Run Cypress integration tests locally - `npm run test-integration`
- Comment out line 41 of `src/selectors/templates.js`
- Run the `editDraftPage.spec.js` tests in Cypress and see the test fail due to the uncaught exception
- Re-introduce line 41 of `src/selectors/templates.js`
- Run the `editDraftPage.spec.js` tests in Cypress again and see everything pass
=> TR-2221 - Filter out falsy values from the templates content object

.travis.yml, config/cypressBatches.js, cypress/tests/integration/alerts/detailsPage.spec.js, package.json, scripts/cypressIntegration.js
[FE-858](https://jira.int.messagesystems.com/browse/FE-858)
- Properly passes spec batch keys to the Cypress integration test script
- Adds additional edge case handling to the Cypress integration test script
- Manually exits the Cypress node process when encountering an error based on the number of failed tests being > 0
- Fixed failing test in alerts details page
- Verify that builds from prior commits failed when a test failed: https://travis-ci.org/SparkPost/2web2ui/builds/653200064?utm_source=github_status&utm_medium=notification
- Verify integration tests are properly split - they were being run simultaneously by multiple runners!
=> FE-858 - Adding promise resolution to Cypress run

cypress/tests/integration/recipients/recipient-validation/list-page-routes/listRoute.spec.js, src/constants/index.js, src/pages/recipientValidation/UploadedListPage.js, src/pages/recipientValidation/tests/UploadedListPage.test.js
AC-1270-  Fixing Error when adding credit card on RV lists
- What changes did you make to satisfy the AC?
- Renamed the UploadedListForm to FORMS.RV_ADDPAYMENTFORM_UPLOADLISTPAGE
- Added billing loading condition and removed the pristine check for submitDisabled.
- Sign up (on free bundle)
- Enable account option ui.standalone_rv
- Refresh the UI.
- View new RV page, upload a list. Do not add credit card yet.
- Select "Back" to go to /recipient-validation/list
- Select the action "Review" on the uploaded list
- Check the "State" field without selecting a country. You should see a default state (Alabama).
- Attempt to add credit card and "Validate."
=>  AC-1270-  Fixing Error when adding credit card on RV lists

src/components/reduxFormWrappers/tests/__snapshots__/ComboBoxTypeaheadWrapper.test.js.snap, src/components/typeahead/ComboBoxTypeahead.js, src/components/typeahead/tests/ComboBoxTypeahead.test.js, src/pages/alerts/components/AlertForm.js, src/pages/alerts/components/fields/FilterFields.js, src/pages/alerts/components/fields/SubaccountsField.js, src/pages/alerts/components/fields/tests/FilterFields.test.js, src/pages/alerts/components/fields/tests/SubaccountsField.test.js, src/pages/alerts/components/fields/tests/__snapshots__/SubaccountsField.test.js.snap, src/pages/alerts/components/tests/__snapshots__/AlertForm.test.js.snap
- Updated ComboboxTypeahead to use redux-form initial values.
- Removed the the selectedMap prop and isExclusiveItem check.
- Added isExclusiveItem function prop.
- ComboboxTypeahead only accepts strings, not objects.
- Check that the comboboxs in alerts works correctly.
- Run Cypress tests to verify.
=> FE-853 Fix ComboBoxTypeahead to use redux-form initalValues.

src/actions/addRVtoSubscription.js, src/actions/tests/addRVtoSubscription.test.js, src/pages/recipientValidation/RecipientValidationPage.js, src/pages/recipientValidation/UploadedListPage.js, src/pages/recipientValidation/components/ValidateSection.js, src/pages/recipientValidation/tests/UploadedListPage.test.js, src/reducers/addRVtoSubscription.js, src/reducers/index.js
AC-1238: Update the Recipient Validation Page for manually billed customers
- Update the RV page for manually billed customers who have rv on their subscription. 
-Do not show the Credit Card Section
-Show the Validate and Create API key buttons.
-Added loading state for UploadedListPage and RecipientValidationPage as discussed on [uxfe](https://msys.slack.com/archives/GLLAW6UAX/p1582658131001000)
- Enable 'standalone_rv' ui flag.
- Create a manually billed account using https://github.com/SparkPost/sparkpost-admin-api- 
documentation/blob/master/services/billing_api.md#create-a-manually-billed-account-post .
- Add rv to user subscription (use PUT /billing/subscription/bundle)
=> AC-1238: Update the Recipient Validation Page for manually billed customers

src/config/navItems/account.js, src/config/routes/index.js, src/pages/dataPrivacy/DataPrivacyPage.js
- Added page as `/account/data-privacy`
- Enable UI flag `data_privacy`
- Check that top right dropdown includes link for `Data and Privacy`
=> AC-1263: Add data privacy page

cypress/tests/integration/events/listPage.spec.js, src/helpers/tests/validation.test.js, src/helpers/validation.js, src/pages/billing/helpers/tests/totalRecipientValidationCost.test.js, src/pages/reports/messageEvents/components/AdvancedFiltersModal.js, src/pages/reports/messageEvents/components/SearchForm.js, src/pages/reports/messageEvents/helpers/transformData.js
- Message events, add filters
- Now has default 3 filter categories + 1 empty select
- Validation now only checks for typed fields. Empty field (regardless of select) will be removed
- Default filters do not appear if other filters modify the select
- Navigate to `/message-events`
- Go to "Add Filters"
- Verify that the bottom section defaults to multiple filters.
- Add any filter (preferably just 1) and save
- Reopen modal
- Verify that the defaults do not show up
- Verify that the validation does not pop up on empty text input fields
=> SE-566: Added default filters

src/App.js, src/components/hibana/HibanaComponents.module.scss, src/components/layout/Layout.js, src/components/layout/tests/__snapshots__/Layout.test.js.snap
[FE-830](https://jira.int.messagesystems.com/browse/FE-830) Follow Up
- Uses `position: sticky` to position the Hibana banner
- Moves the Hibana banner component to a different portion of the app
- Verify that the Hibana banner scrolls with the window when scrolling through page
- Verify that the Hibana banner does not cover page content at the bottom of the page.
=> FE-830-4 - Use position sticky for Hibana banner

src/components/matchbox/Inline.js, src/components/matchbox/README.md, src/components/matchbox/index.js, src/components/matchbox/tests/Inline.test.js
[FE-875](https://jira.int.messagesystems.com/browse/FE-875)
- Adds `<Inline/>` component wrapper from Matchbox
- Adds Matchbox component wrapper README based on UX/FE sync discussion
1. Go to any page and add the following (I did it with `DashboardPage.js`):
```js
<Inline>
<h3>Hello!</h3>
<h3>Hello!</h3>
<h3>Hello!</h3>
</Inline>
```
2. Toggle between the Hibana and non-Hibana versions of the app - verify that the styles from Matchbox apply (everything should line up in a row!)
=> FE-875 - Component wrapper for Matchbox Inline component

src/config/navItems/account.js, src/config/routes/index.js, src/pages/dataPrivacy/DataPrivacyPage.js, src/pages/dataPrivacy/DataPrivacyPage.module.scss, src/pages/dataPrivacy/components/ApiDetailsTab.js, src/pages/dataPrivacy/components/ApiDetailsTab.module.scss, src/pages/dataPrivacy/components/tests/ApiDetailsTab.test.js, src/pages/dataPrivacy/tests/DataPrivacyPage.test.js
AC-1266 - Added API Integration tab
- Added API Integration tab
- Link is included for the sparkpost documentation
- Button links to the API key create page
- Enable account ui option - data_privacy
- Navigate to /account/data-privacy
- Check if it matches the mocks https://sparkpost.invisionapp.com/share/BCVKAJRH4E9#/screens/404037210
=> AC-1266 - Added API Integration tab

src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/ShowMeSparkpostStep.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/dashboard/components/tests/ShowMeSparkpostStep.test.js, src/pages/dashboard/constants.js
AC-1182 "Check out Events" item in "Show Me SparkPost" list (UI)
- Added "Check Out Events" Item in Show Me Sparkpost list.
- Events guide show up when navigating to events page (https://sparkpost.invisionapp.com/share/DHULLYL45GB#/screens/390961100) [Note - use http://app.sparkpost.test:3100 to see the guide] 
On Dashboard, 
- Click Show Me SparkPost in Getting Started Guide
-  Check if the Check Out Events List Item matches mocks
-  click on the button and see if you see the guide on events page
-  after navigation the check should be stored  and item should be completed (shows a green tick)
=> AC-1182 "Check out Events" item in "Show Me SparkPost" list (UI)

cypress/tests/integration/navigation/navigation.spec.js, src/components/navigation/components/AccountDropdown.js, src/components/navigation/components/AccountDropdown.module.scss, src/components/navigation/components/Top.js, src/components/navigation/components/Top.module.scss, src/components/navigation/components/tests/AccountDropdown.test.js, src/components/navigation/components/tests/__snapshots__/AccountDropdown.test.js.snap, src/components/navigation/components/tests/__snapshots__/Top.test.js.snap, src/config/navItems/account.js
- Added link to change plan page in the top nav for free users.
- Added upgrade label to the billing section of the account nav dropdown.
- Login to a free user account (or create a new acount).
- Check that there is a upgrade plan link on the top nav in orange. 
- Check that there is an upgrade label in the account dropdown.
- Login as a paid user. Check that the above do no appear for the paid user.
=> FE-848 Add upgrade plan button for free users.

src/actions/inboxPlacement.js, src/actions/tests/inboxPlacement.test.js
- Added a helper function that dispatches a thunk that switches out the inbox placement url based on a user UI flag. 
- Updated tests to match the changes.
- Removed the async await in the tests. 
- Create new user or login to a user under appteam account.
- Add the user ui 'use_inbox_placement_ea' flag through the /users/{username}/control endpoint. 
- Go to any inbox placement route in the UI. Check that the api calls use `/v1/inbox-placement-ea`
=> SA-1249: Add option to use inbox-placement-ea endpoint with user flag

src/components/collection/FilterSortCollection.js, src/components/datePicker/DatePicker.js, src/components/matchbox/Select.js, src/components/matchbox/index.js, src/components/matchbox/tests/Select.test.js, src/components/reduxFormWrappers/SelectWrapper.js, src/pages/inboxPlacement/components/TestDetails.js, src/pages/reports/messageEvents/components/SearchQuery.js, src/pages/reports/messageEvents/components/tests/__snapshots__/SearchQuery.test.js.snap, src/pages/reports/summary/components/GroupByOption.js, src/pages/sendingDomains/components/BounceSetupInstructionPanel.js, src/pages/signals/components/IntegrationPageFilter.js, src/pages/signals/components/filters/FacetFilter.js, src/pages/signals/components/filters/tests/DateFilter.test.js, src/pages/signals/tests/IntegrationPage.test.js
FE-886 - Component wrapper for Matchbox Select
- Select has a single, globally accessible point of entry within the app
- Select is only imported from Matchbox in one place - replaced all instances of the Select directly imported from matchbox with this new global component
- New props available to the Hibana version of the component are exposed - and subsequently ignored by the original component (https://jira.int.messagesystems.com/browse/FE-816)
- Ensure no unusual positioning UI defects are introduced as a result of this change - both for when using Hibana and when using the default theme
- enable hibana ui flag 
`{
"options": {
"ui":{
"hibana":{
"hasThemeControls": true
}
}
}
}`
- Check all instances of Select for ui defects with and without hibana enabled
=> FE-886 - Component wrapper for Matchbox Select

src/__func__/signup/__snapshots__/join.test.js.snap, src/__func__/signup/__snapshots__/joinEmailOptIn.test.js.snap, src/pages/join/JoinPage.js, src/pages/join/tests/__snapshots__/JoinPage.test.js.snap
AC-1299 -  (UI) Join page should submit email_opt_in flag in creation_params to POST /account
- Added email_opt_in flag in creation_params to POST /account
- Create a account and check if email_out_in flag is sent in the body for POST /account
=> AC-1299 -  (UI) Join page should submit email_opt_in flag in creation_params to POST /account

cypress/fixtures/account/200.get.json, cypress/fixtures/data-privacy/200.post.json, cypress/fixtures/data-privacy/400.post.json, cypress/tests/integration/accounts/data-privacy/SingleRecipientPage.spec.js, src/actions/dataPrivacy.js, src/actions/tests/dataPrivacy.test.js, src/components/subaccountSection/SubaccountSection.js, src/components/subaccountSection/__snapshots__/SubaccountSection.test.js.snap, src/pages/dataPrivacy/DataPrivacyPage.js, src/pages/dataPrivacy/components/SingleRecipientTab.js, src/pages/dataPrivacy/components/SingleRecipientTab.module.scss, src/pages/dataPrivacy/components/tests/SingleRecipientTab.test.js, src/pages/dataPrivacy/tests/DataPrivacyPage.test.js, src/pages/snippets/CreatePage.js, src/pages/snippets/EditPage.js, src/pages/snippets/tests/__snapshots__/EditPage.test.js.snap, src/pages/templates/components/create/CreateForm.js, src/pages/templates/components/settings/SettingsForm.js, src/reducers/dataPrivacy.js, src/reducers/index.js
AC-1264 - (UI) Single address tab
- Tab 1 for the single address form is created
- The form changes endpoints based on Right to Be forgotten or opting out
- Subaccount is assigned to header
- Cypress tests are added for Single Recipient Page
- Enable 'data_privacy' flag.
- Navigate to /account/data-privacy/single-recipient.
- Check if it matched mocks https://sparkpost.invisionapp.com/share/BCVKAJRH4E9#/screens/400849700
- Submit request for rtbf and Opt out check if requests are sent as doucmented - https://github.com/SparkPost/sparkpost-admin-api-documentation/pull/452/files
=> AC-1264 - (UI) Single address tab

package.json, src/components/collection/FilterSortCollection.js, src/components/collection/TableCollection.js, src/components/collection/TableHeader.js, src/components/collection/tests/FilterSortCollection.test.js, src/components/collection/tests/TableCollection.test.js, src/components/matchbox/Table.js, src/components/matchbox/index.js, src/components/matchbox/tests/Table.test.js, src/components/recipientValidation/RecipientValidationPriceTable.js, src/components/summaryTable/Billboard.js, src/components/summaryTable/Body.js, src/components/summaryTable/Head.js, src/components/summaryTable/SummaryTable.js, src/pages/alerts/components/AlertCollection.js, src/pages/alerts/components/AlertIncidents.js, src/pages/billing/components/FeatureComparisonModal.js, src/pages/billing/components/tests/__snapshots__/FeatureComparisonModal.test.js.snap, src/pages/blacklist/components/IncidentsCollection.js, src/pages/blacklist/components/RelatedIncidents.js, src/pages/inboxPlacement/TestListPage.js, src/pages/inboxPlacement/components/AllMessagesCollection.js, src/pages/inboxPlacement/components/PlacementBreakdown.js, src/pages/reports/messageEvents/components/TableElements.js, src/pages/sendingDomains/components/SimpleTable.js
FE-890 - Component Wrapper for Matchbox Table
- Created Table Wrapper component and added Cell, HeaderCell and Row to this export
- Replaced all instances of Table with Table Wrapper
- upgraded matchbox hibana version to 9
-  Check the table on /inbox-placement, /blacklist/incidents, all pages in content nav, events page, signal pages
=> FE-890 - Component Wrapper for Matchbox Table

cypress/tests/integration/signals-analytics/health-score/dashboardPage.spec.js, src/components/matchbox/Text.js, src/components/matchbox/index.js, src/components/matchbox/tests/Text.test.js
FE-893 - Component Wrapper for Matchbox Text
- Added Text component wrapper
1. Go to any page and add the following;
```js
<>
<Text as="p">
Paragraph
</Text>
<Text as="i">
Italic
</Text>
<Text as="u">
Underline
</Text>
</>
```
[ref -  [https://nostalgic-stonebraker-a9b0c1.netlify.com/?path=/story/text--example-of-tags]( https://nostalgic-stonebraker-a9b0c1.netlify.com/?path=/story/text--example-of-tags)]
=> FE-893 - Component Wrapper for Matchbox Text

src/components/contentEditor/ContentEditor.js, src/components/contentEditor/__snapshots__/ContentEditor.test.js.snap, src/components/matchbox/Tabs.js, src/components/matchbox/index.js, src/components/matchbox/tests/Tabs.test.js, src/components/support/Support.js, src/components/support/tests/__snapshots__/Support.test.js.snap, src/pages/dataPrivacy/DataPrivacyPage.js, src/pages/inboxPlacement/TestDetailsPage.js, src/pages/inboxPlacement/components/TestContent.js, src/pages/inboxPlacement/components/tests/TestContent.test.js, src/pages/inboxPlacement/components/tests/__snapshots__/TestContent.test.js.snap, src/pages/inboxPlacement/tests/__snapshots__/TestDetailsPage.test.js.snap, src/pages/recipientValidation/RecipientValidationPage.js, src/pages/recipientValidation/RecipientValidationPage.module.scss, src/pages/reports/bounce/BouncePage.js, src/pages/reports/bounce/tests/__snapshots__/BouncePage.test.js.snap, src/pages/signals/components/engagement/Tabs.js, src/pages/signals/components/engagement/tests/__snapshots__/Tabs.test.js.snap, src/pages/subaccounts/DetailsPage.js, src/pages/subaccounts/tests/__snapshots__/DetailsPage.test.js.snap, src/pages/suppressions/CreatePage.js, src/pages/suppressions/ListPage.js, src/pages/suppressions/tests/__snapshots__/CreatePage.test.js.snap, src/pages/suppressions/tests/__snapshots__/ListPage.test.js.snap, src/pages/templates/components/EditSection.js, src/pages/templates/components/tests/__snapshots__/EditSection.test.js.snap, src/pages/webhooks/DetailsPage.js, src/pages/webhooks/tests/__snapshots__/DetailsPage.test.js.snap
FE-891 - Component Wrapper for Matchbox Tabs
- Added Component Wrapper for Tabs
- Replaced all instances of Tabs
- Moved the Tabs for Support component inside Panel
- Upgraded matchbox hibana version to 9
-  Check the tabs on /recipient-validation/list, /lists/suppressions, /account/data-privacy/single-recipient, /reports/bounce
- the tabs in hibana, 
- have type="button" missing and that is why the recipientValidation forms are submitting when we switch tabs
- tabs have issue when wrapping words (white-space: nowrap is missing)
=> FE-891 - Component Wrapper for Matchbox Tabs

src/pages/dataPrivacy/DataPrivacyPage.js, src/pages/dataPrivacy/tests/DataPrivacyPage.test.js
- Reset added for swapping tabs on data privacy
- Go to /account/data-privacy
- Single tab, add an invalid email address
- Swap tabs
- Verify that multi error modal is not there
=> AC-1265: Fix for error handling on data privacy

src/actions/brightback.js, src/actions/reportOptions.js, src/helpers/metrics.js, src/helpers/reports.js, src/helpers/tests/metrics.test.js, src/reducers/reportOptions.js, src/reducers/tests/__snapshots__/reportOptions.test.js.snap, src/reducers/tests/reportOptions.test.js, src/selectors/reportSearchOptions.js, src/selectors/tests/__snapshots__/reportSearchOptions.test.js.snap, src/selectors/tests/reportSearchOptions.test.js
- Added timezone and precision URL params to the report URLs for sharing
- Open a report (/reports/summary as example)
- See that your local timezone (based on browser/system clock) is added to the query params
- See that precision (based on the to and from dates) is added to the query params
- See that metrics API requests send that timezone along with the request
- Change the timezone in the query params to UTC
- See that metrics API requests send that timezone along with the request
=> SA-1272 Add timezone and precision to report URLs

src/pages/alerts/components/AlertForm.container.js
FE-951 - Alert Create page breaks in Hibana theme
- Added `destroyOnUnmount: false` to AlertForm
- To replicate issues :
- Open /alerts/create
- Click "Take a Look" Hibana button
- Select "Health Score" metric
- Also Check out the following cases - https://msys.slack.com/archives/GKXTKHDSP/p1585325093014300
=> FE-951 - Alert Create page breaks in Hibana theme

src/helpers/conditions/account.js, src/helpers/conditions/tests/account.test.js, src/pages/users/CreatePage.js, src/pages/users/ListPage.js
- Switched feature toggle to use `isAccountUiOptionSet`
1. Create a new account
1. Click "Manage Users" link from account dropdown
1. Click "Invite User" button
1. _Confirm the "Assign to subaccount" checkbox is **not** displayed_
1. Enable "subaccount_reporting" UI feature flag
1. _Confirm the "Assign to subaccount" checkbox is **not** displayed_
1. Create a subaccount
1. _Confirm the "Assign to subaccount" checkbox is displayed_
1. Disable "subaccount_reporting" UI feature flag
1. _Confirm the "Assign to subaccount" checkbox is **not** displayed_
=> AC-1341: Subaccount_reporting UI option doesn't toggle off

codecov.yml, cypress/fixtures/utils/content-previewer/200.post.json, cypress/tests/integration/templates/editDraftPage.spec.js, src/pages/templates/components/PreviewFrame.js
- Set rel attribute on anchors in template preview
- Create a new template
- Set "HTML" content to `<a href="http://google.com">Click Here</a>`
- Confirm link rendered in the preview has "rel" attribute set and when clicked it opens a new tab
=> TR-2344: Links in template editor need noreferrer attribute

cypress/fixtures/account/200.get.json, src/components/subaccountSection/SubaccountSection.js, src/components/subaccountSection/__snapshots__/SubaccountSection.test.js.snap, src/config/navItems/account.js, src/config/routes/index.js, src/pages/dataPrivacy/components/MultipleRecipientsTab.js, src/pages/dataPrivacy/components/SingleRecipientTab.js
AC-1267 - Release UI for data privacy
- Removed ui flag data_privacy
- Added Data and Privacy Page to hibana nav
- Replaced title with label in SubaccountSection, MultipleRecipientsTab, SingleRecipientsTab
- Check if Data and Privacy page is visible without enabling feature flag.(only to admin users)
- Check if SubaccountSection used in templates, snippets and Data Privacy page looks the same after the replacement of title with label.
- Check if the Data and Privacy Page is visible under Hibana Nav.
=> AC-1267 - Release UI for data privacy

src/__func__/signup/helpers.js, src/components/pendo/Pendo.js, src/components/pendo/tests/Pendo.test.js, src/components/pendo/tests/__snapshots__/Pendo.test.js.snap, src/pages/join/components/JoinForm.js, src/pages/join/components/tests/__snapshots__/JoinForm.test.js.snap
- Added company name field
- Added field view password field
- Create account
- Verify that show password works correctly
-Add company name
- Verify company name exists on the account information on logging in the app (network request)
=> AC-1289: Added company name field and show password on join page

src/components/typeahead/TimezoneTypeahead.js, src/components/typeahead/tests/TimezoneTypeahead.test.js, src/pages/reports/components/ReportOptions.js, src/pages/reports/components/tests/ReportOptions.test.js
- Disabled datepicker when day, week, month precision is locally set in state to show that the date range choice will change their timezone.
- Set Hour precision and timezone to something other than UTC. Then choose a date range out of the window of hourly precision (15 days, etc.). Before clicking apply, see the timezone picker is disabled and set to UTC. If you choose another within the window of hourly precision, the timezone will revert back and be enabled.
- The reverse is a little harder to test/see, but if you have a day precision set, open date picker and click on a day. Then hover over the same day (precision will change to 15 mins), and the timezone picker will re-enable itself (but with UTC still chosen, because that's the last timezone that was picked).
=> SA-1306 Disable the Timezone picker when datepicker changes local precision to day, week, month

src/Providers.js, src/config/routes/index.js
- Moved HibanaProvider and HibanaTheme above ErrorBoundary
- Added two new routes /error-boundary and /private-error-boundary for testing ErrorBoundary's
- Open /error-boundary to confirm app error boundary renders EmptyState without error
=> FE-1015: Error: useHibanaState must be used within a HibanaProvide

src/pages/passwordReset/ResetPasswordPage.js, src/pages/passwordReset/tests/ResetPasswordPage.test.js
AC-1020: (UI) Delete password reset tokens after successful reset
- added the logout api call after reset password.
- updated test for ResetPasswordPage
- Reset password using reset link sent in email.
- Check if logout api is called after reset api.
- Check if the token can be used again.
- Check if the Profile Page update password works same as before ( without forced logout )
=> AC-1020: (UI) Delete password reset tokens after successful reset

src/components/callout/Callout.js, src/components/charts/Legend.js, src/components/charts/Tooltip.js, src/components/charts/TooltipHibana.module.scss, src/components/charts/TooltipMetric.js, src/components/charts/tests/Legend.test.js, src/components/charts/tests/Tooltip.test.js, src/components/charts/tests/TooltipMetric.test.js, src/components/charts/tests/__snapshots__/Legend.test.js.snap, src/pages/inboxPlacement/components/TrendsChart.js, src/pages/signals/ComplaintsByCohortPage.js, src/pages/signals/EngagementRateByCohortPage.js, src/pages/signals/EngagementRecencyPage.js, src/pages/signals/SpamTrapPage.js, src/pages/signals/tests/__snapshots__/ComplaintsByCohortPage.test.js.snap, src/pages/signals/tests/__snapshots__/EngagementRateByCohortPage.test.js.snap, src/pages/signals/tests/__snapshots__/EngagementRecencyPage.test.js.snap, src/pages/signals/tests/__snapshots__/SpamTrapPage.test.js.snap
FE-929: Re-style global chart component
- Added Hibana style for TooltipMetric
- Added Hibana style for Tooltip
- Update `<Legend/>`
**Note**  - `BarChart` doesn't seem to need any update
- point to prd and Check the charts in 108 account.
- Check Bar Chart, Tooltip, Legend 
- /signals/engagement/cohorts/sid/0
- /inbox-placement
=> FE-929: Re-style global chart component

src/pages/billing/SummaryPage.js, src/pages/billing/components/BillingSummary.js, src/pages/billing/components/tests/__snapshots__/BillingSummary.test.js.snap
- RV usage was not showing up in billing summary, removed condition check for old account option
- Create account, and go `/account/billing`, no usage for RV should show up.
- Add RV, validate a few addresses, and then go back to billing. RV should show up (might be slightly delayed on updating usage).
=> AC-1398: Removed summary condition for RV

src/components/typeahead/ComboBoxTypeahead.js, src/components/typeahead/tests/ComboBoxTypeahead.test.js, src/constants/index.js, src/pages/alerts/components/fields/FilterFields.js
- Disabled Pendo tooltip
- Added help text to mailbox provider
- Open create alert page, /alerts/create
- Select "Block Bounce Rate" from "Alert Metric" dropdown
- Confirm Pendo tooltip is gone and help text is present
=> SE-620: Replace Alert Mailbox Provider tooltip in Pendo with code (UI)

package-lock.json, package.json, src/components/grantBoxes/GrantsCheckboxes.js, src/components/grantBoxes/GrantsCheckboxes.module.scss, src/components/grantBoxes/tests/__snapshots__/GrantsCheckboxes.test.js.snap, src/components/matchbox/Button.js, src/pages/api-keys/components/ApiKeyForm.js, src/pages/api-keys/components/tests/__snapshots__/ApiKeyForm.test.js.snap, src/pages/trackingDomains/components/CreateForm.js, src/pages/trackingDomains/components/TrackingDomainRow.js, src/pages/trackingDomains/components/UnverifiedBanner.js, src/pages/trackingDomains/components/tests/__snapshots__/CreateForm.test.js.snap, src/pages/trackingDomains/components/tests/__snapshots__/TrackingDomainRow.test.js.snap, src/pages/trackingDomains/components/tests/__snapshots__/UnverifiedBanner.test.js.snap
- Tracking domains pages (List, create)
- API keys pages (LIst, create/edit, view)
- Navigate to all these routes:
- /account/api-keys
- /account/api-keys/create
- /account/api-keys/edit/:id
- /account/api-keys/view/:id
- /account/tracking-domains
- /account/tracking-domains/create
- Check that all the pages visually look correct
=> FE-964: Updated API keys and tracking domains pages

src/pages/billing/components/Banners.js, src/pages/billing/components/tests/__snapshots__/Banners.test.js.snap
[FE-968-2] Fix for Banner pending plan change
- Fixed the maxWidth value for pending plan change banner
- Check the Pending Plan Banner on billing page(after Downgrading plan)
=> [FE-968-2] Fix for Banner pending plan change

cypress/fixtures/billing/bundles/200.get.json, cypress/fixtures/billing/plans/200.get.json, cypress/fixtures/billing/subscription/200.get.starter-plan-higher-subaccounts-limitoverride.json, cypress/fixtures/billing/subscription/200.get.test-plan-with-subaccounts.json, cypress/fixtures/billing/subscription/bundle/200.put.json, cypress/tests/integration/accounts/billing/changeBillingPlanPage.spec.js, src/pages/billing/components/FeatureChangeSection.js, src/pages/billing/components/SubmitSection.js, src/pages/billing/components/tests/FeatureChangeSection.test.js, src/pages/billing/context/FeatureChangeContext.js, src/pages/billing/context/tests/FeatureChangeContext.test.js, src/pages/billing/context/tests/__snapshots__/FeatureChangeContext.test.js.snap
AC-1446 - Show the Subaccounts Section while changing plans
**Note** We had implemented this functionality earlier but removed it as api did not support limits
- Added the functionality to bring back the subaccounts section when a user changes plan
- Shows a warning to user and prevents them from changing plan if the current quantity of subaccounts is over the limit of the plan that they have selected
- if the current Limit is more than the future limit than than shows up as plain text **without** "Update account" button
- Run the following cypress tests to see how this functions as the api as still not returning limits
- Upgrades free account to premier 1M with previous active subaccounts, current quantity of subaccounts doesn't exceed new limit
- Upgrades free account to starter 100K …
=> AC-1446 - Show the Subaccounts Section while changing plans

cypress/fixtures/zuora/payment-method/credit-cards/200.post.with-error.json, cypress/fixtures/zuora/payment-method/credit-cards/400.post.json, cypress/tests/integration/accounts/billing/billingPage.spec.js, src/actions/helpers/tests/__snapshots__/zuoraRequest.test.js.snap, src/actions/helpers/tests/zuoraApiError.test.js, src/actions/helpers/tests/zuoraRequest.test.js, src/actions/helpers/zuoraApiError.js, src/actions/helpers/zuoraRequest.js, src/helpers/errorTracker.js, src/helpers/tests/errorTracker.test.js, src/pages/billing/forms/UpdatePaymentForm.js
AC-1413: (UI) Report all Zuora API errors with error code
- Added ZuoraErrorCode in tags, when zuora request fails with response status 200
- Added Error reporting to sentry when zuora errors out with 4xx or 5xx.
- Added cypress tests to test the following
- run the cypress tests that are added in this PR and open the network tab and check the sentry request (even though the sentry requests have failed, you should still be able to check Request Payload)
=> AC-1413: (UI) Report all Zuora API errors with error code

src/reducers/inboxPlacement.js, src/reducers/tests/__snapshots__/inboxPlacement.test.js.snap
SA-1417 -  Inbox Placement list page crashes when user's session expires and logs in again
- getTrendsFilterValuesError should be a string; TypeAhead expects a string
- Login and open the network tab to get the token sent by authenticate. Copy that token.
- Navigate to inbox-placement page
- Use postman and using POST /authenticate/logout invalidate the token
- Now on inbox-placement page, change the date range filter to something else; this should trigger a logout. Watchout for two error alerts meaning message-filter api and inbox-placement api must have thrown 401.
- Now login again, you should have landed on inbox-placement page without it crashing.
=> SA-1417 -  Inbox Placement list page crashes when user's session expires and logs in again

src/pages/ipPools/EditPage.js, src/pages/ipPools/ListPage.js, src/pages/ipPools/tests/ListPage.test.js, src/pages/ipPools/tests/__snapshots__/EditPage.test.js.snap, src/pages/ipPools/tests/__snapshots__/ListPage.test.js.snap
- Moved IP warm-up banner to edit IP pool page (maybe should add it to edit ip page?)
- Added Strict TLS and Custom Messaging Expiration banner to IP pool list page
- Navigate to /account/ip-pools and confirm Strict TLS ... banner is visible
- Click submit a support ticket to confirm support modal opens
- Navigate to /account/ip-pools/edit/default and confirm warm-up banner is visible
=> SD-1693: Update SparkPost UI to Reflect New IP Pool Options

src/pages/users/CreatePage.js, src/pages/users/ListPage.js, src/pages/users/tests/__snapshots__/CreatePage.test.js.snap
[FE-1100](https://jira.int.messagesystems.com/browse/FE-1100)
- Incorporated feedback tweaks outlined in the ticket
- Go to `/account/users` and verify the "Enabled" tag in the 2FA column does not render with a color
- Go to `/account/users/create` and verify that the paragraph help text is moved below the field via the `helpText` prop
=> FE-1100 - Incorporate UX feedback for the users feature

src/pages/ipPools/components/IpForm.js
- Changed "gold" to "cold" on sending IP details page
- See steps to reproduce in ticket
=> SD-1876: Fix "gold" typo on sending IP details page

src/components/filterDropdown/FilterDropdown.js, src/components/filterDropdown/FilterDropdown.module.scss, src/components/filterDropdown/tests/__snapshots__/FilterDropdown.test.js.snap, src/pages/signals/components/filters/SubaccountFilter.module.scss, src/pages/suppressions/components/SuppressionSearch.js, src/pages/suppressions/components/SuppressionSearch.module.scss, src/pages/suppressions/components/tests/__snapshots__/SuppressionSearch.test.js.snap
[FE-1097](https://jira.int.messagesystems.com/browse/FE-1097)
- Updated `SubaccountFilter` and `FilterDropdown` components according to ticket requirements
=> FE-1097 - Custom dropdown components should render full width relative to their paired fields

cypress/fixtures/api-keys/401.delete.scim-token.json, cypress/tests/integration/accounts/account-settings/accountSettingsPage.js, src/actions/scimToken.js, src/actions/tests/__snapshots__/scimToken.test.js.snap, src/actions/tests/scimToken.test.js, src/pages/account/components/SingleSignOnPanel/SCIMTokenSection.js, src/pages/account/components/SingleSignOnPanel/SingleSignOnPanel.js, src/reducers/scimToken.js, src/reducers/tests/__snapshots__/scimToken.test.js.snap, src/reducers/tests/scimToken.test.js
AC-1474: (UI) Add the Delete SCIM token flow
- Clicking on the Delete token opens Delete scim token modal.  https://sparkpost.invisionapp.com/public/share/FR169HZ78E#/screens/478309246
- Click on the Delete Token in SCIM token section, it opens the Delete SCIM token modal. 
- Run the cypress test added. This should help in checking the flow.
=> AC-1474: (UI) Add the Delete SCIM token flow

src/config/env/dev-config.js, src/config/env/production-config.js, src/config/env/staging-config.js, src/config/env/uat-config.js
[AC-1471] Update support.algolia.index in config for new WP VIP indices
- Change these index names:
- development_site_posts_support_article -> wp_vip_site_develop_posts_support_article
- staging_site_posts_support_article -> wp_vip_site_preprod_posts_support_article
- production_site_posts_support_article -> wp_vip_site_production_posts_support_article
- Open the support modal and Check if the network request are sent to updated index names.
=> [AC-1471] Update support.algolia.index in config for new WP VIP indices

src/components/support/Support.js, src/components/support/tests/Support.test.js, src/selectors/accountBillingInfo.js, src/selectors/support.js, src/selectors/tests/support.test.js
AC-1195 - (UI) App should enforce phone support via billing subscription
**This branch is based from AC-1325**
- phone support for a user is now checked using products returned by their GET billing/subscription
- Added selector for the same
- check if you see/not see phone support tab in the support modal based on your plan
- [] Address feedback
=> AC-1195 - (UI) App should enforce phone support via billing subscription

src/pages/account/components/CancellationPanel.js
[FE-1113] The CancellationPanel logs an error when window.pendo does not exist
- Changed this sentry error to a sentry warning instead.
- Block Pendo cdn and click on Cancel Account, this should trigger a sentry warning. 
ref - https://sentry.io/organizations/sparkpost/issues/1773564134/?project=232588&query=is%3Aunresolved
=> FE-1113 - The CancellationPanel logs an error when window.pendo does not exist

src/pages/billing/components/BillingSummary.js, src/pages/billing/components/tests/__snapshots__/BillingSummary.test.js.snap, src/selectors/accessConditionState.js, src/selectors/tests/accessConditionState.test.js
AC-1553 - Starter plan description should not include "First dedicated IP address is free"
- includesIps is set to true when (currentBundle has 'dedicated_ip' on it) &&  (current plan is not deprecated), otherwise it is set to false
- Dedicated Ip Panel shows up on billing page irrespective of canPurchaseIps.
- Create an account on a starter plan and confirm that 'First dedicated IP address is free' line doesn't show on /account/billing/plan .
=> AC-1553 - Starter plan description should not include "First dedicated IP address is free"

package-lock.json, package.json
- Upgrade axios from v0.18.0 to v0.19.2 ([release notes](https://github.com/axios/axios/releases))
Before testing, it is very important to understand what "fixes and functionality" are included in the upgrade.
v0.19.0
- Unzip response body only for statuses != 204 (#1129) - drawski
- n/a, we don't set the Content-Encoding header
- Destroy stream on exceeding maxContentLength (fixes #1098) (#1485) - Gadzhi Gadzhiev
- n/a, we don't stream
- Makes Axios error generic to use AxiosResponse (#1738) - Suman Lama
- n/a, just the typescript definition
- Fixing Mocha tests by locking follow-redirects version to 1.5.10 (#1993) - grumblerchester
- n/a, tests
- Allow uppercase methods in typings. (#1781) - Ken Powers
- n/a, more typescript definition tweaks
- Fixing .eslintrc without extension (#1789) …
=> FE-1122: Upgrade axios to v0.19.2 for 2web2ui

src/components/support/components/SupportForm.js, src/config/supportIssues.js, src/helpers/conditions/account.js, src/helpers/conditions/tests/account.test.js, src/selectors/accountBillingInfo.js
AC-1557 - (UI) App should enforce online support via billing subscription
- Show online support tab on help form if "online_support" product is returned from GET /billing/subscription
- Check if you see the options(eg Daily Sending Limit Increase) in the menu in "Submit A ticket" tab on Support Form on the basis of whether you have "online_support" in subscription or not.
=> AC-1557 - (UI) App should enforce online support via billing subscription

cypress/tests/integration/accounts/billing/billingPage.spec.js, src/__func__/billing/__snapshots__/updateContactDetails.test.js.snap, src/actions/billing.js
AC-1340 -  Replace PUT /api/v1/account/billing with PUT /api/v1/billing
- replaced PUT /account/billing with /billing to update billing contact details
- On billing page, update the billing contact details and check if the network call is being made to /billing instead of /account/billing
~**need to wait on AC-1327 on being merged before testing this.**~ ✅
=> AC-1340 -  (UI) Replace PUT /api/v1/account/billing with PUT /api/v1/billing

cypress/fixtures/account/200.get.250k-premier-plan.json, cypress/fixtures/billing/subscription/200.get.premier-plan-with-limitoverride.json, cypress/tests/integration/accounts/billing/changeBillingPlanPage.spec.js, src/pages/billing/context/FeatureChangeContext.js, src/pages/billing/context/tests/__snapshots__/FeatureChangeContext.test.js.snap
AC-1588 - (UI) Update the override condition for subaccounts
- User needs to be prompted to update the subaccount status if the qty > limit_override && limit_override > limit of the new selected plan
- The cypress test added in this ticket can help in testing this scenario.
=> AC-1588 - (UI) Update the override condition for subaccounts

src/__func__/auth/__snapshots__/login.test.js.snap, src/__func__/auth/__snapshots__/loginRememberMe.test.js.snap, src/__func__/auth/__snapshots__/ssoReturn.test.js.snap, src/__func__/auth/__snapshots__/tfa.test.js.snap, src/__func__/auth/__snapshots__/tfaEnableOnLogin.test.js.snap, src/__func__/signup/__snapshots__/join.test.js.snap, src/__func__/signup/__snapshots__/joinEmailOptIn.test.js.snap, src/actions/accessControl.js, src/actions/tests/accessControl.test.js, src/pages/recipientValidation/RecipientValidationPage.js, src/pages/recipientValidation/UploadedListPage.js
AC-1608 - Remove the GET /billing/subscription call for AWS users
- Removed the GET /billing/subscription call for aws users from accessControlState
- Verify that app loads for aws users. [I can invite to a aws account]
=> AC-1608 - Remove the GET /billing/subscription call for AWS users

src/pages/billing/context/FeatureChangeContext.js
AC-1597 - Empty Subaccount section should not show in Features after updating the status of subaccounts
- Empty Subaccount section will not render in Features after updating the status of subaccounts
- Steps to reproduce the bug :
- Create an account on premier plan with limit_override = 2, Create 3 subaccounts
[to set the override - PUT /billing/subscription/control/product/subaccounts
{limit_override : 2}]
- Navigate to change plan page and select starter plan
-  Click on Update Status in Subaccount Section
- terminate 1 subaccount in new tab and navigate back to old tab, empty subaccount section shouldn't shows up now
=> AC-1597 - Empty Subaccount section should not show in Features after updating the status of subaccounts

src/helpers/segment.js, src/pages/sendingDomains/CreatePage.js, src/pages/sendingDomains/tests/CreatePage.test.js
- Added a new event for tracking when a sending domain is added
- Create a sending domain
- Ensure event is being logged via the debugger: https://app.segment.com/sparkpost-daniel-chalef/sources/webui_dev/debugger
=> AC-1619 Added Sending Domain Added event

src/context/HibanaContext.js, src/helpers/segment.js
- In addition to logging to pendo, log the hibana toggled event to Segment
- Toggle Hibana on and off via the profile page
- Ensure events are being logged via the debugger: https://app.segment.com/sparkpost-daniel-chalef/sources/webui_dev/debugger
- Ensure the event has an attribute `ux`, which we will be able to filter by in mixpanel, etc.
=> AC-1668 Add Hibana Toggled On and Hibana Toggled Off to Segment

src/helpers/segment.js, src/helpers/tests/segment.test.js
- Every time we `identify` we also `group`, which allows us to group analytics per tenant/account combination.
- Pretty much do anything in the app (load a page, for example)
- Check segment debugger to see a "Group" event: https://app.segment.com/sparkpost-daniel-chalef/sources/webui_dev/debugger
=> AC-1680 Call Segment Group function every time Identify is called

src/helpers/segment.js, src/helpers/tests/segment.test.js
- It turns out that Mixpanel ignores the first argument of the Segment `group` call, so we need to be redundant and send it as a trait. See https://help.mixpanel.com/hc/en-us/articles/115004560846-Segment-Set-Up-Guide under "Integrating Group Analytics via Segment"
- Do anything in the web app (load page, etc.)
- Ensure the "Group" event is in the debugger: https://app.segment.com/sparkpost-daniel-chalef/sources/webui_dev/debugger with the additional trait "groupId"
=> AC-1680 Followup - Mixpanel ignores first segment argument for group call

cypress/tests/integration/domains/createPage.spec.js, src/pages/domains/components/CreateForm.js
FE-1193: Add the Option to create Bounce Domain to Add a Domain Form
- Added the option for Bounce Domain in Add a Domain Form.
- On Selecting this option and creating a Bounce Domain it redirects to Bounce only verification Page (Hibana_Domains ) /domains/details/:id/verify-bounce; this verification page is being completed as part of FE-1173 which is in review.
- Added cypress tests for creation of Bounce Domain
- Updated condition for Principal and all Subaccounts to show up even when bounce domains are created
mock - https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478910829
- Create a bounce domain from /domains/create
- After adding a bounce domain you should be redirected to /domains/details/:id/verify-bounce
=> FE-1193: Add the Option to create Bounce Domain to Add a Domain Form

cypress/tests/integration/domains/createPage.spec.js, src/config/routes/index.js, src/pages/domains/VerifySendingBounceDomainPage.js, src/pages/domains/components/CreateForm.js, src/pages/domains/components/DomainAlignmentModal.js, src/pages/domains/index.js
FE-1194 - Add the Modal for Domain Alignment
- Added the Modal as in the mocks. This modal shows up when user clicks on Save and Continue for a sending domain.
- If the user clicks on ‘Yes’ for ‘Strict Alignment’ then redirect to Sending/Bounce Verification Page - domains/details/:id/verify-sending-bounce
- if the user clicks on ‘No’ for ‘Strict Alignment’ then redirect to Sending Verification Page - domains/details/:id/verify-sending
mock - https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/479035680
- Create a Sending Domain from /domains/create and Select Yes or No and check if it redirects to the correct page
=> FE-1194 - Add the Modal for Domain Alignment

cypress/fixtures/tracking-domains/200.put.json, cypress/plugins/index.js, cypress/tests/integration/domains/detailsPage.spec.js, package-lock.json, package.json, src/pages/domains/components/Container.js, src/pages/domains/components/DomainStatusSection.js, src/reducers/sendingDomains.js
- Added a confirmation modal and cypress tests to the new domain details page.
- Run the cypress tests for domains/domainDetails.spec.js
- Load the app the navigate to `http://localhost:3100/domains/details/fad-5415.io` logged in with appteam. Then toggle the "Set as Default Tracking Domain" checkbox.
=> FE-1196 - Default Domain Confirmation Modal

cypress/fixtures/sending-domains/200.get.bounce-verified-sending-unverified.json, cypress/tests/integration/domains/detailsPage.spec.js, src/pages/domains/DetailsPage.js
[FE-1195] Added the Bounce domain section for unverified sending and bounce domains
- updated the isSectionVisible condition for bounce section
- On an unverified sending domain page, bounce section should also be visible
[FE-1195]: https://sparkpost.atlassian.net/browse/FE-1195
=> [FE-1195] Added the Bounce domain section for unverified sending and bounce domains details page

src/pages/reportBuilder/components/GroupByOption.js, src/pages/reportBuilder/components/tests/GroupByOption.test.js, src/pages/reportBuilder/components/tests/ReportTable.test.js
- Fixed group by behavior on non comparators
- Go to report builder with `allow_report_filters_v2` as `false`
- Go to group by, select any category
- Click one filter to add it in
- Only one row should be visible after
- Choose another category and then go back to original category
- Still should only have one role
=> SA-1721: Fixed issue with group by in non comparators filters

cypress/fixtures/sending-domains/200.get.all-verified.json, cypress/fixtures/sending-domains/200.get.unverified-dkim-bounce.json, cypress/tests/integration/domains/verifySendingBounceDomainPage.spec.js, src/pages/domains/DetailsPage.js, src/pages/domains/VerifyBounceDomainPage.js, src/pages/domains/VerifySendingBounceDomainPage.js, src/pages/domains/VerifySendingDomainPage.js, src/pages/domains/components/Container.js, src/pages/domains/components/DomainStatusSection.js, src/pages/domains/components/LinkTrackingDomainSection.js, src/pages/domains/components/SendingAndBounceDomainSection.js, src/pages/domains/components/SetupBounceDomainSection.js, src/pages/domains/components/SetupForSending.js, src/pages/domains/components/TrackingDnsSection.js, src/pages/domains/components/VerifyEmailSection.js, src/pages/domains/components/tests/DomainStatusSection.test.js, src/reducers/trackingDomains.js
FE-1187 - Add the Sending/Bounce Verification Page
- Added the Sending/Bounce Verification Page
- Updated the condition for showing the sending and bounce section on details page of completely verified domain
- Reduced prop drilling happening in DomainDetailsPage
- Added the pending state to all the verification pages
- Added cypress tests for Sending/Bounce Verification Page
- Create Sending Domain from /domains/create
- Select 'Strict Alignment' from Domain Alignment Modal to get to Sending/Bounce Verification Page.
- Check if it matches mocks - https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478945612
=> FE-1187 - Add the Sending/Bounce Verification Page

cypress/fixtures/metrics/deliverability/subaccount/200.get.json, cypress/tests/integration/signals-analytics/analytics-report/analyticsReportBreakdownTable.spec.js, src/pages/reportBuilder/ReportBuilder.js, src/pages/reportBuilder/components/ReportTable.js
- Subaccounts called on mounting report builder
- Subaccounts are no longer feature flagged behind additional comparators
- Subaccounts called once
- On any account (with or without account ui feature flag `allow_report_filters_v2`), subaccounts API call should be made
- Click on Group By selector (bottom of page)
- Select subaaccounts
- Subaccount names should populate (if available)
=> SA-1763: Subaccounts are called on mounting report builder

cypress/tests/integration/signals-analytics/analytics-report/reportPage.spec.js, src/pages/reportBuilder/ReportBuilder.js
- Filter are properly attached when parsed from URL params
- Go to report builder
- Don't select a report
- Add a filter
- Copy and paste URL
- Filter should persist through URL
=> SA-1770: Fixed filters not properly being pulled from query params

cypress/tests/integration/domains/detailsPage.spec.js, src/pages/domains/DetailsPage.js, src/pages/domains/components/Container.js, src/pages/domains/components/SetupForSending.js, src/pages/domains/components/TrackingDnsSection.js
[FE-1197] UX Feedback for Domain Details Pages - Part 3
- Verify if the above changes look good
[FE-1197]: https://sparkpost.atlassian.net/browse/FE-1197
=> [FE-1197] UX Feedback for Domain Details Pages - Part 3

src/components/toggleBlock/ToggleBlock.js, src/pages/domains/DetailsPage.js, src/pages/domains/components/CreateForm.js, src/pages/domains/components/DomainStatusSection.js, src/pages/domains/components/LinkTrackingDomainSection.js, src/pages/domains/components/SendingAndBounceDomainSection.js, src/pages/domains/components/SetupBounceDomainSection.js, src/pages/domains/components/SetupForSending.js, src/pages/domains/components/TrackingDnsSection.js, src/pages/domains/components/VerifyEmailSection.js
[FE-1203] UX Feedback for Domain Detail Pages Part - 1
-  Verify all the above changes look good.
[FE-1203]: https://sparkpost.atlassian.net/browse/FE-1203
=> [FE-1203] UX Feedback for Domain Detail Pages Part - 1

cypress/tests/integration/signals-analytics/analytics-report/filtersForm.spec.js, src/hooks/useMultiEntry/useMultiEntry.js, src/hooks/useMultiEntry/useMultiEntry.test.js, src/pages/reportBuilder/components/FiltersForm/FiltersForm.js, src/pages/reportBuilder/components/FiltersForm/components.js
[SA-1805](https://sparkpost.atlassian.net/browse/SA-1805)
- Adds new `error` and `minLength` properties to the `useMultiEntry` hook state
- Adds `minLength` of `3` to the `MultiEntryController` used in the `FiltersForm`
- Adds supporting integration and unit tests
- With Hibana enabled and the `allow_report_filters_v2` feature flag enabled, go to `/signals/analytics`
- Click on "Add Filters" and change the compare by value to "contains" or "does not contain"
- type 1 or 2 characters and try adding the tag to the field with the space key, enter key, or by blurring the field
- An error should render!
- The error should be removed when: the user clears their entry entirely _or_ the user enters 3 or more characters
=> SA-1805 - (UI) Advanced comparators error with less than 3 character values

cypress/tests/integration/domains/listPage.spec.js, src/pages/domains/components/SendingDomainsTab.js, src/pages/domains/components/TableFilters.js, src/pages/domains/components/TrackingDomainsTab.js, src/pages/domains/helpers/customDomainStatusFilter.js, src/pages/domains/helpers/filterStateToParams.js, src/pages/domains/helpers/getActiveStatusFilters.js, src/pages/domains/helpers/getReactTableFilters.js, src/pages/domains/helpers/index.js
- Reversed the UI logic for domain status filtering
1. **The page url** "http://localhost:3100/domains/list/sending" **automatically selects and updates the url on page load** - "http://localhost:3100/domains/list/sending?readyForSending=true&readyForDKIM=true&readyForBounce=true&validSPF=true&unverified=true&blocked=true"
**2. As the user un-checks the status options the URL is updated along with the table.**
**3. Refreshing the page causes the same filter state to load.**
(Sorting and paging are not persistent in the URL ... yet...?)
- Just have to load up the domain list pages and try to break the filtering/sorting/paging in any way possible. 
http://localhost:3100/domains/list/sending
http://localhost:3100/domains/list/bounce
http://localhost:3100/domains/list/tracking
Question for …
=> FE-1226 - Domain list page - status filter "or" logic

src/pages/domains/DetailsPage.js
[FE-1258] - Link tracking domain section not showing subaccount options
- Added listtracking call for Link tracking domain section
- Click on a verified sending domain and check the Link Tracking domain section
- On clicking select their you should see all the available options
- Double check with old ui in OG theme.
[FE-1258]: https://sparkpost.atlassian.net/browse/FE-1258
=> [FE-1258] listtracking call for Link tracking domain section

src/pages/domains/components/Container.js, src/pages/domains/components/LinkTrackingDomainSection.js
How to test - 
- Check for option in "Link Tracking Domains" section for sending domain with subaccounts and check option in OG theme.
- Check for option in "Link Tracking Domains" section for sending domain without subaccounts and check option in OG theme.
=> Fe 1258 hotfix - fixing tracking domain options for sending domain with subaccounts

cypress/tests/integration/domains/detailsPage.spec.js, cypress/tests/integration/domains/verifySendingBounceDomainPage.spec.js, src/pages/domains/DetailsPage.js, src/pages/domains/components/SendingAndBounceDomainSection.js, src/pages/domains/components/SetupBounceDomainSection.js
FE-1245 - Removed the "Authenticate for SPF" section from domain details page and verification page for bounce and sending/bounce
- Removed the "Authenticate for bounce" section from
- Unverified domain details page - domains/details/sending-bounce/test.123.900
- Verification pages 
- Sending/Bounce = domains/details/test.123.900/verify-sending-bounce
- Bounce = http://localhost:3100/domains/details/test.123.900/verify-bounce
- Copy in the left Panel for Bounce is also updated to match - https://sparkpost.invisionapp.com/console/share/CS1SX9XT3H/478945608
- Verify the Authentication for SPF section is gone, and rest of functionality still works correctly
=> FE-1245 - Removed the "Authenticate for SPF" section from domain details page and verification page for bounce and sending/bounce

src/context/HibanaContext.js, src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/subaccounts/components/SendingDomainsTab.js, src/pages/subaccounts/components/test/SendingDomainsTab.test.js, src/pages/subaccounts/components/test/__snapshots__/SendingDomainsTab.test.js.snap
FE-1244 - Redirection to account/sending-domains from /account/subaccounts and Add a Sending Domain step on Dashboard should be replaced with correct domain pages in Hibana
- In Hibana redirect to /domains/list/sending instead of account/sending-domains from /account/subaccounts page
- In Hibana redirect to /domains/create instead of account/sending-domains/create Add a Sending Domain step on old 
Dashboard page
- Check if the links redirect to correct pages in Hibana and in OG
=> [FE-1244] Fixed the links to domains in Hibana

cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js, src/pages/dashboardV2/DashboardPageV2.container.js, src/pages/dashboardV2/DashboardPageV2.js
- Added grant checks around the dynamic onboarding states. Set fallback as the else if the needed grants are not met.
- Removed the extra <Abbr> element
Follow on to: https://github.com/SparkPost/2web2ui/pull/1899
(in that pr I added an extra abbr and didnt set the right grant checks - this fixes that)
**Note**: At some point I think it'd be good to move the onboarding logic/string to be on the main app state where any component/state could pick up on it and react to the users onboarding state. 
- Load up a user of each type and check to see the onboarding states are correct.
admin and dev will see the individual onboarding steps based on sending domain and api key data. 
reporting and templates will _currently_ always see the analytics promo until a future ticket changes that.
=> FE-1257 - DashboardV2 Onboarding Grant Check

src/pages/usage/components/MessagingUsageSection.js
- Modified the existing Usage page
- changed `ExternalLink` to `SubduedLink` to match mocks
- Log in to any account and visit `/usage`
- Make sure the `Messaging Usage Definition` and `Quota Limits` links on the left side of the page are subdued, external links
=> FE-1277 use SubduedLink on Usage page

src/pages/domains/components/TrackingDnsSection.js
- display text `TXT` is changed to `CNAME`
- Just need to make sure the value displays correctly on the tracking domain details page: http://localhost:3100/domains/details/tracking/{domain_name}
domain I used: boo-yeah.com
=> FE-1279 - CNAME instead of TXT

cypress/tests/integration/domains/detailsPage.spec.js, cypress/tests/integration/domains/verifyBounceDomainPage.spec.js, cypress/tests/integration/domains/verifySendingBounceDomainPage.spec.js, cypress/tests/integration/domains/verifySendingDomainPage.spec.js, cypress/tests/integration/domains/verifyTrackingDomainPage.spec.js, src/components/links/ExternalLink.js, src/pages/domains/components/CreateForm.js, src/pages/domains/components/DeleteDomainSection.js, src/pages/domains/components/DomainStatusSection.js, src/pages/domains/components/LinkTrackingDomainSection.js, src/pages/domains/components/SendingAndBounceDomainSection.js, src/pages/domains/components/SetupBounceDomainSection.js, src/pages/domains/components/SetupForSending.js, src/pages/domains/components/TrackingDnsSection.js, src/pages/domains/components/VerifyEmailSection.js
- Button labels changed (Authenticate For Bounce -> Verify Bounce, Authenticate Domain -> Verify Domain)
- Buttons not disabled by default - error messages show if clicked
- More Cypress tests added to cover the error/button interaction
- More Cypress tests for the Forward to Colleague anchors/href values
- Adjusted grammar a little (added periods at the end of sentences)
- Removed margin bottom from all the <Panel /> components I could find in the domain details and create pages.
- <ExternalLink /> props adjusted to control icon sizing and spacing directly instead of by `Component.name`
(component.name === button is still setting icon size and space if the size/margin values are default)
- Placeholder sentence was removed from the "For other reasons why this ay have happenedchek out our …
=> FE-1278 - Domain Configuration Feedback

cypress/tests/integration/signals-analytics/analytics-report/reportTabs.spec.js, src/pages/reportBuilder/ReportBuilder.js, src/pages/reportBuilder/components/tables/BounceReasonTable.js, src/pages/reportBuilder/components/tables/DelayReasonTable.js, src/pages/reportBuilder/components/tables/index.js, src/pages/reportBuilder/components/tabs/BounceReasonComparisonTab.js, src/pages/reportBuilder/components/tabs/BounceReasonTab.js, src/pages/reportBuilder/components/tabs/DelayReasonsComparisonTab.js, src/pages/reportBuilder/components/tabs/DelayReasonsTab.js, src/pages/reportBuilder/components/tabs/index.js, src/pages/reportBuilder/constants/index.js
[SA-1850](https://sparkpost.atlassian.net/browse/SA-1850)
- Extracts delay reasons table as a component and refactors existing delay reasons tab
- Adds new `DelayReasonsComparisonTab` component that renders when relevant delay reason metrics are selected _and_ comparisons are applied
- Cleaned up existing tests by adding missing `cy.wait()` actions and using more re-usable functions
1. With the compare by feature flag enabled, go to `/signals/analytics`
2. Add delay reason metrics ("Accepted", "Delayed", "Delayed 1st Attempt")
3. Add two valid comparisons
4. Verify that a new delay reason tab renders for each item being compared and that the default "Delay Reason" tab does _not_ render
5. Additionally, add some bounce reason metrics ("Bounces", for example) and verify that bounce reason …
=> SA-1850 - (UI) Compare By - Delays Report

cypress/fixtures/reports/200.get.json, cypress/tests/integration/signals-analytics/analytics-report/savedReports.spec.js, src/pages/reportBuilder/components/SavedReportsSection/SaveReportModal.js, src/pages/reportBuilder/components/SavedReportsSection/tests/SaveReportModal.test.js
- Active comparisons displayed on save report changes modal
- Go to report builder
- Save a custom report
- Click Add Comparisons and add at least 2 comparison filters (need feature flag `allow_compare_by`)
- Click `Save Changes` to get to save report modal
- Verify that active comparisons are displayed
=> SA-1894: Add active comparisons to save report modal

cypress/fixtures/authenticate/grants/200.get.reporting.json, cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js, src/hooks/usePinnedRport/usePinnedReport.js, src/pages/dashboardV2/DashboardPageV2.container.js
[FE-1286] Show Pinned Report to Reporting and templates user when their last_usage_date!==null
- Updated the condition to show Analytics Promo step for templates and reporting user when last usage date is null
- And show Pinned Report for templates and reporting user when last usage date is not null
- Updated a condition on usePinnedReport which was causing the _skipped_ cypress test to fail
- Updated the usage/view grant in the fixture for reporting users.
- Check /dashboardv2 for reporting and templates user on appteam, it should show pinned report.
[FE-1286]: https://sparkpost.atlassian.net/browse/FE-1286
=> FE-1286 - Show Pinned Report to Reporting and templates user when their last_usage_date!==null

cypress/fixtures/subaccounts/200.get.many.json, cypress/tests/integration/signals-analytics/analytics-report/reportCompareBy.spec.js, src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
- Added comparison limit of 10 filters
- On Hibana, with `allow_compare_by` feature flag enabled, go to Report Builder page
- Click on `Add Comparison`
- Select comparison type
- Fill out form, adding up to 10 filters
- Verify that warning appears at top of form
- Just realized that user wouldn't immediately see the warning message. Might be worth thinking about how the message is displayed.
=> SA-1893: Compare by filters limited to 10 filters

src/helpers/segment.js, src/pages/reportBuilder/components/CompareByForm/CompareByForm.js
- Added segment tracking event for compare by in report builder
- Go to Comparison form in report builder
- Apply form with no comparisons
- Check that request does not go through with applying
- Apply form with at least 2 comparison
- Check that request goes through with the appropriate data
=> SA-1892: Added segment to report builder comparison form

cypress/fixtures/users/200.get.subaccount-banner-dismissed.json, cypress/tests/integration/subaccounts/listPage.spec.js, src/components/matchbox/Page.js, src/config/routes/index.js, src/constants/index.js, src/pages/api-keys/ListPage.js, src/pages/snippets/ListPage.js, src/pages/subaccounts/ListPage.js, src/pages/subaccounts/components/InfoBanner.js, src/pages/subaccounts/components/SubaccountEmptyState.js, src/pages/subaccounts/index.js, src/pages/subaccounts/tests/__snapshots__/ListPage.test.js.snap
- Adding empty state and banner to subaccount list
- Cypress tests locally are easiest, because the account has to have the usage to create subaccounts for real.
- For non local: Have to have an account that has the ability to have subaccounts and has none yet.
- Check the empty state shows and has the right display text, then create a subaccount and test the banner is visible.
- Then clear the banner and refresh to make sure it doesn't show up again.
=> FE-1252 - Subaccounts Empty State and Info Banner

src/pages/reportBuilder/components/SavedReportsSection/SavedReportsSection.js
- Fixed error from triggering when no report selected and deleting report
- Delete a report without selecting report
- Verify error doesn't occur
=> SA-1918: Check for selected report before checking id

cypress/tests/integration/signals-analytics/analytics-report/savedReports.spec.js, src/pages/reportBuilder/components/ReportOptions.js, src/pages/reportBuilder/components/SavedReportsSection/SaveReportModal.js, src/pages/reportBuilder/components/SavedReportsSection/tests/SaveReportModal.test.js
- Report params generated again instead of pulling straight from URL
- Report ID no longer attached to saving report (to avoid having a report point to another report
- Go to report builder
- Select a report
- Save a new report
- Save under a new name
- Verify that report id is not attached
=> SA-1897: Strip report ID when saving a report from an existing report

cypress/tests/integration/signals-analytics/analytics-report/reportPage.spec.js, src/constants/index.js, src/pages/reportBuilder/ReportBuilder.js, src/pages/reportBuilder/components/ReportBuilderEmptyState.js, src/pages/reportBuilder/components/index.js
FE-1269 - Create Empty State for Analytics Report 
-  Empty state should show up on Analytics Report when user has no sending domain.
-  Added the three Tabs  as in the mock (with placeholder components)
mocks - https://sparkpost.invisionapp.com/console/Empty-States-ckcno05yk00tf011ij29ebpmx/ckevla6xu04f301yh7ymqfocx/play#project_console
- Enable "allow_empty_states" feature flag and check the Analytics page when you have no sending domain, you should see the Empty state as in the mock, with three placeholder tabs
- When "allow_empty_states" feature flag is not enabled the Analytics Page should appear as it is now.
=> FE-1269 - Create Empty State for Analytics Report 

cypress/fixtures/billing/subscription/200.get.premier-plan-with-dedicatedip-override.json, cypress/tests/integration/accounts/billing/billingPage.spec.js, src/config/default.js, src/pages/billing/components/BillingSummary.js, src/pages/billing/components/DedicatedIpCost.js, src/pages/billing/components/DedicatedIpSummarySection.js, src/pages/billing/components/ManuallyBilledOrAwsBanner.js, src/pages/billing/components/tests/BillingSummary.test.js, src/pages/billing/components/tests/DedicatedIpCost.test.js, src/pages/billing/components/tests/DedicatedIpSummarySection.test.js, src/pages/billing/components/tests/__snapshots__/BillingSummary.test.js.snap, src/pages/billing/components/tests/__snapshots__/DedicatedIpSummarySection.test.js.snap, src/pages/billing/components/tests/__snapshots__/ManuallyBilledOrAwsBanner.test.js.snap, src/pages/billing/forms/AddIps.js, src/pages/billing/forms/tests/AddIps.test.js, src/pages/billing/forms/tests/__snapshots__/AddIps.test.js.snap
AC-1838: Update UI to use dedicated ip limits from api instead of value in config
- DedicatedIpSection and AddIps form on billing page now uses limits, quantity, price and billing_period from GET /billing/subscription
- removed the isAwsAccount from the DedicatedIpCost since billing page isn't visible to them anyways (they just see a banner)
- Added cypress tests for the case where user has higher limit on subscription for dedicated ip
- Run the added cypress tests 
- Limit override can be set for a account using PUT /billing/subscription/control/product/dedicated_ip - https://github.com/SparkPost/sparkpost-admin-api-documentation/blob/master/services/billing_api.md#subscription-product---[…]oncontrolproductproduct
- Check that the Add Dedicated Ips is not disabled for user who haven't …
=> AC-1838: Update UI to use dedicated ip limits from api instead of value in config

cypress/fixtures/users/200.get.report-builder-banner-dismissed.json, cypress/tests/integration/signals-analytics/analytics-report/reportPage.spec.js, src/pages/reportBuilder/ReportBuilder.js, src/pages/reportBuilder/components/InfoBanner.js, src/pages/reportBuilder/components/index.js, src/pages/reportBuilder/context/ReportBuilderContext.js
Branched from [FE-1270](github.com/SparkPost/2web2ui/pull/2005)
- Info banner for report builder doc and seedlist buttons was added at the top of the page
- On an account that hasn't dismissed the banner yet, go to the report builder page with at least one verified sending domain.
- The info banner should show at the top of the page until the user dismisses it.
- 
- What's the link for the view seedlist button?
- When should that view seedlist button show? Always?
=> FE-1338 - Report Builder Info Banner

cypress/fixtures/sending-domains/200.get.multiple-results.json, cypress/fixtures/sending-domains/200.get.paginated-results.json, cypress/fixtures/sending-domains/verify/200.post-abusetoken.json, cypress/tests/integration/configuration/domains/listPage.spec.js, src/pages/domains/DetailsPage.js, src/pages/domains/ListPage.js, src/pages/domains/components/Container.js, src/pages/domains/components/SendingDomainsTab.js, src/pages/domains/components/VerifyToken.js, src/pages/sendingDomains/components/VerifyToken.js, src/reducers/sendingDomains.js
FE-1334: Add the functionality on new domain pages to verify domain through url
- Added VerifyToken component on Domains list page
- Whenever domain/list/sending?domain={{domain}}&token={{token}}&mailbox={{mailbox}} is loaded, verify action will trigger on page load
- if the domain is verified then it would redirect to domain details page with a success alert
- if domain is not verified then it would stay on the list page with unsuccessful alert
- Load http://localhost:3100/domains/list/sending?domain=unverified.com&mailbox=abuse&token=akaka url, you should see a unsuccessful alert
- From appteam staging send yourself a email from here 
- use the token and mailboax in the link and navigate to http://localhost:3100/domains/list/sending?domain={{domain}}&mailbox={{mailbox}}&token={{token}}
=> FE-1334: Add the functionality on new domain pages to verify domain through url

cypress/tests/integration/signals-analytics/analytics-report/reportPage.spec.js, src/pages/reportBuilder/ReportBuilder.js
- Do not show empty states for customers when allow_ingest_events is enabled
- Enable allow_ingest_events Account option for a new account and check if you can see the empty state on Report builder page.
- Check if this solution works for all the roles.
=> [FE-1352] Do not show empty state when allow_ingest_events  is enabled

src/hooks/usePinnedRport/usePinnedReport.js
- Custom relativeRange reports were calling into `getRelativeDates` and that function wasn't returning from and to information. That was resulting in the response from `reportOptionsWithDates` to not have from and to, and as a result the pinnedReport `pinnedReport` object used in DashboardPageV2.js had no from and to information. 
- This PR ensures that custom relativeRange reports have their from and to properties set for displaying on the dashboard. 
- Go to the /dashboard page and change reports to and from custom and non custom date range reports. Use the summary report too - and check to make sure the to and from dates used/showing are correct for the custom saved range.
=> FE-1337 - Fix custom relativeRange reports on dashboard v2

cypress/tests/integration/accounts/usage/usagePage.spec.js, src/pages/usage/UsagePage.js
- Merged the account usage response into the main usage response to make sure limit data is correctly displaying.
- Go to the `/usage` page and make sure daily and monthly limit data is displaying.
(this data will only show if on accounts that have limits & not on enterprise)
- https://sparkpost.atlassian.net/browse/FE-1249
=> AC-1851 - Merge account usage into main usage

src/helpers/segment.js, src/pages/dashboardV2/DashboardPageV2.container.js, src/pages/dashboardV2/DashboardPageV2.js
- Tracking onboarding steps in segment as long as it's not set to "done"
- Create a new account and go to the dashboard. 
- Go through each onboarding step manually calling the API to get past the sending domain verification process.
- Make sure calls are going out to segment for each step.
=> FE-1344 - track onboarding in segment

cypress/tests/integration/signals-analytics/analytics-report/compareBy.spec.js, src/components/typeahead/AsyncComboBoxTypeahead.js, src/helpers/api/domains.js, src/helpers/api/metrics.js, src/helpers/api/selectors/metrics.js, src/helpers/api/subaccounts.js, src/pages/reportBuilder/components/CompareByForm/CompareByForm.js, src/pages/reportBuilder/components/CompareByForm/Typeahead.js, src/pages/reportBuilder/components/FiltersForm/FiltersForm.js, src/pages/reportBuilder/components/Typeahead.js
- Typeahead now passes to/from dates
- Typeahead now uses react-query to help with caching
- Typeahead now has debounce of 500ms
- Go to report builder
- Verify that typeaheads pass in proper params in filters form
- Verify that typeahesds pass in proper params in compare by
- Verify that typeaheads have longer debounce time
=> SA-2055: Performance improvements on typeahead

cypress/tests/integration/dashboard/dashboardPage.spec.js, src/pages/dashboardV2/DashboardPageV2.container.js, src/pages/dashboardV2/DashboardPageV2.js, src/pages/dashboardV2/components/Sidebar.js
- Used the account condition `isManuallyBilled` to determine `hasUpgradeLink`.
- When an account/user has a billing/subscription return type `manual` - hasUpgradeLink is set to false.
- a.k.a. Upgrade link hidden for manually billed customers.
- Have to have a manually billed account/user subscription type. I don't know how to actually set that or log in with that. I mocked the state using Cypress. 
- Log into a manually billed account then go to dashboard and verify no Upgrade link on the right sidebar.
=> FE-1361 - Hide upgrade link for manually billed subscriptions

.circleci/config.yml, src/components/collection/Pagination.js
[FE-1299](https://sparkpost.atlassian.net/browse/FE-1299)
- Uses newer Matchbox `Columns` component to fix layout issues with the `TableCollection` component on smaller screen sizes
- On smaller screen sizes the layout looks like this:
- On larger screen sizes the layout looks like this:
- Visit a page using the `TableCollection` (like **/lists/recipient-lists** or **/domains**) and resize the window until it is relatively narrow
- Verify that pagination content wraps as expected
- Verify that the pagination buttons conditionally render as expected according to the changes
=> FE-1299 - Fixes layout problem with the Pagination component

src/pages/domains/components/SendingDomainStatusCell.js, src/pages/domains/components/SendingDomainsTable.js, src/pages/domains/components/SetupForSending.js
- Change tag color green to darkGray for domain pages
Before: 
After:
Before:
After:
- Go to the domain list and details page and make sure the green tags on stage are now gray locally
=> FE-1364 - change green to darkGray

cypress/tests/integration/configuration/domains/listPage.spec.js, src/actions/sendingDomains.js, src/constants/index.js, src/pages/domains/components/VerifyToken.js
FE-1366 - Alert is displayed only once
- Alert on verification of domain through token will display the success/error alert only once.
Steps to reproduce the bug:
- Verify a domain by email.
- Click on the link in the email notification.
- After being redirected to the app, and if the domain is successfully verified, navigate away from the Domains list page and back
- ~Subsequent visits to the list page display the same Snackbar~ subsequent visits should display snackbar only once.
=> FE-1366 - Alert is displayed only once

cypress/fixtures/tracking-domains/verify/200.post.json, cypress/tests/integration/configuration/domains/detailsPage.spec.js, src/actions/tests/__snapshots__/trackingDomains.test.js.snap, src/actions/tests/trackingDomains.test.js, src/actions/trackingDomains.js, src/pages/domains/components/SendingAndBounceDomainSection.js, src/pages/domains/components/SetupBounceDomainSection.js, src/pages/domains/components/SetupForSending.js, src/pages/domains/components/TrackingDnsSection.js
FE-1370 - Added the Re-verify Domain button to domain details page(Sending, Bounce and Tracking)
- Added the Re-Verify Domain Buttons to 
- Verified Sending / Bounce Domain Page eg - http://localhost:3100/domains/details/sending-bounce/staging-test.spappteam.com
- Verified Tracking Domain Pages eg - http://localhost:3100/domains/details/tracking/newbob.spappteam.com
- Navigate to any sending/bounce/tracking domain detail pages
- there should be Re-Verify Domain button that should trigger the api to verify these domains
- Should throw appropriate alerts on success/failure
=> [FE-1370] Added the Re-verify Domain button to domain details page(Sending, Bounce and Tracking)

cypress/tests/integration/configuration/domains/createPage.spec.js, src/pages/domains/components/CreateForm.js
- Added a mini banner in the domain and assignment to draw attention to using a subdomain and not a root domain.
- Go to the domain create form/page.
- Look at the left sidebar for the "domain and assignment" section.
=> FE-1298 - Recommend using a subdomain when creating

cypress/tests/integration/configuration/domains/listPage.spec.js, src/pages/domains/components/DomainStatusSection.js, src/pages/domains/components/SendingDomainsTab.js, src/pages/domains/components/SendingDomainsTable.js, src/pages/domains/components/TableFilters.js, src/pages/domains/components/TrackingDomainStatusCell.js, src/pages/domains/components/TrackingDomainsTab.js, src/pages/domains/components/TrackingDomainsTable.js, src/pages/domains/helpers/customDomainStatusFilter.js
- All domain status filters are unchecked by default, then preserved using the url query params between page loads and using the browser back button.
- Clears filter state when switching from sending -> bounce tab. (request from UX)
- Leaves filter state when switching from bounce -> sending tab. (request from UX)
- go to /domains/list/sending and test the domain status filter on all three tabs
- test navigating away from the page and using the browser back button
- Test landing the page, updating the filters, switching between the tabs and refreshing the page (note the filter state reset logic mentioned in "what changed")
=> FE-1340 - No domain status filters selected by default

cypress/tests/integration/configuration/domains/listPage.spec.js, src/pages/domains/components/VerifyToken.js
[FE-1372] subaccountid is sent with the  verifytoken request
- Corrected the misspelled key in domains VerifyToken component
- Added a cypress test to verify correct headers are sent with the request
[FE-1372]: https://sparkpost.atlassian.net/browse/FE-1372
=> [FE-1372] subaccountid is sent with the  verifytoken request

package-lock.json, package.json, src/App.js
[AC-1849] -  Prevent Segment installation when you are a bot
- Do not load segment if a bot is detected at user agent.
- Added the isBot npm library to help identify the user agent. - _Decided to go with ibot since it has better [npm trends](https://www.npmtrends.com/crawler-user-agents-vs-isbot-vs-spider-detector-vs-bot-detector) than other packages_
- One way to test this set the useragent to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/61.0.3116.0 Safari/537.36 Chrome-Lighthouse` following instructions here https://developers.google.com/web/tools/chrome-devtools/device-mode/override-user-agent 
In cypress.dev.json add 
{
"baseUrl": "http://localhost:3100",
"userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36(KHTML, like Gecko) …
=> [AC-1849] -  Prevent Segment installation when you are a bot

cypress/tests/integration/configuration/domains/listPage.spec.js, src/pages/domains/VerifyBounceDomainPage.js, src/pages/domains/components/LinkTrackingDomainSection.js, src/pages/domains/components/SendingDomainStatusCell.js, src/pages/domains/components/SendingDomainsTab.js, src/pages/domains/components/SendingDomainsTable.js, src/pages/domains/components/SetupBounceDomainSection.js
FE-1371 - Remove all SPF related information from domain pages and remove Create a separate bounce domain link where not necessary
- Check if any SPF related information is present on the domain pages (as mentioned above)
- Check whether  'Create a separate bounce subdomain' link doesn't show on domain detail page for bounce verified domains.
- Check whether 'Create a separate bounce subdomain'  link is not present on /domains/details/{{domainname}}/verify-bounce.
=> FE-1371 - Remove all SPF related information from domain pages and remove Create a separate bounce domain link where not necessary

.circleci/config.yml, cypress/tests/integration/content/templates/createPage.spec.js
- Adds missing `cy.wait()` commands to reduce the risk of flakiness
- [Retry the pipeline repeatedly](https://app.circleci.com/pipelines/github/SparkPost/2web2ui/4436/workflows/0b93d5f9-7195-48ff-a75a-f9f282de449f) and see if the `createPage.spec.js` passes consistently
=> FE-1367 - Addresses test flakiness for templates create page spec

cypress/tests/integration/signals-analytics/analytics-report/dateAndTimeSection.spec.js, package.json, src/components/reportBuilder/AggregatedMetrics.js, src/components/reportBuilder/CompareByAggregatedMetrics.js, src/helpers/date.js, src/pages/dashboardV2/DashboardPageV2.js, src/pages/reportBuilder/ReportBuilder.js
-Dates account for timezone in  report builder
- Go to report report builder
- Set a time that is on the edge of a new day (previous or forward)
- Change timezone to move day to next day (or previous day)
- Verify that date is correct in aggregate data (relative to timezone)
=> SA-2042: Fixed issue with dates not formatting to timezone 

src/actions/billingCreate.js, src/actions/tests/billingCreate.test.js, src/components/billing/PromoCodeNew.js, src/components/billing/tests/__snapshots__/PromoCodeNew.test.js.snap, src/pages/onboarding/ChoosePlan.js, src/pages/onboarding/tests/__snapshots__/ChoosePlan.test.js.snap, src/reducers/billingCreate.js, src/reducers/index.js, src/selectors/onboarding.js, src/selectors/tests/__snapshots__/onboarding.test.js.snap, src/selectors/tests/onboarding.test.js
AC-1850 - ChoosePlanPage flashes before redirecting to dashboard and adding a paid plan
_Note-_ 
_Cause of this bug seemed to be coming from the actions emitted by the redux form, the form would emit a redux/@Destroy action after a successful submit which would trigger rerender of the form before the redirect to dashboard._
- moved the redirect and alert to useEffect instead of then.
- Sign up for a new account.
- On Choose plan page, choose a paid plan
- check if the flasing of the page is gone and you get redirected to dashboard smoothly
=> AC-1850 - ChoosePlanPage flashes before redirecting to dashboard when adding a paid plan

src/components/reportBuilder/CompareByAggregatedRow.js
[SA-2194](https://sparkpost.atlassian.net/browse/SA-2139)
- Updated styles to collapse on certain breakpoints
- Resize the browser window on both `/signals/analytics` and `/dashboard` with comparisons active on a report (Click "Add Comparisons" if none are present or swap to a saved report with active comparisons)
- Verify the content within the aggregates UI is responsive:
=> SA-2194 - Resolves (UI) Compare by aggregated UI should be responsive

package.json, src/constants/index.js, src/pages/dashboardV2/DashboardPageV2.container.js, src/pages/dashboardV2/DashboardPageV2.js
- Removed useless conditional from Dashboard - 
- https://github.com/SparkPost/2web2ui/security/code-scanning/94?query=ref%3Arefs%2Fheads%2Fmaster
- https://github.com/SparkPost/2web2ui/security/code-scanning/93?query=ref%3Arefs%2Fheads%2Fmaster
- moved onboarding strings into an enum in src/constants
- Check if any code scanning alert shows up.
=> [FE-1381] Resolve Code scanning warning for 2web2ui - DashboardPageV2.container.js

src/pages/templates/hooks/useEditorContent.js
[FE-1383] Resolve code scanning warning for 2web2ui - src/pages/templates/*
- Remove useless condition from src/pages/templates/hooks/useEditorContent.js
- Check if condition change doesn't break anything in templates (editing content)  
[FE-1383]: https://sparkpost.atlassian.net/browse/FE-1383
=> [FE-1383] Resolve code scanning warning for 2web2ui - src/pages/templates/*

src/pages/billing/components/PlanSelect.js, src/pages/billing/components/tests/PlanSelect.test.js, src/pages/billing/context/FeatureChangeContext.js
[FE-1392] Resolve code scanning warning for 2web2ui - src/pages/billing/*
- Replace local useModal with the src/hooks/useModal
- Remove useless test from FeatureChangeContext
- Check if the Feature Comparison Modal is working correctly on /account/billing/plan
- Check if the Saved Report feature shows up correctly on Change Plan Page
[FE-1392]: https://sparkpost.atlassian.net/browse/FE-1392
=> [FE-1392] Resolve code scanning warning for 2web2ui - src/pages/billing/*

src/components/segment/SegmentPage.js, src/components/segment/tests/SegmentPage.test.js, src/components/segment/tests/__snapshots__/Segment.test.js.snap, src/constants/index.js, src/pages/join/JoinPage.js
- Removed the check for access control in the segment page call
- Create a new account and make sure segment is getting the /onboarding/join data after account creation
=> AC-1905 - Track /join to /onboarding/plan in segment

src/pages/defaultRedirect/DefaultRedirect.js, src/pages/defaultRedirect/tests/DefaultRedirect.test.js, src/pages/sso/SSOPage.js, src/pages/sso/tests/SSOPage.test.js, src/pages/sso/tests/__snapshots__/SSOPage.test.js.snap, src/reducers/auth.js
AC-1911: Unable to re-enter webui when using SSO and Safari
Note - Reason for the below change - https://sparkpost.atlassian.net/browse/AC-1911?focusedCommentId=204739
Related to https://bugs.webkit.org/show_bug.cgi?id=77538
- Added an extra check on DefaultRedirect to set the authCookie, if it is not already set
- Not sure of a way to test this locally, Can be easily tested in staging though using the credentials we have in 1pass.
=> AC-1911: Unable to re-enter webui when using SSO and Safari

cypress/tests/integration/accounts/billing/billingPage.spec.js, src/pages/abTesting/EditMode.js, src/pages/abTesting/tests/EditMode.test.js, src/pages/abTesting/tests/__snapshots__/EditMode.test.js.snap, src/pages/join/components/JoinForm.js, src/pages/join/components/tests/JoinForm.test.js, src/pages/join/components/tests/__snapshots__/JoinForm.test.js.snap, src/pages/reportBuilder/components/MetricsForm/MetricsForm.js, src/pages/snippets/CreatePage.js, src/pages/snippets/EditPage.js, src/pages/snippets/tests/CreatePage.test.js, src/pages/snippets/tests/EditPage.test.js, src/pages/snippets/tests/__snapshots__/CreatePage.test.js.snap, src/pages/snippets/tests/__snapshots__/EditPage.test.js.snap
This is split branch from AC-1917 and has all other changes other than domain
**On Ab testing page**
**On Report Builder**
**On Snippet**
**On JoinForm**
- onSubmit of these newly added forms work correctly
=> [AC-1917-without-domain-changes] All other form updates other than domains

src/pages/domains/components/SendingAndBounceDomainSection.js, src/pages/domains/components/SetupBounceDomainSection.js, src/pages/domains/components/SetupForSending.js, src/pages/domains/components/TrackingDnsSection.js, src/pages/domains/components/VerifyEmailSection.js
**On Domain Pages**
- onSubmit of these newly added forms work correctly
- Easier approach to testing this section would be take a existing verified sending/bounce domain and navigate to 
- /domains/details/:domainName/verify-sending-bounce
- domains/details/:domainName/verify-bounce
- domains/details/:domainName/verify-sending
for tracking domain
- domains/details/:domainName/verify-tracking
- For email verification Modal
- For testing MailboxVerificationModal open src/config/env/dev-config.js change allow_anyone_at_verification = false and allow_mailbox_verification = true, no spc/spceu/staging account(we can't test for enterprise account in staging) has this feature flag disabled, so the default AllowAnyoneVerificationModal currently is the most used one. Testing the …
=> AC-1917 - with Domain changes only
