SparkPost/2web2ui

src/components/Navigation/navItems.js, src/pages/Dashboard/components/TutorialItem.js, src/pages/index.js
Also removed a line that that was crashing the app
=> Upgrade MB to 1.0.0

package.json, src/components/reduxFormWrappers.js, src/components/subaccountTypeahead/SubaccountTypeahead.js, src/components/subaccountTypeahead/SubaccountTypeahead.module.scss, src/components/subaccountTypeahead/SubaccountTypeaheadItem.js, src/components/subaccountTypeahead/tests/SubaccountTypeahead.spec.js, src/components/subaccountTypeahead/tests/__snapshots__/SubaccountTypeahead.spec.js.snap
Here's an initial pass at the subaccount typeahead component that will be used in probably half of the forms in our UI.
TO DO:
=> FAD-5500 Subaccount Typeahead

package.json, src/components/auth/ProtectedRoute.js
Moment has a bug: https://github.com/moment/moment/issues/4216
ProtectedRoute started passing all props through to RR Route, causing
an issue with component vs render, fixed that here too.
=> Pins moment, fixes route bug

src/config/routes.js, src/pages/templates/CreatePage.js, src/pages/templates/EditPage.js, src/pages/templates/PublishedPage.js, src/pages/templates/test/CreatePage.test.js, src/pages/templates/test/__snapshots__/CreatePage.test.js.snap, src/selectors/templates.js, src/selectors/tests/__snapshots__/templates.test.js.snap, src/selectors/tests/templates.test.js
Known issue: Sending domain selection. However, that's [a known issue](https://github.com/SparkPost/2web2ui/blob/master/src/pages/templates/components/Form.js#L74) anyway and will be handled later, separately.
=> Templates - Duplicate

src/index.js
This is follow-up to #145 caught by Sentry, issue [396100186](https://sentry.io/sparkpost/2web2ui-dev/issues/396100186/)
=> Hotfix for onunhandledrejection handler

src/actions/auth.js
This reverts commit 8511b5315972bc5dae93e03b5e6611b54c8bfc53.
=> Revert "FAD-5682 Remove redundant dispatch"

.gitignore, .npmrc, package-lock.json, package.json
https://bamboo.int.messagesystems.com/browse/CENG-W2UI-1614
=> Enable package lock to fix broken build

src/components/collection/Collection.js
Turns out the check is not needed in cDU, just needed default props
=> FAD-5928 Add collection filterBox default props

.eslintrc, jest.config.json, package-lock.json, package.json, src/pages/register/tests/RegisterPage.test.js, src/pages/register/tests/RegisterUserForm.test.js, src/pages/subaccounts/components/formFields.js, src/pages/users/CreatePage.js
To test locally:
* `git fetch && git checkout hotfix/FAD-5936`
* Make a throwaway branch based on this one, so you can test commits `git checkout -b throwaway`
* `npm install`
* Add something valid to a file and do `git add` for that file
* Add a `console.log` to a different file but _don't_ do `git add` on that one
* Commit your valid change, should commit fine
* Now do `git add` on the invalid file with the console.log in it
* Try to commit, notice you get an error and the commit has failed
* Replace the `console.log` with a line missing a semi-colon or some other "fixable" error
* Try to commit, it will go through fine and the file will have been committed as "fixed"
* Delete your test branch `git checkout - && git branch -D throwaway`
You can also try running tests to verify the …
=> [FAD-5936] Pre-commit and build-time linting

config/webpack.config.prod.js, src/components/layout/Layout.module.scss, src/index.scss
- Turns off [z-index rebasing](http://cssnano.co/optimisations/zindex/) on production build. This should fix a lot of mobile & nav layering
- Also closes #201 - Makes top accent bar fixed
- Also closes #200 - Sets HTML background color
=> FAD-5942 Fix z-index rebasing

src/pages/suppressions/CreatePage.js, src/pages/suppressions/tests/CreatePage.test.js
This is the error from Sentry.
https://sentry.io/share/issue/0a19f9e798f84235928ab2e46dbaf0f3/
**Steps to Reproduce**
1. Download [empty.csv.zip](https://github.com/SparkPost/2web2ui/files/1717424/empty.csv.zip)
2. Navigate to suppression upload list form
3. Choose "empty.csv"
4. Click "Upload" button
Actual - An unexpected error is thrown.
Expected - Nothing should happen because input error message is already displayed.
=> FAD-5629 Hotfix for suppression upload list form

package-lock.json, package.json, src/components/copyField/CopyField.js, src/components/copyField/tests/CopyField.test.js, src/components/copyField/tests/__snapshots__/CopyField.test.js.snap, src/components/domainStatus/tests/__snapshots__/StatusTooltip.test.js.snap, src/components/grantBoxes/tests/__snapshots__/GrantsCheckboxes.test.js.snap, src/components/support/Support.js, src/components/support/tests/__snapshots__/Support.test.js.snap, src/components/tags/tests/__snapshots__/DomainStatusTag.test.js.snap, src/pages/profile/components/BackupCodesView.js, src/pages/profile/components/CopyCodes.js, src/pages/profile/components/tests/__snapshots__/BackupCodesView.test.js.snap, src/pages/profile/components/tests/__snapshots__/CopyCodes.test.js.snap, src/pages/reports/components/DateFilter.js, src/pages/reports/components/tests/DateFilter.test.js, src/pages/reports/components/tests/__snapshots__/DateFilter.test.js.snap, src/pages/reports/components/tests/__snapshots__/MetricCard.test.js.snap, src/pages/reports/engagement/components/tests/__snapshots__/EngagementTable.test.js.snap, src/pages/reports/messageEvents/components/tests/__snapshots__/EventDetails.test.js.snap, src/pages/reports/summary/components/MetricsModal.js, src/pages/reports/summary/components/tests/__snapshots__/MetricsModal.test.js.snap, src/pages/sendingDomains/components/tests/__snapshots__/EditBounce.test.js.snap
Updates for SparkPost/matchbox#111
Will update package version once  the MB pr has been merged
=> FAD-6245 Overlay Portals

src/actions/helpers/sparkpostApiRequest.js, src/actions/helpers/tests/__snapshots__/sparkpostApiRequest.test.js.snap, src/actions/helpers/tests/sparkpostApiRequest.test.js
See steps to reproduce in the ticket
=> FAD-6387 fix logout flow

src/pages/templates/components/Form.js, src/pages/templates/components/tests/__snapshots__/Form.test.js.snap
Verify:
- Save 
- Create
- Get (initial value population)
=> FAD-6398 Fix template reply_to name

src/pages/suppressions/components/ErrorBanner.js, src/pages/suppressions/components/tests/ErrorBanner.test.js
_See [FAD-6425](https://jira.int.messagesystems.com/browse/FAD-6425)._
=> FAD-6425 Error handling for bulk upload of suppressions is broken

src/components/domainStatus/StatusTooltipHeader.js, src/components/domainStatus/tests/__snapshots__/StatusTooltip.test.js.snap, src/pages/sendingDomains/components/EditBounce.js, src/pages/sendingDomains/components/SetupSending.js, src/pages/sendingDomains/components/StatusDescription.js, src/pages/sendingDomains/components/tests/EditBounce.test.js, src/pages/sendingDomains/components/tests/SetupSending.test.js, src/pages/sendingDomains/components/tests/__snapshots__/EditBounce.test.js.snap, src/pages/sendingDomains/components/tests/__snapshots__/SetupSending.test.js.snap, src/pages/sendingDomains/components/tests/__snapshots__/StatusDescription.test.js.snap
Mb updated to allow `node` pass through to `Panel` title
=> FAD-6171 Reverify DNS

src/components/collection/FilterBox.js, src/pages/reports/bounce/BouncePage.js, src/pages/reports/bounce/tests/__snapshots__/BouncePage.test.js.snap, src/pages/reports/rejection/RejectionPage.js, src/pages/reports/rejection/components/DataTable.js, src/pages/reports/rejection/components/tests/__snapshots__/DataTable.test.js.snap, src/pages/reports/rejection/tests/__snapshots__/RejectionPage.test.js.snap
Had to rework some of the `Panel`-ing around these tables. Added Panels around every other filterbox as well.
=> FAD-6416 Bounce and Rejections Report table filters

public/index.html, public/static/tenant-config/production.js, src/config/default.js, src/critical.scss, src/index.js, src/index.scss
Sentry issue: https://sentry.io/sparkpost/phoenix-ui-local/issues/512705488/?query=is:unresolved
Error screen:
Easiest way to test is to block the url `localhost:3100/static/js/bundle.js` in chrome dev tools
=> FAD-6279 Gracefully handle and log app load errors

src/actions/messageEvents.js, src/actions/tests/__snapshots__/messageEvents.test.js.snap, src/actions/tests/messageEvents.test.js, src/components/globalAlert/RedirectAndAlert.js, src/components/globalAlert/tests/RedirectAndAlert.test.js, src/components/globalAlert/tests/__snapshots__/RedirectAndAlert.test.js.snap, src/config/default.js, src/pages/reports/messageEvents/EventPage.js, src/pages/reports/messageEvents/components/MessageEventsSearch.js, src/pages/reports/messageEvents/tests/EventPage.test.js, src/pages/reports/messageEvents/tests/__snapshots__/EventPage.test.js.snap, src/reducers/messageEvents.js, src/selectors/messageEvents.js, src/selectors/tests/messageEvents.test.js
Refer to [FAD-6455](https://jira.int.messagesystems.com/browse/FAD-6455)
=> FAD-6455: Improve UX for message events details page when message_id is undefined

src/pages/reports/components/ShareModal.js, src/pages/reports/components/tests/ShareModal.test.js, src/pages/reports/components/tests/__snapshots__/ShareModal.test.js.snap
Re opening cause it needs a GH review
=> FAD-6475 Turn on qp encoding in share modal

src/components/support/Support.js, src/components/support/components/SearchPanel.js, src/components/support/components/SearchPanel.module.scss, src/components/support/components/SupportCta.js, src/components/support/components/SupportCta.module.scss, src/components/support/components/tests/SearchPanel.test.js, src/components/support/components/tests/SupportCta.test.js, src/components/support/components/tests/__snapshots__/SearchPanel.test.js.snap, src/components/support/components/tests/__snapshots__/SupportCta.test.js.snap, src/components/support/tests/Support.test.js, src/components/support/tests/__snapshots__/Support.test.js.snap, src/selectors/support.js, src/selectors/tests/support.test.js
To verify, make sure you are on a plan with phone support. Use appteam account to verify the negative case where online support is still available but phone is not
=> FE-98 Add phone support text in submit a ticket pop up

src/actions/billingCreate.js, src/helpers/errorTracker.js, src/helpers/tests/errorTracker.test.js, src/pages/billing/forms/ChangePlan.js
log zuora payload (partially) to track card type issue
=> ESCSP-2204

src/config/metrics.js
=> SA-64 Add support for the new unsubscribe metric

src/pages/users/components/DeleteButton.js, src/pages/users/components/tests/__snapshots__/DeleteButton.test.js.snap
=> FE-379 Reduce size of role select and delete user button on user list page

src/config/metrics-units.js, src/helpers/chart.js, src/helpers/tests/chart.test.js, src/pages/reports/summary/components/async/LineChart.scss
Use this link to test under appteam: http://localhost:3100/reports/summary?from=2018-06-11T19%3A21%3A45Z&metrics=unsubscribe_rate&range=custom&to=2018-06-18T19%3A21%3A45Z
=> FE-402 Display up to a thousandth in summary chart percent labels

jest.config.js, package-lock.json, package.json, src/actions/tests/__snapshots__/support.test.js.snap, src/components/auth/tests/__snapshots__/SuspensionAlerts.test.js.snap, src/components/navigation/components/tests/__snapshots__/AccountDropdown.test.js.snap, src/components/support/components/tests/__snapshots__/SupportForm.test.js.snap, src/components/typeahead/tests/__snapshots__/SubaccountTypeahead.test.js.snap, src/helpers/tests/file.test.js, src/pages/dashboard/tests/__snapshots__/DashboardPage.test.js.snap, src/pages/ipPools/tests/__snapshots__/ListPage.test.js.snap, src/pages/profile/components/tests/__snapshots__/EnableTfaModal.test.js.snap, src/pages/reports/bounce/tests/__snapshots__/BouncePage.test.js.snap, src/pages/reports/components/tests/__snapshots__/ReportOptions.test.js.snap, src/pages/reports/messageEvents/components/tests/__snapshots__/MessageEventsSearch.test.js.snap, src/pages/reports/messageEvents/tests/__snapshots__/MessageEventsPage.test.js.snap, src/pages/sendingDomains/components/tests/__snapshots__/EditBounce.test.js.snap, src/pages/sendingDomains/components/tests/__snapshots__/SetupSending.test.js.snap, src/pages/sendingDomains/tests/__snapshots__/ListPage.test.js.snap, src/pages/subaccounts/components/test/__snapshots__/SubaccountCreateForm.test.js.snap, src/pages/subaccounts/components/test/__snapshots__/SubaccountEditForm.test.js.snap, src/pages/suppressions/components/tests/__snapshots__/SuppressionSearch.test.js.snap, src/pages/templates/tests/__snapshots__/ListPage.test.js.snap, src/pages/users/tests/__snapshots__/ListPage.test.js.snap, src/pages/webhooks/tests/__snapshots__/ListPage.test.js.snap, src/selectors/tests/__snapshots__/support.test.js.snap
Jest changes
- `<React.Fragment>` now rendered in snapshots
- `<Context>` now rendered in snapshots
- `mockFn.mock.results` returned in snapshots for some reason
=> FE-375 Update Jest deps

src/pages/reports/messageEvents/components/ActiveFilters.js, src/pages/reports/messageEvents/components/AdvancedFilters.js, src/pages/reports/messageEvents/components/searchConfig.js, src/pages/reports/messageEvents/components/tests/__snapshots__/AdvancedFilters.test.js.snap
New message events advanced filter:
Tags:
=> FE-311 Add filter by bounce class

src/critical.scss, src/pages/suppressions/components/Results.js, src/pages/suppressions/components/tests/Results.test.js
- Add thunks from event handlers to suppression search `Results.toggleDeleteModal`
- Also fixed some smart quotes in critical.scss
=> FE-430: be more careful with event handler arguments in Suppression Detail component

package-lock.json, package.json, src/components/planPicker/PlanPicker.js, src/pages/reports/components/tests/__snapshots__/Typeahead.test.js.snap, src/pages/templates/components/FromEmail.js, src/pages/templates/components/tests/FromEmail.test.js
Closes #504 #517
Dropped this update ~~Awaiting `cssnano` update to fix this build error (https://github.com/cssnano/cssnano/issues/537):~~
```
Module build failed: BrowserslistError: Unknown version 67 of android
```
=> FE-431 Greenkeeper updates

src/components/labelledValue/LabelledValue.js, src/components/labelledValue/tests/LabelledValue.test.js, src/components/labelledValue/tests/__snapshots__/LabelledValue.test.js.snap
Updating this component (LabelledValue) instead of the message events detail component per conversation with @jasonrhodes and @jonambas
=> SA-139: Updates LabelledValue component to gracefully handle booleans

docs/access-control.md, src/__integration__/README.md
=> Last updates to docs

package-lock.json, package.json, public/index.html, src/components/errorBoundaries/ErrorBoundary.js, src/helpers/errorTracker.js, src/helpers/tests/__snapshots__/errorTracker.test.js.snap, src/helpers/tests/errorTracker.test.js
What to test?
- Confirm render errors are reported to Sentry
- Confirm every reported error was a documentLanguage, navigatorLanguage, and source
- Confirm browser extension errors are reported to Sentry as warnings
- Confirm API errors are reported as warnings
- Confirm unable to load application errors are reported to Sentry as warnings
=> FE-413: Improve Sentry issue filtering, tags

src/actions/accessControl.js, src/actions/account.js, src/actions/currentUser.js, src/actions/tests/accessControl.test.js
- Login
- Modify auth token
- Refresh
- App should log you out with no visible errors
=> FE-534 Suppress access control errors

src/constants/index.js, src/pages/dashboard/DashboardPage.js, src/pages/dashboard/components/Tutorial.js, src/pages/dashboard/components/TutorialItem.js, src/pages/dashboard/components/TutorialItem.module.scss, src/pages/dashboard/components/tests/__snapshots__/Tutorial.test.js.snap, src/pages/dashboard/components/tests/__snapshots__/TutorialItem.test.js.snap, src/selectors/sendingDomains.js, src/selectors/tests/__snapshots__/sendingDomains.test.js.snap, src/selectors/tests/sendingDomains.test.js
=> FE-478 Improve getting started checklist

scripts/generateConfigs/defaultTemplate.js, scripts/generateConfigs/tenants/production.js, scripts/generateConfigs/tenants/staging.js, scripts/generateConfigs/tenants/uat.js, scripts/generateConfigs/tests/__snapshots__/constructConfig.test.js.snap, scripts/generateConfigs/tests/__snapshots__/defaultTemplate.test.js.snap, scripts/generateConfigs/tests/constructContent.test.js, src/pages/users/EditPage.js, src/pages/users/tests/EditPage.test.js
=> FE-528: Disable single sign-on checkbox for users when not enabled for account

src/pages/users/ListPage.js, src/pages/users/tests/ListPage.test.js, src/pages/users/tests/__snapshots__/ListPage.test.js.snap
New "Edit your user account" link
=> AC-295: Sole user accounts wants ability to enable single sign-on

scripts/generateConfigs/tenants/production.js
Will check config details with TAM and update this PR as needed.
Note: DNS and CF are not yet configured.
=> FE-549: Added new tenant

src/helpers/http.js
=> TR-641: Fix /authenticate endpoint

package-lock.json, src/pages/auth/components/LoginForm.js, src/pages/auth/components/tests/__snapshots__/LoginForm.test.js.snap
Bug - this shouldn't be disabled:
Repro:
1. Log out of lastpass
2. Make sure saved credentials in chrome://settings/passwords
3. Open app, let Chrome fill in fields without touching anything
=> FE-573 Login page submit button disabled when fields autofilled

package-lock.json, package.json
=> Installed devDep eslint-plugin-flowtype

src/__integration__/http-responses/v1/metrics/deliverability/get.js, src/components/brightback/Brightback.js, src/components/brightback/tests/Brightback.test.js, src/components/brightback/tests/__snapshots__/Brightback.test.js.snap
- Removed `brightback` UI option conditions
- Fixed up unit and integration tests
- Start with a paid account
- Downgrade to free
- Site back and watch as you're redirected to Brightback
=> AC-439: make Brightback available to all

src/context/Poll.js, src/context/tests/Poll.test.js, src/context/tests/__snapshots__/Poll.test.js.snap, src/pages/recipientValidation/components/ListResults.js, src/pages/recipientValidation/components/tests/ListResults.test.js
(1) Polling should stop if it completes when on another route
(2) Polling should stop when logging out
=> EO-354 Recip Validation Polling bugs

src/pages/signals/components/charts/horizontalbar/HorizontalBar.js, src/pages/signals/components/charts/horizontalbar/tests/HorizontalBar.test.js, src/pages/signals/components/charts/horizontalbar/tests/__snapshots__/HorizontalBar.test.js.snap, src/pages/signals/components/charts/sparkline/Sparkline.js, src/pages/signals/components/charts/sparkline/tests/Sparkline.test.js, src/pages/signals/components/charts/sparkline/tests/__snapshots__/Sparkline.test.js.snap, src/pages/signals/components/charts/tooltip/Tooltip.js, src/pages/signals/components/charts/tooltip/Tooltip.scss, src/pages/signals/components/charts/tooltip/tests/Tooltip.test.js, src/pages/signals/components/charts/tooltip/tests/__snapshots__/Tooltip.test.js.snap
Example usage:
```js
import HorizontalBar from './components/charts/horizontalbar/HorizontalBar';
<HorizontalBar
value={{
hits: 2,
fill: 'blue',
date: new Date() // date here will display it in the tooltip
}}
xRange={[0,5]}
xKey='hits'
tooltipContent={(payload) => <div>hits: {payload.value}</div>}
/>
```
=> EO-431 Add Horizontal Bar component

scripts/generateConfigs/tenants/production.js, src/config/default.js, src/config/test-config.js, src/pages/billing/components/tests/__snapshots__/Confirmation.test.js.snap, src/selectors/brightback.js, src/selectors/tests/__snapshots__/brightback.test.js.snap
I wasn't sure what to call the plan config, so I modeled it off of what we do in the accusers API where we call it `defaults.plan`
=> AC-456 adds default plan for downgrade to free

src/pages/signals/OverviewPage.js, src/pages/signals/components/charts/barchart/BarChart.js, src/pages/signals/components/charts/barchart/BarChart.scss, src/pages/signals/components/charts/barchart/tests/BarChart.test.js, src/pages/signals/components/charts/barchart/tests/__snapshots__/BarChart.test.js.snap
Demo code: 
```js
import BarChart from './components/charts/barchart/BarChart';
import moment from 'moment';
import _ from 'lodash';
// fake data
const randInt = (max) => Math.floor(Math.random() * Math.floor(max));
const data = _.range(90).map((n, i) => ({
bar: randInt(25),
foo: randInt(25),
baz: randInt(25),
abc: randInt(25),
date: moment().subtract(90 - i, 'day').toISOString()
}));
// class state setup
state = {
selected: ''
}
handleBarClick = ({ payload }) => {
this.setState({ selected: payload.date });
}
// render
<BarChart timeSeries={data}
yDomain={[0,100]}
yKeys={[
{ key: 'bar', fill: '#B157CE' },
{ key: 'foo', fill: '#28C0C4' },
{ key: 'baz', fill: '#FF9502' },
{ key: 'abc', fill: '#50D1F3' }
]}
gap={0.3}
onClick={this.handleBarClick}
selected={this.state.selected}
xAxisProps={{ …
```
=> EO-434 Add bar chart

package-lock.json, package.json, src/components/summaryTable/PerPageControl.js, src/components/summaryTable/SummaryTable.js, src/components/summaryTable/SummaryTable.module.scss, src/components/summaryTable/tests/__snapshots__/PerPageControl.test.js.snap, src/components/summaryTable/tests/__snapshots__/SummaryTable.test.js.snap
=> EO-452 Update signals pagination styling

package-lock.json, package.json, src/actions/signalOptions.js, src/actions/tests/__snapshots__/signalOptions.test.js.snap, src/actions/tests/signalOptions.test.js, src/components/typeahead/Typeahead.js, src/components/typeahead/tests/__snapshots__/Typeahead.test.js.snap, src/config/facets.js, src/pages/signals/components/filters/DateFilter.js, src/pages/signals/components/filters/DateFilter.module.scss, src/pages/signals/components/filters/FacetFilter.js, src/pages/signals/components/filters/FacetFilter.module.scss, src/pages/signals/components/filters/SubaccountFilter.js, src/pages/signals/components/filters/SubaccountFilter.module.scss, src/pages/signals/components/filters/SubaccountOption.js, src/pages/signals/components/filters/SubaccountOption.module.scss, src/pages/signals/components/filters/tests/DateFilter.test.js, src/pages/signals/components/filters/tests/FacetFilter.test.js, src/pages/signals/components/filters/tests/SubaccountFilter.test.js, src/pages/signals/components/filters/tests/SubaccountOption.test.js, src/pages/signals/components/filters/tests/__snapshots__/DateFilter.test.js.snap, src/pages/signals/components/filters/tests/__snapshots__/FacetFilter.test.js.snap, src/pages/signals/components/filters/tests/__snapshots__/SubaccountFilter.test.js.snap, src/pages/signals/components/filters/tests/__snapshots__/SubaccountOption.test.js.snap, src/pages/signals/components/withSignalOptions.js, src/pages/signals/tests/__snapshots__/OverviewPage.test.js.snap, src/reducers/index.js, src/reducers/signalOptions.js, src/reducers/tests/__snapshots__/signalOptions.test.js.snap, src/reducers/tests/signalOptions.test.js
=> EO-426: Create Overview Filter Components

scripts/generateConfigs/tenants/production.js
Slack thread: https://msys.slack.com/archives/C69L53989/p1545146113061000
=> FE-591 Update eonians tracking domain cname value

src/components/navigation/components/Item.js, src/components/navigation/components/Item.module.scss, src/components/navigation/components/tests/Item.test.js, src/components/navigation/components/tests/__snapshots__/Item.test.js.snap, src/config/navItems.js
=> EO-465 Add new feature nav item tag

src/selectors/accountBillingInfo.js, src/selectors/tests/__snapshots__/accountBillingInfo.test.js.snap, src/selectors/tests/accountBillingInfo.test.js
Remove filters based on filters already added to api for plans
=> AC-491: Updated filters for dropdowns

public/index.html, src/App.js, src/components/pendo/Pendo.js, src/components/pendo/tests/Pendo.test.js, src/components/pendo/tests/__snapshots__/Pendo.test.js.snap
[Pendo install doc is here](https://help.pendo.io/resources/support-library/installation/snippet-installation.html).
- In the console after auth: `pendo.validateInstall()`
- Ask me for a Pendo account
- Improve the weird `...iff pendo is available` test in `Pendo.test.js`
=> FE-604: load and init Pendo

src/pages/recipientValidation/components/ListResults.js, src/pages/recipientValidation/components/ListResultsCard.js, src/pages/recipientValidation/components/ListResultsCard.module.scss, src/pages/recipientValidation/components/tests/ListResults.test.js, src/pages/recipientValidation/components/tests/ListResultsCard.test.js, src/pages/recipientValidation/components/tests/__snapshots__/ListResults.test.js.snap, src/pages/recipientValidation/components/tests/__snapshots__/ListResultsCard.test.js.snap, src/reducers/recipientValidation.js
=> EO-480 Support recip validation batch job errors

src/components/summaryTable/Column.js, src/components/summaryTable/SummaryTable.module.scss, src/pages/signals/components/EngagementRecencyOverview.js, src/pages/signals/components/HealthScoreOverview.js, src/pages/signals/components/SpamTrapOverview.js, src/pages/signals/components/dataCells/DataCell.module.scss, src/pages/signals/components/dataCells/FacetDataCell.js, src/pages/signals/components/dataCells/WoWDataCell.js, src/pages/signals/components/dataCells/WoWHeaderCell.js, src/pages/signals/components/dataCells/tests/WoWHeaderCell.test.js, src/pages/signals/components/dataCells/tests/WowDataCell.test.js, src/pages/signals/components/dataCells/tests/__snapshots__/WoWHeaderCell.test.js.snap, src/pages/signals/components/dataCells/tests/__snapshots__/WowDataCell.test.js.snap, src/pages/signals/components/tests/EngagementRecencyOverview.test.js, src/pages/signals/components/tests/HealthScoreOverview.test.js, src/pages/signals/components/tests/SpamTrapOverview.test.js, src/pages/signals/components/tests/__snapshots__/EngagementRecencyOverview.test.js.snap, src/pages/signals/components/tests/__snapshots__/HealthScoreOverview.test.js.snap, src/pages/signals/components/tests/__snapshots__/SpamTrapOverview.test.js.snap, src/selectors/signals.js, src/selectors/tests/__snapshots__/signals.test.js.snap, src/selectors/tests/signals.test.js
=> EO-547 wow

src/pages/users/components/RoleRadioGroup.js, src/pages/users/components/tests/__snapshots__/RoleRadioGroup.test.js.snap
=> AC-591 : Snapshot Update

package-lock.json, package.json
- Fixes pagination bug
- Fixes popover positioning on resize
- Next Page buttons on signals tables should disable without a next page (they are currently always disabled)
- When resizing viewport width down, main content area should not be horizontally scrollable
=> EO-624 FE-574 Bump matchbox

src/pages/alerts-new/components/AlertForm.js, src/pages/alerts-new/components/MultiFacet.module.scss, src/pages/alerts-new/components/tests/__snapshots__/AlertForm.test.js.snap
EO-634: Fix redux-form validation bug
[Bug 1]
Help text does not render correctly when you do not have valid domains to use
[Bug 2]
Investigate a maximum depth exceeded error on input change or assignTo change
Seems to be related to field validation on edit only
=> fixed validation bug

__mocks__/react.js, package-lock.json, src/helpers/math.js, src/helpers/signals.js, src/helpers/tests/math.test.js, src/helpers/tests/signals.test.js, src/pages/signals/components/charts/barchart/BarChart.js, src/pages/signals/components/filters/SubaccountFilter.module.scss, src/pages/signals/constants/healthScoreThresholds.js, src/pages/signals/dashboards/HealthScoreDashboard.js, src/pages/signals/dashboards/components/CurrentHealthGauge/CurrentHealthGauge.js, src/pages/signals/dashboards/components/CurrentHealthGauge/CurrentHealthGauge.module.scss, src/pages/signals/dashboards/components/CurrentHealthGauge/Gauge.js, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/CurrentHealthGauge.test.js, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/Gauge.test.js, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/__snapshots__/CurrentHealthGauge.test.js.snap, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/__snapshots__/Gauge.test.js.snap, src/pages/signals/dashboards/components/MetricDisplay/MetricDisplay.js, src/pages/signals/dashboards/components/MetricDisplay/MetricDisplay.module.scss, src/pages/signals/dashboards/components/MetricDisplay/tests/MetricDisplay.test.js, src/pages/signals/dashboards/components/MetricDisplay/tests/__snapshots__/MetricDisplay.test.js.snap, src/pages/signals/dashboards/tests/__snapshots__/HealthScoreDashboard.test.js.snap, src/selectors/signals.js, src/selectors/tests/__snapshots__/signals.test.js.snap, src/selectors/tests/signals.test.js
This PR isn't opened against master. Will need to do some cleanup with EO-632 when that is ready.
- Added new components to support these mocks: https://sparkpost.invisionapp.com/share/H8R0LV8E5NA#/352294734_Health_Dashboard
- Point your local upstreams to staging
- Log into appteam or enable the `feature_signals_v2` UI option
- Navigate to the new Health Score page from the main side nav
- May hold on this to avoid ballooning this PR
=> EO-628 Health Score Gauge

src/__integration__/__snapshots__/billing.test.js.snap, src/actions/ipPools.js, src/actions/tests/__snapshots__/ipPools.test.js.snap, src/actions/tests/ipPools.test.js, src/pages/ipPools/components/PoolForm.js, src/pages/ipPools/components/tests/PoolForm.test.js, src/pages/ipPools/components/tests/__snapshots__/PoolForm.test.js.snap, src/selectors/ipPools.js, src/selectors/tests/ipPools.test.js
Address SD-800 to fix some UI issues
- Fix issue to set overflow pool during pool creation
- Show overflow pool always (except default) in editing
- Add placeholder overflow and unsetting overflow pool
- Fix logics for listing overflow pools 
- Assign overflow pool during creation
- Unset overflow pool
=> SD-800 Fix IP Autowarmup issues

src/pages/ipPools/components/PoolForm.js, src/pages/ipPools/components/tests/PoolForm.test.js, src/selectors/ipPools.js
Fix issue: overflow disabled during creation of ip pool
=> fix overflow rendering at creation

src/pages/alerts-new/components/AlertForm.js, src/pages/alerts-new/components/tests/AlertForm.test.js
=> fixed normalizer

src/components/pendo/Pendo.js, src/components/pendo/tests/__snapshots__/Pendo.test.js.snap, src/config/env/test-config.js
[FE-648](https://jira.int.messagesystems.com/browse/FE-648)
- Added `release` from config to be sent to pendo, which contains commit hash
- Check that information is being sent to pendo and that information is being properly tracked
=> FE-648: Added release information to pendo

src/helpers/signals.js, src/helpers/tests/signals.test.js, src/pages/signals/EngagementRateByCohortPage.js, src/pages/signals/EngagementRecencyPage.js, src/pages/signals/HealthScorePage.js, src/pages/signals/SpamTrapPage.js, src/pages/signals/UnsubscribeRateByCohortPage.js, src/pages/signals/components/OtherChartsHeader.js, src/pages/signals/components/SignalsPage.js, src/pages/signals/components/charts/barchart/BarChart.js, src/pages/signals/components/tests/__snapshots__/OtherChartsHeader.test.js.snap, src/pages/signals/components/tests/__snapshots__/SignalsPage.test.js.snap, src/pages/signals/constants/healthScoreThresholds.js, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/__snapshots__/CurrentHealthGauge.test.js.snap, src/pages/signals/dashboards/components/CurrentHealthGauge/tests/__snapshots__/Gauge.test.js.snap, src/pages/signals/dashboards/components/HealthScoreChart/HealthScoreChart.js, src/pages/signals/dashboards/components/HealthScoreChart/HealthScoreChart.module.scss, src/pages/signals/dashboards/components/HealthScoreChart/tests/__snapshots__/HealthScoreChart.test.js.snap, src/pages/signals/tests/HealthScorePage.test.js, src/pages/signals/tests/__snapshots__/EngagementRateByCohortPage.test.js.snap, src/pages/signals/tests/__snapshots__/EngagementRecencyPage.test.js.snap, src/pages/signals/tests/__snapshots__/HealthScorePage.test.js.snap, src/pages/signals/tests/__snapshots__/SpamTrapPage.test.js.snap, src/pages/signals/tests/__snapshots__/UnsubscribeRateByCohortPage.test.js.snap
See A/C -> https://jira.int.messagesystems.com/browse/EO-658
- Log into appteam or add the `feature_signals_v2` UI option to your account.
- Visit an overview and details pages
=> EO-658 UX Design Feedback on Signals V2 Pages

src/helpers/email.js, src/helpers/tests/email.test.js, src/selectors/brightback.js, src/selectors/tests/__snapshots__/brightback.test.js.snap, src/selectors/tests/brightback.test.js
- Added company name to brightback selector
- Added subscription monthly cost to brightback selector
- Enter billing page
- Check that company name and monthly cost is included in brightback precancel request
=> AC-513: Added additional info for brightback

package-lock.json, package.json
DSM icon: https://sparkpost.invisionapp.com/dsm/spark-post/spark-post/asset/icons/5c7ab91f4827906340e73f5c
Matchbox storybook: https://sparkpost.github.io/matchbox
**New**
**Old**
- Bumped matchbox
- Nothing special, log into the app and verify the new icon is used
=> EO-700 Bump matchbox-icons for signals icon

package-lock.json, package.json, src/pages/alerts-new/components/AlertForm.js, src/pages/alerts-new/components/MultiFacet.js, src/pages/alerts-new/components/MultiFacet.module.scss, src/pages/alerts-new/components/MultiFacetInput.js, src/pages/alerts-new/components/tests/MultiFacet.test.js, src/pages/alerts-new/components/tests/__snapshots__/AlertForm.test.js.snap
- Upgrades downshift
- Shows full list when field is empty
- Updates list when facet changes
- Test alerts multi facet typeahead
- Test other typeaheads
=> Fix alerts typeahead

src/pages/billing/components/CardSection.js, src/pages/billing/components/tests/CardSection.test.js, src/pages/billing/forms/ChangePlanForm.js, src/pages/billing/forms/tests/ChangePlanForm.test.js, src/pages/billing/forms/tests/__snapshots__/ChangePlanForm.test.js.snap, src/pages/join/components/JoinError.js, src/pages/join/components/tests/__snapshots__/JoinError.test.js.snap
[Link to ticket](https://jira.int.messagesystems.com/browse/AC-701)
- Enabled reinitialize on redux form to allow form to reset on finishing loading country info
- Fixes issue with `State` field not loading even though United States is defaulted country.
- Check that `State` field appears on initial form
- Affects `/account/billing/plan`, and not `/onboarding/plan`
=> AC-701: Enabled reinitialize

src/prototypes/signals/Rec.js
- Shortens some content inside the prototype
- Enable the UI option
- Navigate to the prototype route
=> (Prototype) Shorten button text

src/constants/index.js, src/constants/users.js, src/pages/join/components/JoinError.js, src/pages/join/components/tests/JoinError.test.js, src/pages/join/components/tests/__snapshots__/JoinError.test.js.snap
[AC-743](https://jira.int.messagesystems.com/browse/AC-743)
- Removed support ticket link 
- Chrome dev tools, block request for `api.sparkpost.test/api/v1/account` or `*/api/v1/account`
- Attempt to create account
- Message should read `Something went wrong. Please try again in a few minutes.`
=> AC-743: Removed obsolete link

src/prototypes/signals/DetailsPage.js, src/prototypes/signals/Rec.js, src/prototypes/signals/Rec.module.scss, src/prototypes/signals/Select.js, src/prototypes/signals/Select.module.scss
Design: https://sparkpost.invisionapp.com/share/Z6RM9B67XDU#/358502594_HS_Detail_ACTIONS
- Datefilter custom dates now work
- Makes the add hs component button more obvious
- Adds status icons to each hs component
- Uses a button instead of a link for Fix Now
- Log into appteam or use the ui flag `prototype_signals_details`
- Visit `/prototype/signals-details`
=> UX-80 Signals Prototype Changes

src/pages/templatesV2/EditAndPreviewPage.module.scss, src/pages/templatesV2/components/tests/EditNavigation.test.js, src/pages/templatesV2/components/tests/__snapshots__/EditNavigation.test.js.snap, src/pages/templatesV2/constants/editNavigationLinks.js, src/pages/templatesV2/hooks/useEditorContent.js
- Nav item label is updated - it was done in past but lost in merge/conflict resolution. Hence created separate PR
- Fixes the issue with sometime editor is not allowing edit (in draft mode)
- Added border to nav panel as suggested by Lynn
- Edit a template from V2. You should see the labels like Content to `Email Content`
- You are able to edit template content (html/txt/amp)
- Border is added
=> TR-1560 Update editor nav item labels

src/components/navigation/Navigation.js, src/components/navigation/components/NavGroup.js, src/components/navigation/components/NavItem.js, src/components/navigation/components/NavItem.module.scss, src/components/navigation/components/tests/__snapshots__/NavItem.test.js.snap, src/config/navItems/newNavItems.js, src/selectors/navItems.js
- Updated navigation styling and groups
- Add account ui flag `new_navigation` as true
- Check that navigation matches
- Check that existing navigation still works correctly
=> SA-877: Updated navigation styling

src/pages/alerts/components/AlertForm.js, src/pages/alerts/components/fields/EvaluatorFields.js, src/pages/alerts/components/fields/FilterFields.js, src/pages/alerts/components/fields/tests/FilterFields.test.js, src/pages/alerts/components/fields/tests/__snapshots__/EvaluatorFields.test.js.snap, src/pages/alerts/components/tests/__snapshots__/AlertDetails.test.js.snap, src/pages/alerts/components/tests/__snapshots__/AlertForm.test.js.snap, src/pages/alerts/constants/formConstants.js, src/pages/alerts/helpers/alertForm.js, src/pages/alerts/helpers/tests/alertForm.test.js
* Removed the IP section when theres no IPs on the account
* Updated sliders to have a precision of 0 instead of 2. 
* Various tiny copy changes
=> SE-224 Polish Alerts Create/Edit form

src/pages/billing/components/Banners.js, src/pages/billing/components/tests/__snapshots__/Banners.test.js.snap
AC 874 - Copy change for Premium Add-On on Billing Page
- Description for Enterprise plan and Premium Plan has been changed to the [following](https://jira.int.messagesystems.com/browse/AC-874)
- navigate to `accounts/billing` and verify the text for banners.
=> AC 874 - Copy change for Premium Add-On on Billing Page

src/pages/alerts/components/tests/__snapshots__/AlertForm.test.js.snap, src/pages/alerts/constants/formConstants.js
- Swapping the description for Slack and Webhooks
- Updated snapshots
=> SE-295 Swapping the description for Slack and Webhooks

src/actions/billing.js, src/actions/helpers/mockData.js, src/actions/helpers/mockThunk.js, src/pages/billing/components/FeatureChangeSection.js, src/pages/billing/components/FeatureChangeSection.module.scss, src/pages/billing/components/PlanSelect.js, src/pages/billing/components/tests/FeatureChangeSection.test.js, src/pages/billing/components/tests/PlanSelect.test.js, src/pages/billing/components/tests/__snapshots__/FeatureChangeSection.test.js.snap, src/pages/billing/context/FeatureChangeContext.js, src/pages/billing/context/tests/FeatureChangeContext.test.js, src/pages/billing/context/tests/__snapshots__/FeatureChangeContext.test.js.snap, src/pages/billing/forms/NewChangePlanForm.js, src/pages/billing/forms/tests/NewChangePlanForm.test.js, src/pages/billing/forms/tests/__snapshots__/NewChangePlanForm.test.js.snap, src/reducers/billing.js, src/selectors/accountBillingInfo.js
- Added feature change section which lists features that would be removed or need to change before plan change
- Go to new plan select
- Choose free or lower plan tier
- Check that feature changes populate and should be acknowledged
=> AC-987: Feature comparison section

src/pages/auth/components/SsoLoginForm.js, src/pages/auth/components/TfaForm.js, src/pages/auth/components/TfaForm.module.scss, src/pages/auth/components/tests/Tfaform.test.js, src/pages/auth/components/tests/__snapshots__/SsoLoginForm.test.js.snap
AC-1013 - New help contact address for TFA or SSO users who are locked out
- All errors associated with TFA logging in append "Please contact login.issues@sparkpost.com for assistance" in the UI.
- All errors associated with SSO logging in append "Please contact login.issues@sparkpost.com for assistance" in the UI.
- Try out TFA login and check the error message.
- Try out SSO login and check the error message.
=> AC-1013 - New help contact address for TFA or SSO users who are locked out

src/components/percentWheel/PercentWheel.js, src/components/percentWheel/PercentWheel.module.scss, src/components/percentWheel/index.js, src/components/percentWheel/tests/PercentWheel.test.js, src/components/percentWheel/tests/__snapshots__/PercentWheel.test.js.snap, src/pages/inboxPlacement/components/AuthenticationResults.js, src/pages/inboxPlacement/components/FolderPlacementBarChart.js, src/pages/inboxPlacement/components/ProvidersBreakdown.js, src/pages/inboxPlacement/components/ProvidersBreakdown.module.scss, src/pages/inboxPlacement/components/TestDetails.js, src/pages/inboxPlacement/components/TestDetails.module.scss, src/pages/inboxPlacement/components/TimeToReceiveSection.js, src/pages/inboxPlacement/components/tests/AuthenticationResults.test.js, src/pages/inboxPlacement/components/tests/ProvidersBreakdown.test.js, src/pages/inboxPlacement/components/tests/TimeToReceiveSection.test.js, src/pages/inboxPlacement/components/tests/__snapshots__/ProvidersBreakdown.test.js.snap, src/pages/inboxPlacement/components/tests/__snapshots__/TestDetails.test.js.snap, src/pages/inboxPlacement/constants/graphs.js, src/pages/inboxPlacement/constants/percentWheel.js
- Added authentication section to Placement table and inbox details header
- Added Time to Receive values
- Go to `/inbox-placement`
- Navigate to one of the test details
- Verify that the sections match the mockup
=> SA-832: Test details include authentication + time to receive

.eslintrc, config/jest/setup.js, package-lock.json, package.json, src/components/panelLoading/PanelLoading.js, src/components/panelLoading/tests/__snapshots__/PanelLoading.test.js.snap, src/pages/templates/components/SendTestEmailButton.js, src/pages/templates/components/tests/SendTestEmailButton.test.js
[FE-765](https://jira.int.messagesystems.com/browse/FE-765)
- Installs `@testing-library/react` ➡️ https://github.com/testing-library/react-testing-library
- Installs supporting matcher library `@testing-library/jest-dom` ➡️ https://github.com/testing-library/jest-dom
- Installs supporting user event simulation library `@testing-library/user-event` for typing and click simulation ➡️ https://github.com/testing-library/user-event
- Installs supporting ESLint plugin to encourage best practices `eslint-plugin-testing-library` ➡️ https://github.com/Belco90/eslint-plugin-testing-library
- Added `data-id` attribute to `<PanelLoading/>` component
- Configured default test ID attribute to `data-id` instead of `data-testid`
- Updated Jest setup script to catch warnings with exception for bug with …
=> FE-765 - Adds React Testing Library

src/pages/dashboard/DashboardPage.js, src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/GuideListItem.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/dashboard/constants.js, src/pages/dashboard/tests/DashboardPage.test.js, src/pages/dashboard/tests/__snapshots__/DashboardPage.test.js.snap, src/pages/templates/components/PreviewControlBar.js, src/pages/templates/components/tests/__snapshots__/PreviewControlBar.test.js.snap, src/reducers/account.js, src/reducers/tests/account.test.js
AC-1083 - "Show Me SparkPost" checklist item for sending test email
- "Show Me SparkPost" Button directs to the Templates page / starts the guide in AC-1107
- Condition is stored in UI option on clicking the button and navigating to the Templates page. (The ListItem will have a green tick and button is no longer orange)
-  Click on 'Start Sending' then 'Show Me SparkPost' then 'Send a Test Email'.
-  Check if click on Send a Test Email button redirects to /templates page, check after redirection 
the list item is completed(green tick and button is no longer orange. )
=> AC-1083 - "Show Me SparkPost" checklist item for sending test email

src/pages/blacklist/IncidentsPage.js
- Removed accidental semicolon
- goto /blacklists
=> SA-986-2: Removed accidental semicolon

src/__func__/auth/__snapshots__/login.test.js.snap, src/__func__/auth/__snapshots__/loginRememberMe.test.js.snap, src/__func__/auth/__snapshots__/ssoReturn.test.js.snap, src/__func__/auth/__snapshots__/tfa.test.js.snap, src/__func__/auth/__snapshots__/tfaEnableOnLogin.test.js.snap, src/__func__/signup/__snapshots__/choosePaidPlan.test.js.snap, src/__func__/signup/__snapshots__/chooseTestPlan.test.js.snap, src/__func__/signup/__snapshots__/join.test.js.snap, src/__func__/signup/__snapshots__/joinEmailOptIn.test.js.snap, src/__func__/signup/__snapshots__/sendingDomain.test.js.snap, src/__testHelpers__/http-responses/default/v1/billing/subscription/get.js, src/__testHelpers__/http-responses/paid/v1/billing/subscription/get.js, src/actions/accessControl.js, src/actions/billing.js, src/actions/tests/accessControl.test.js, src/config/routes/index.js, src/helpers/conditions/account.js, src/helpers/conditions/tests/account.test.js, src/pages/billing/components/ManuallyBilledBanner.js, src/pages/billing/components/tests/__snapshots__/ManuallyBilledBanner.test.js.snap, src/pages/billing/forms/EnableAutomaticBillingForm.js, src/pages/billing/forms/tests/EnableAutomaticBillingForm.test.js, src/pages/billing/forms/tests/__snapshots__/EnableAutomaticBillingForm.test.js.snap, src/selectors/accessConditionState.js, src/selectors/tests/__snapshots__/accountBillingInfo.test.js.snap, src/selectors/tests/accessConditionState.test.js, src/selectors/tests/accountBillingInfo.test.js
This reverts commit e6e8077f2330158dda5ddbf9d235e2ca6f4d383c, reversing
changes made to 60a11aeb43b1da88c055e53e4c579ae242528f74.
=> Revert "Merge branch 'AC-921'"

src/pages/sendingDomains/DelegatedDomainPage.js, src/pages/sendingDomains/hack.css
- What changes did you make to satisfy the AC?
> Outline changes to user flows, any surprising architectural decisions 
> Alignment between PR commits and this section helps your reviewers.
- Describe any special dev environment setup required.
> Anything outside basic hamurai-managed stuff counts as "special".
> Manage reviewers' expectations on missing features, tests, bugs, late design changes, ...)
=> styled table with mock data

src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/dashboard/constants.js
AC-1085 - "Show Me SparkPost" checklist item for starting to send
- What changes did you make to satisfy the AC?
- Clicking on 'Invite a Collaborator' links to /account/users.
- Clicking on 'setup email sending now' takes to the Let's Code step of the guide.
- Performing any one of the above steps marks the 'Invite you Team' GuideListItem as completed(green tick and the action button is no longer orange)
- Enable "messaging_onboarding" flag.
- Check if the above mentioned changes work as expected.
=> AC-1085 - "Show Me SparkPost" checklist item for starting to send

Procfile, README.md, package-lock.json, package.json
Installs Foreman to run the app and Storybook simultaneously
- Installs `foreman`
- Adds a `Procfile` to define commands Foreman runs
- Updates README to describe changes
- Updates NPM scripts - renames `npm start` => `npm start-app`
- `npm start` script runs the app and Storybook via commands configured in the `Procfile`. The `FORCE_COLOR` environment variable ensures color output from underlying scripts is preserved
- Ensure both the app and Storybook run simultaneously 
- Ensure live reload works for both the app and Storybook when making changes
=> Installs Foreman to run the app and Storybook simultaneously

src/components/usageReport/SendMoreCTA.js, src/components/usageReport/tests/SendMoreCTA.test.js, src/components/usageReport/tests/__snapshots__/SendMoreCTA.test.js.snap, src/components/usageReport/tests/__snapshots__/UsageReport.test.js.snap, src/components/verifyEmailBanner/VerifyEmailBanner.js, src/components/verifyEmailBanner/tests/__snapshots__/VerifyEmailBanner.test.js.snap
- Removed note to increase limits from /dashboard
- Create new account
- Go to `/dashboard`
- Banner should have all references to verifying email increasing daily limits removed
=> AC-1093: Removed references to increasing limits

src/pages/dashboard/DashboardPage.js, src/pages/dashboard/components/GettingStartedGuide.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/dashboard/tests/DashboardPage.test.js, src/pages/dashboard/tests/__snapshots__/DashboardPage.test.js.snap
- Check added on grants to render the guide
- With a reporting user, check the dashboard page
- Should no longer 403 or render guide list
- onboarding.ui option is not stored for developer role for now.
=> AC-1188: Onboarding guide

src/App.js, src/components/vwo/VisualWebsiteOptimizer.js, src/components/vwo/tests/VisualWebsiteOptimizer.test.js, src/components/vwo/tests/__snapshots__/VisualWebsiteOptimizer.test.js.snap, src/config/env/production-config.js
- Added script tag from https://app.vwo.com/#/settings/code?token=eyJhY2NvdW50X2lkIjo0NjE1NjUsInR5cGUiOiJ0cmFja2luZ0NvZGUiLCJ2ZXJzaW9uIjoxLCJoYXNoIjoiMjFiYzQ3NTU0MTcxOTcwMzE3MDRlZmRlMWZiZjllZDQifQ%3D%3D&integrationType=vwo-async to our head tag in the app, only on production
- Verify with Smartcode Checker on above page
- Interact with the app and see requests made to https://dev.visualwebsiteoptimizer.com/settings.js
=> FE-804 Add VWO script to head in prod

src/selectors/blacklist.js, src/selectors/tests/blacklist.test.js
- Fixed days listed for resolved date
- Go to blacklist/incidents
- Click on any incident.
- Verify that the days listed is correct.
=> SA-1162: Fix days listed for resolved incidents

src/pages/blacklist/IncidentsPage.js, src/pages/blacklist/WatchlistAddPage.js, src/pages/blacklist/WatchlistPage.js, src/pages/blacklist/components/CongratsBanner.js, src/pages/blacklist/components/StopMonitoringModal.js, src/pages/blacklist/components/tests/StopMonitoringModal.test.js, src/pages/blacklist/tests/WatchlistAddPage.test.js
- Lots of text.
- Check that all the text is correct. 
- Documentation links are not present.
- Success Banner for incidents page is unchanged for now.
=> SA-1143: Update Text For Blacklist

src/actions/blacklist.js, src/actions/tests/blacklist.test.js, src/pages/alerts/DetailsPage.js, src/pages/alerts/components/AlertDetails.js, src/pages/alerts/components/AlertForm.js, src/pages/alerts/components/fields/FilterFields.js, src/pages/alerts/components/fields/tests/FilterFields.test.js, src/pages/alerts/components/tests/AlertDetails.test.js, src/pages/alerts/components/tests/AlertForm.test.js, src/pages/alerts/components/tests/__snapshots__/AlertForm.test.js.snap, src/pages/alerts/constants/formConstants.js, src/pages/alerts/helpers/alertForm.js, src/pages/alerts/helpers/formatFormValues.js, src/pages/alerts/helpers/tests/formatFormValues.test.js, src/pages/alerts/tests/DetailsPage.test.js, src/reducers/blacklist.js, src/reducers/tests/__snapshots__/blacklist.test.js.snap, src/reducers/tests/blacklist.test.js, src/selectors/alerts.js, src/selectors/tests/alerts.test.js
See [SE-477](https://jira.int.messagesystems.com/browse/SE-477)
- New "Blacklists" alert metric option
**Please note that the API is ready, so we can't test everything** 
- Set the account option
- Navigate to /alerts
- Click "Create an Alert"
- Select "Blacklists" from "Alert Metric" dropdown
- Fill-out rest of the form
- Click "Creeate Alert"
=> SE-477: Blacklist Alerts Create & Edit

README.md
=> Fix Codecov badge link

src/pages/onboarding/RVBundlePage.js, src/pages/onboarding/RVBundlePage.module.scss, src/pages/onboarding/tests/RVBundle.test.js
- Added modal to show pricing 
- Navigate to `/onboarding/recipient-validation`
- Click on `See Pricing` in the RV Panel
- Verify that the modal matches the mocks
=> AC-1120: Added modal to show pricing

src/config/routes/index.js, src/pages/join/JoinPage.js, src/pages/join/tests/JoinPage.test.js, src/pages/onboarding/RVBundlePage.js, src/pages/onboarding/RVBundlePage.module.scss, src/pages/onboarding/components/CreditCardSection.js, src/pages/onboarding/components/tests/__snapshots__/CreditCardSection.test.js.snap, src/pages/onboarding/index.js
- New page after joining which directs to recipient validation
- Log out and go to path /join?product=rv
- Sign up and should navigate to /onboarding/recipient-validation
- Verify that copy is correct and matches mocks
- Verify that link navigates to RV page after
=> AC-1119: New sign up flow for RV

.eslintrc
- Added no-console rule to Eslint.
- Add a console.log statement to any file. Try to commit the changes. Verify that an error occurs and the commit does not happen.
=> FE-837: add eslint rule to disallow console

.github/pull_request_template.md
Updated Github PR template. Might not work until merged to master?
=> FE-842: add reminder to check user roles and include feature flags

cypress/fixtures/authenticate/grants/200.get.admin.json, cypress/tests/integration/recipients/recipient-validation/list-page-routes/listRoute.spec.js, cypress/tests/integration/recipients/recipient-validation/list-page-routes/singleRoute.spec.js, cypress/tests/integration/recipients/recipient-validation/listConfirmationPage.spec.js, cypress/tests/integration/recipients/recipient-validation/listPage.spec.js, cypress/tests/integration/recipients/recipient-validation/listProgressPage.spec.js, package.json, src/config/routes/index.js, src/helpers/conditions/account.js
- Check for standalone_rv flag is defaulted to true (code cleanup in separate ticket)
- Go to RV and check that each flow works correctly
- List Upload
- Single Validation
- API Key
- Check that the integration tests work
=> AC-1122: Release standalone RV

scripts/build.js, scripts/copyMatchboxStyles.js
This is follow-up for FE-830.  It is currently in staging, but we caught an issue that the stylesheets were not in present.  Turned out to be an issue with the scripts/build.js.
=> FE-830: [Follow-up] Implement Hibana app styling controlled by theme context

.travis.yml, config/cypressBatches.js, cypress/plugins/index.js, cypress/support/index.js, cypress/tests/integration/alerts/createPage.spec.js, cypress/tests/integration/signals-analytics/summaryReport.spec.js, src/components/layout/Layout.js, src/components/layout/tests/__snapshots__/Layout.test.js.snap
[FE-901](https://jira.int.messagesystems.com/browse/FE-901)
- Adds `defer={false}` prop to `<Helmet>` instance that controls the `<title>`
- Adds new commands to Cypress to ensure `cy.log()` outputs to the Node console during headless runs
- Cleans up deep equality check by stringifying the network response
- Updates obsolete snapshots for the Layout component
1. Log in to the app in staging or prod and open a new tab
1. Verify the bug exists by verifying the `<title>` only updates when the relevant tab receives focus
1. Log in to the app locally and open a new tab
1. Verify the page title shows in the new tab without focusing the tab
=> FE-901 - Resolve <title> not updating when new tab is opened

package-lock.json, package.json, src/components/typeahead/tests/__snapshots__/InboxPlacementTypeahead.test.js.snap
- Upgraded Matchbox to v3.9.1 to fix styling of tags, specifically when there is a close button
Upgrade also includes...
- Slider should now work correctly with positive min values [#298](https://github.com/SparkPost/matchbox/pull/298) [#304](https://github.com/SparkPost/matchbox/pull/304)
- The prop defaultValue is no longer set to 0 by defaultProps
- Slider now passes through the attribute aria-controls [#298](https://github.com/SparkPost/matchbox/pull/298)
- matchbox-icons is now listed as a peer dependency [#302](https://github.com/SparkPost/matchbox/pull/302)
- Added various Cypress tests [#304](https://github.com/SparkPost/matchbox/pull/304) [#305](https://github.com/SparkPost/matchbox/pull/305) [#306](https://github.com/SparkPost/matchbox/pull/306)
- Confirm filter tags on summary …
=> FE-921 Tag contents and close button are not vertically aligned

src/components/matchbox/README.md, src/components/matchbox/Stack.js, src/components/matchbox/index.js, src/components/matchbox/tests/Stack.test.js
- Hibana wrapper for new stack component. 
- Fixed filenames in index.js
- Could add something like 
```html 
<Stack space ="200">   
<Box
bg="blue.400"
p="200"
>
Foo
</Box>
<Box
bg="blue.400"
p="200"
>
Bar
</Box>
</Stack>
```
And check that the hibana and no hibana are different
=> FE-889 Hibana wrapper for Stack

src/components/matchbox/Slider.js, src/components/matchbox/index.js, src/components/matchbox/tests/Slider.test.js, src/components/reduxFormWrappers/SliderFieldWrapper.js, src/components/reduxFormWrappers/tests/SliderFieldWrapper.test.js
[FE-887](https://jira.int.messagesystems.com/browse/FE-887)
- Adds <Slider/> component wrapper
- Updates unit tests accordingly
- Go to /alerts and edit or create an alert (and select a metric)
- Verify components visually
=> FE-887: Component wrapper for matchbox slider

src/components/matchbox/Table.js
FE-890-2 whitelisting width in HeaderCell
- whitelisted width in HeaderCell
- Check engagement recency page
=> FE-890-2 whitelisting width in HeaderCell

src/components/summaryTable/HeaderLabel.js, src/pages/recipientValidation/components/JobsTableCollection.js, src/pages/reports/delays/components/DelaysDataTable.js
[FE-890-3] missed Table imports DelayedDataTable and JobsTableCollection
- added Table component wrapper imports DelayedDataTable and JobsTableCollection
- Check DelayedDataTable and JobsTableCollection
=> FE-890-3 - missed Table imports DelayedDataTable and JobsTableCollection

src/components/collection/Pagination.js, src/components/matchbox/Pagination.js, src/components/matchbox/index.js, src/components/matchbox/tests/Pagination.test.js, src/components/summaryTable/SummaryTable.js, src/components/summaryTable/tests/__snapshots__/SummaryTable.test.js.snap
- Pagination component wrapper
- Verify that Tables pagination are working correctly (for default)
- More unique pagination on Signals pages + events summary
=> FE-880: Pagination component wrapper

package-lock.json, package.json, src/components/matchbox/Radio.js, src/components/matchbox/index.js, src/components/matchbox/tests/Radio.test.js, src/components/matchbox/tests/Tooltip.test.js, src/components/reduxFormWrappers/RadioGroup.js, src/components/reduxFormWrappers/tests/RadioGroup.test.js, src/components/reduxFormWrappers/tests/__snapshots__/RadioGroup.test.js.snap, src/components/subaccountSection/SubaccountSection.js, src/pages/api-keys/components/ApiKeyForm.js, src/pages/api-keys/components/tests/__snapshots__/ApiKeyForm.test.js.snap, src/pages/sendingDomains/components/SubaccountForm.js, src/pages/sendingDomains/components/tests/__snapshots__/SubaccountForm.test.js.snap, src/pages/subaccounts/components/formFields.js, src/pages/subaccounts/components/test/__snapshots__/formFields.test.js.snap, src/pages/users/components/RoleRadioGroup.js, src/pages/users/components/tests/__snapshots__/RoleRadioGroup.test.js.snap, src/pages/webhooks/components/Fields.js, src/pages/webhooks/components/SubaccountSection.js, src/pages/webhooks/components/tests/__snapshots__/Fields.test.js.snap, src/pages/webhooks/components/tests/__snapshots__/SubaccountSection.test.js.snap
FE-885 : Component Wrapper for Matchbox Radio
- Added Component Wrapper for Radio
- Hibana version bumped to 12.
- it is present on 
- /account/data-privacy/multiple-recipients
- /templates/create
=> FE 885 - Component Wrapper for Matchbox Radio

src/pages/reports/summary/SummaryPage.js, src/pages/reports/summary/SummaryPage.module.scss, src/pages/reports/summary/tests/SummaryPage.test.js
This reverts commit 706ec28086899fb6b7a8eaf1f037721cf74c8c66.
=> SA-1304 Remove precision & timezone label from summary page chart

src/pages/ipPools/EditIpPage.js, src/pages/ipPools/EditIpPageHibana.module.scss, src/pages/ipPools/EditPage.js, src/pages/ipPools/ListPage.js, src/pages/ipPools/components/IpForm.js, src/pages/ipPools/components/IpFormHibana.module.scss, src/pages/ipPools/components/PoolForm.js, src/pages/ipPools/components/tests/IpForm.test.js, src/pages/ipPools/components/tests/__snapshots__/PoolForm.test.js.snap, src/pages/ipPools/tests/EditPage.test.js, src/pages/ipPools/tests/__snapshots__/EditPage.test.js.snap, src/pages/ipPools/tests/__snapshots__/ListPage.test.js.snap
FE-969 : Hibana style cleanup for IP pools pages
- Updated IP pools ListPage, Create IP pools form, edit ip pool form
- visit 
/account/ip-pools
/account/ip-pools/create
/account/ip-pools/edit/:poolId
/account/ip-pools/edit/:poolId/:ip
and check if there is anything that needs update in styling.
- mocks: https://sparkpost.invisionapp.com/share/QKWORJ4DM4Y#/screens
=> FE-969 : Hibana style cleanup for IP pools pages

src/actions/helpers/zuoraApiError.js, src/actions/helpers/zuoraRequest.js
zuoraApiError and changes to zuoraRequest
=> zuoraApiError and changes to zuoraRequest

src/pages/reportBuilder/components/AddFiltersSection.js, src/pages/reportBuilder/components/ReportOptions.js, src/pages/reportBuilder/components/Typeahead.js, src/selectors/reportFilterTypeaheadCache.js
- Subaccount filtering fixed on report builder
- Go to Report builder
- Click Add filters
- Test different filters + types
=> SA-1329: Fixes for subaccount filtering

cypress/support/index.js, cypress/tests/integration/accounts/auth/logInPage.spec.js, src/components/matchbox/README.md, src/constants/index.js, src/helpers/analytics/eventsMapper.js, src/helpers/hibana.js, src/helpers/tests/hibana.test.js, src/hooks/usePageFilters/usePageFilters.js, src/hooks/usePageFilters/usePageFilters.test.js, src/pages/blacklist/IncidentsPage.js, src/pages/inboxPlacement/TestListPage.js, src/pages/signals/IntegrationPage.js
- Find and replace on all uses of "whitelist" or "whitelabel" in repo
- Check build to confirm Cypress tests don't break
- Confirm `usePageFilters` hook is working as expected on /blacklist/incidents and /inbox-placement
=> FE-1101: Change whitelist to allowlist in 2web2ui

src/__func__/signup/__snapshots__/join.test.js.snap, src/__func__/signup/__snapshots__/joinEmailOptIn.test.js.snap, src/pages/join/JoinPage.js, src/pages/join/tests/JoinPage.test.js, src/pages/join/tests/__snapshots__/JoinPage.test.js.snap, src/pages/sendingDomains/components/SetupSending.js
AC-1563: (UI) VWO Tracking for Video Test
- `Verifies Sending Domain` is being tracked in VWO
- set a user option on the basis of the request params(video=true or video=false) received on sign up and trigger different goals on that basis.
- Signup with following variations
- /join?video=false
- /join?video=true
- /join
- Check if different vwo goals get triggered based on these variations
- Check for different roles.
- vwo test - https://app.vwo.com/#/test/ab/24/summary
=> AC-1563: (UI) VWO Tracking for Video Test

src/pages/alerts/CreatePage.js, src/pages/alerts/tests/CreatePage.test.js
- Sending an event every time an Alert is created
- Complete the Create an Alert form
- Check the segment debugger to find the event: https://app.segment.com/sparkpost-daniel-chalef/sources/webui_dev/debugger
=> AC-1620 Create Alert Segment Integration

cypress/fixtures/users/200.get.reporting.json, cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js, package-lock.json, src/components/picture/Picture.js, src/pages/dashboardV2/DashboardPageV2.container.js, src/pages/dashboardV2/DashboardPageV2.js, src/pages/dashboardV2/components/Dashboard.js, src/pages/dashboardV2/components/Sidebar.js
[FE-1170](https://sparkpost.atlassian.net/browse/FE-1170)
**Note:** Still waiting to merge this one in - this branch is based on https://github.com/SparkPost/2web2ui/pulls
- Adds conditional rendering based on roles and grants to the Dashboard container component.
- Adds supporting tests for conditional rendering states
- Moves some of the dashboard content around to match the mocks
- Verify `/dashboardV2` with each user role, and verify that these sections render according to the mocks attached in the ticket
=> FE-1170 - [Dashboard UX Redesign] Incorporate conditional rendering per user role

src/helpers/segment.js
- Send Segment utms from URL if they exist on all page calls
- Add a UTM to a url in the app like: https://app.sparkpost.test/dashboard?utm_medium=test
- Verify it shows up in the debugger: https://app.segment.com/sparkpost-daniel-chalef/sources/webui_dev/debugger
=> AC-1695 Add UTMs to page calls in app

cypress/fixtures/account/200.get.json, src/components/matchbox/Button.js, src/components/typeahead/TimezoneTypeahead.js, src/components/typeahead/tests/TimezoneTypeahead.test.js, src/pages/account/components/SingleSignOnPanel/SCIMTokenSection.js, src/pages/account/components/SingleSignOnPanel/SingleSignOnPanel.js, src/pages/account/components/SingleSignOnPanel/tests/SingleSignOnPanel.test.js
AC-1522 -  Removed feature flag - sso_scim_section and used cool new button loading states 
- Removed feature flag - sso_scim_section
- Used cool new button loading states 
- SSO SCIM Section is visible to users without enabling the feature flag
- Check the loading states for buttons
=> AC-1522 -  Removed feature flag - sso_scim_section and added cool new button loading states

src/pages/domains/components/LinkTrackingDomainSection.js, src/pages/domains/components/SendingAndBounceDomainSection.js, src/pages/domains/components/SetupBounceDomainSection.js, src/pages/domains/components/SetupForSending.js, src/pages/domains/components/TrackingDnsSection.js
=> [FE-1204-suggestions] suggestions

cypress/tests/integration/domains/listPage.spec.js, src/pages/domains/components/SendingDomainsTab.js, src/pages/domains/components/TableFilters.js, src/pages/domains/components/TrackingDomainsTab.js
FE-1234 - Last few cleanup items on domains page
- Visually hide the Apply button
- Added Select all checkbox for domain status filter
- Input placeholder text for domain name
- Sending domain tab  - Rename Sending -> Verified in Domain status filter
- Bounce Domain tab - Remove Bounce from the list
- Tracking domain tab  - Rename Tracking -> Verified in Domain status filter
- testing if all the above changes look good 
mock - https://sparkpost.invisionapp.com/console/share/CF19LDYPB2/478910828
=> FE-1234 - Last few cleanup items on domains page

src/context/HibanaContext.js, src/pages/dashboard/components/tests/GettingStartedGuide.test.js, src/pages/subaccounts/components/SendingDomainsTab.js, src/pages/subaccounts/components/test/SendingDomainsTab.test.js, src/pages/subaccounts/components/test/__snapshots__/SendingDomainsTab.test.js.snap
- Wanted to maintain test coverage for FE-1244
- Mainly wanted the experience with jest/contexts
- `npm run test` or let circle do it
=> FE-1244 - review testing/learning/feedback

cypress/fixtures/404.json, cypress/fixtures/account/200.get.has-scheduled-reports.json, cypress/tests/integration/signals-analytics/analytics-report/savedReports.spec.js, cypress/tests/integration/signals-analytics/analytics-report/scheduledReports.spec.js, src/actions/reports.js, src/actions/tests/reports.test.js, src/config/routes/signals.js, src/pages/reportBuilder/ScheduledReportCreatePage.js, src/pages/reportBuilder/ScheduledReportEditPage.js, src/pages/reportBuilder/components/ReportsListModal.js, src/pages/reportBuilder/components/ReportsListModalTabs.js, src/pages/reportBuilder/components/SavedReportsSection/SavedReportsSection.js, src/pages/reportBuilder/components/SavedReportsSection/tests/SavedReportsSection.test.js, src/pages/reportBuilder/helpers/scheduledReports.js, src/pages/reportBuilder/helpers/tests/scheduledReports.test.js, src/reducers/reports.js
Reverts SparkPost/2web2ui#1959
=> Revert "SA-1896: Release Scheduled Reports"

cypress/tests/integration/signals-analytics/analytics-report/reportPage.spec.js, cypress/tests/integration/signals-analytics/dateAndTimeSection.spec.js, cypress/tests/integration/signals-analytics/summaryReport.spec.js, src/actions/metrics.js, src/actions/tests/__snapshots__/metrics.test.js.snap, src/helpers/api/metrics.js, src/pages/reportBuilder/components/ActiveMetrics.js, src/pages/reportBuilder/components/tests/ActiveMetrics.test.js, src/selectors/metrics.js
Reverts SparkPost/2web2ui#2022
=> Revert "SA-1117: Change UI to use rollups"

cypress/tests/integration/dashboardV2/dashboardPageV2.spec.js, src/constants/index.js, src/pages/dashboardV2/DashboardPageV2.js
- Updated Link in "Integration Docs" on new dashboard to https://www.sparkpost.com/docs/getting-started/getting-started-sparkpost/
- Integration Docs links to https://www.sparkpost.com/docs/getting-started/getting-started-sparkpost/
=> [FE-1342] Updated link to Integration Docs

src/pages/dashboardV2/components/Sidebar.js
- Added Upgrade Icon to Dashboard Upgrade Link
- Check Upgrade link has Icon with it on Dashboard 
mock - https://sparkpost.invisionapp.com/console/Progressive-Onboarding-ckfe1rusj0cqn0185gnro5f8c
=> [FE-1330] Add Upgrade Icon to Dashboard Upgrade Link

src/pages/signals/HealthScorePage.js, src/pages/signals/SpamTrapPage.js, src/pages/signals/components/filters/SubaccountFilter.js, src/pages/signals/components/viewControls/ControlGroup.js
FE-1385 - Resolve code scanning warning for 2web2ui - src/pages/signals/*
- Fixed Potentially inconsistent state update issue  
Ref - https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous
- https://github.com/SparkPost/2web2ui/security/code-scanning/23?query=ref%3Arefs%2Fheads%2Fmaster
- https://github.com/SparkPost/2web2ui/security/code-scanning/22?query=ref%3Arefs%2Fheads%2Fmaster
- Fixed Useless conditions
- https://github.com/SparkPost/2web2ui/security/code-scanning/68?query=ref%3Arefs%2Fheads%2Fmaster
- https://github.com/SparkPost/2web2ui/security/code-scanning/67?query=ref%3Arefs%2Fheads%2Fmaster
- https://github.com/SparkPost/2web2ui/security/code-scanning/78?query=ref%3Arefs%2Fheads%2Fmaster
- Check if subaccount filter on Healthscore works correctly …
=> FE-1385 - Resolve code scanning warning for 2web2ui - src/pages/signals/*

src/pages/defaultRedirect/DefaultRedirect.js, src/pages/defaultRedirect/tests/DefaultRedirect.test.js, src/pages/sso/SSOPage.js, src/pages/sso/tests/SSOPage.test.js, src/pages/sso/tests/__snapshots__/SSOPage.test.js.snap, src/reducers/auth.js
Reverts SparkPost/2web2ui#2107
=> Revert "AC-1911: Unable to re-enter webui when using SSO and Safari"
